export interface Country {
  code: string
  name: string
  states?: string[]
  provinces?: string[]
}

export const COUNTRIES: Country[] = [
  {
    code: "US",
    name: "United States",
    states: [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
    ],
  },
  {
    code: "IN",
    name: "India",
    states: [
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chhattisgarh",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
    ],
  },
  {
    code: "BR",
    name: "Brazil",
    states: [
      "Acre",
      "Alagoas",
      "Amapá",
      "Amazonas",
      "Bahia",
      "Ceará",
      "Distrito Federal",
      "Espírito Santo",
      "Goiás",
      "Maranhão",
      "Mato Grosso",
      "Mato Grosso do Sul",
      "Minas Gerais",
      "Pará",
      "Paraíba",
      "Paraná",
      "Pernambuco",
      "Piauí",
      "Rio de Janeiro",
      "Rio Grande do Norte",
      "Rio Grande do Sul",
      "Rondônia",
      "Roraima",
      "Santa Catarina",
      "São Paulo",
      "Sergipe",
      "Tocantins",
    ],
  },
  {
    code: "GB",
    name: "United Kingdom",
    states: ["England", "Scotland", "Wales", "Northern Ireland"],
  },
  {
    code: "VN",
    name: "Vietnam",
    provinces: [
      "Ho Chi Minh City",
      "Hanoi",
      "Da Nang",
      "Can Tho",
      "Hai Phong",
      "Bien Hoa",
      "Nha Trang",
      "Hue",
      "Vung Tau",
      "Buon Ma Thuot",
    ],
  },
  {
    code: "NG",
    name: "Nigeria",
    states: ["Lagos", "Kano", "Ibadan", "Kaduna", "Port Harcourt", "Benin City", "Maiduguri", "Zaria", "Aba", "Jos"],
  },
  {
    code: "ID",
    name: "Indonesia",
    provinces: [
      "Jakarta",
      "Surabaya",
      "Bandung",
      "Medan",
      "Semarang",
      "Makassar",
      "Palembang",
      "Tangerang",
      "Depok",
      "Bekasi",
    ],
  },
  {
    code: "KR",
    name: "South Korea",
    provinces: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Goyang"],
  },
  {
    code: "FR",
    name: "France",
    states: [
      "Île-de-France",
      "Auvergne-Rhône-Alpes",
      "Nouvelle-Aquitaine",
      "Occitanie",
      "Hauts-de-France",
      "Provence-Alpes-Côte d'Azur",
      "Grand Est",
      "Pays de la Loire",
      "Bretagne",
      "Normandie",
      "Bourgogne-Franche-Comté",
      "Centre-Val de Loire",
      "Corse",
    ],
  },
  {
    code: "MX",
    name: "Mexico",
    states: [
      "Aguascalientes",
      "Baja California",
      "Baja California Sur",
      "Campeche",
      "Chiapas",
      "Chihuahua",
      "Coahuila",
      "Colima",
      "Durango",
      "Guanajuato",
      "Guerrero",
      "Hidalgo",
      "Jalisco",
      "México",
      "Michoacán",
      "Morelos",
      "Nayarit",
      "Nuevo León",
      "Oaxaca",
      "Puebla",
      "Querétaro",
      "Quintana Roo",
      "San Luis Potosí",
      "Sinaloa",
      "Sonora",
      "Tabasco",
      "Tamaulipas",
      "Tlaxcala",
      "Veracruz",
      "Yucatán",
      "Zacatecas",
      "Mexico City",
    ],
  },
  {
    code: "PH",
    name: "Philippines",
    provinces: [
      "Metro Manila",
      "Cebu",
      "Davao",
      "Cagayan de Oro",
      "Zamboanga",
      "Bacolod",
      "Iloilo",
      "Baguio",
      "Tagaytay",
      "Bohol",
    ],
  },
]

export class LocationsDB {
  static getCountries(): Country[] {
    return COUNTRIES
  }

  static getCountry(code: string): Country | undefined {
    return COUNTRIES.find((c) => c.code === code)
  }

  static getStatesOrProvinces(countryCode: string): string[] {
    const country = this.getCountry(countryCode)
    return country?.states || country?.provinces || []
  }

  static getLocationLabel(countryCode: string): string {
    const country = this.getCountry(countryCode)
    if (country?.states) return "State"
    if (country?.provinces) return "Province/Region"
    return "Region"
  }
}

export default LocationsDB
