-- =====================================================
-- BATCHES 5-7: General Knowledge Questions (150 questions)
-- From Open Trivia Database - Batches 5, 6, 7
-- =====================================================

INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, category, difficulty) VALUES
-- BATCH 5 (50 questions)
('What is the official language of Costa Rica?', 'Portuguese', 'English', 'Creole', 'Spanish', 'D', 'general', 'rookie'),
('What is the name of the popular animatronic singing fish prop, singing such hits such as "Don''t Worry, Be Happy"?', 'Big Billy Bass', 'Singing Fish', 'Sardine', 'Big Mouth Billy Bass', 'D', 'general', 'pro'),
('What is the nickname of the US state of California?', 'Sunshine State', 'Bay State', 'Treasure State', 'Golden State', 'D', 'general', 'rookie'),
('Which country has the Union Jack in its flag?', 'Canada', 'Hong Kong', 'South Africa', 'New Zealand', 'D', 'general', 'rookie'),
('How many furlongs are there in a mile?', 'Four', 'Six', 'Two', 'Eight', 'D', 'general', 'rookie'),
('What type of animal was Harambe, who was shot after a child fell into its enclosure at the Cincinnati Zoo?', 'Panda', 'Crocodile', 'Tiger', 'Gorilla', 'D', 'general', 'rookie'),
('What is the last letter of the Greek alphabet?', 'Epsilon', 'Kappa', 'Mu', 'Omega', 'D', 'general', 'pro'),
('What is the first book of the Old Testament?', 'Leviticus', 'Numbers', 'Exodus', 'Genesis', 'D', 'general', 'rookie'),
('Where does water from Poland Spring water bottles come from?', 'Bavaria, Poland', 'Masovia, Poland', 'Hesse, Germany', 'Maine, United States', 'D', 'general', 'pro'),
('Which English rockstar has the real name of "William Michael Albert Broad"?', 'Joe Strummer', 'Sid Vicious', 'Steven Tyler', 'Billy Idol', 'D', 'general', 'pro'),
('When someone is inexperienced they are said to be what color?', 'Yellow', 'Red', 'Blue', 'Green', 'D', 'general', 'rookie'),
('What zodiac sign is represented by a pair of scales?', 'Aries', 'Capricorn', 'Sagittarius', 'Libra', 'D', 'general', 'rookie'),
('What is the largest organ of the human body?', 'large Intestine', 'Heart', 'Liver', 'Skin', 'D', 'general', 'rookie'),
('In DC comics where does the Green Arrow (Oliver Queen) live?', 'Gotham City', 'Metropolis', 'Central City', 'Star City', 'D', 'general', 'rookie'),
('The Quadrangularis Reversum is best described as which of the following?', 'A building in Oxford University', 'A geometric theorem', 'A chess move', 'A percussion instrument', 'D', 'general', 'legend'),
('What is considered to be the first sport ever to have been played?', 'Running', 'Javelin', 'Boxing', 'Wrestling', 'D', 'general', 'legend'),
('Which type of cutlery is most suited for eating soup?', 'Chopsticks', 'Fork', 'Knife', 'Spoon', 'D', 'general', 'rookie'),
('Antibiotics are generally taken to combat what?', 'Muscular pains', 'Migraines', 'Viruses', 'Bacterial infections', 'D', 'general', 'rookie'),
('The Fields Medal, one of the most sought after awards in mathematics, is awarded every how many years?', '3', '6', '5', '4', 'D', 'general', 'pro'),
('When one is "envious", they are said to be what color?', 'Red', 'Yellow', 'Blue', 'Green', 'D', 'general', 'rookie'),
('What is the world''s most expensive spice by weight?', 'Cinnamon', 'Vanilla', 'Cardamom', 'Saffron', 'D', 'general', 'rookie'),
('What fast food chain has the most locations globally?', 'Starbucks', 'KFC', 'McDonalds', 'Subway', 'D', 'general', 'pro'),
('Which sign of the zodiac is represented by the Crab?', 'Sagittarius', 'Libra', 'Virgo', 'Cancer', 'D', 'general', 'rookie'),
('What was the destination of the missing flight MH370?', 'Tokyo', 'Kuala Lumpur', 'Singapore', 'Beijing', 'D', 'general', 'pro'),
('Originally another word for poppy, coquelicot is a shade of what?', 'Green', 'Pink', 'Blue', 'Red', 'D', 'general', 'legend'),
('Which Italian automobile manufacturer gained majority control of U.S. automobile manufacturer Chrysler in 2011?', 'Alfa Romeo', 'Ferrari', 'Maserati', 'Fiat', 'D', 'general', 'pro'),
('Computer manufacturer Compaq was acquired for $25 billion dollars in 2002 by which company?', 'Asus', 'Dell', 'Toshiba', 'Hewlett-Packard', 'D', 'general', 'pro'),
('A statue of Charles Darwin sits in what London museum?', 'Science Museum', 'Tate', 'British Museum', 'Natural History Museum', 'D', 'general', 'pro'),
('Directly between the Washington Monument and the Reflecting Pool is a memorial to which war?', 'American Revolutionary War', 'American Civil War', 'Vietnam War', 'World War II', 'D', 'general', 'pro'),
('The term "scientist" was coined in which year?', '1796', '1942', '1933', '1833', 'D', 'general', 'pro'),
('Which country, not including Japan, has the most people of Japanese descent?', 'South Korea', 'China', 'United States of America', 'Brazil', 'D', 'general', 'rookie'),
('The phrase "accident waiting to happen" is an example of what type of figure of speech?', 'Metaphor', 'Analogy', 'Simile', 'Idiom', 'D', 'general', 'pro'),
('Which of the following is not another name for the eggplant?', 'Guinea Squash', 'Melongene', 'Brinjal', 'Potimarron', 'D', 'general', 'legend'),
('What does the Latin phrase "Veni, vidi, vici" translate into English?', 'See no evil, hear no evil, speak no evil', 'Past, present, and future', 'Life, liberty, and happiness', 'I came, I saw, I conquered', 'D', 'general', 'legend'),
('Which of these banks are NOT authorized to issue currency notes in Hong Kong?', 'Bank of China', 'HSBC', 'Standard Chartered', 'OCBC', 'D', 'general', 'legend'),
('Which candy is NOT made by Mars?', 'Twix', 'Snickers', 'M&M''s', 'Almond Joy', 'D', 'general', 'rookie'),
('What English word means to "think deeply"?', 'Condensate', 'Constipate', 'Confiscate', 'Contemplate', 'D', 'general', 'pro'),
('The new One World Trade Center in Manhattan, New York City was designed by which architect?', 'Fumihiko Maki', 'Michael Arad', 'Bjarke Ingels', 'David Childs', 'D', 'general', 'pro'),
('What is a dead mall?', 'A mall after business hours', 'A mall that has been condemed', 'A mall with no stores', 'A mall with high vacancy rates or low consumer foot traffic', 'D', 'general', 'pro'),
('The file hosting service, "Google Drive" was launched on what day?', 'November 14, 2008', 'January 12, 2014', 'January 20, 2010', 'April 24, 2012', 'D', 'general', 'rookie'),
('What is the romanized Russian word for "winter"?', 'Leto', 'Osen''', 'Vesna', 'Zima', 'D', 'general', 'pro'),
('Which famed architect, who died in 2019 aged 102, designed the glass pyramid at the Louvre museum in Paris?', 'Pascale Guédot', 'Frank Gehry', 'Wang Shu', 'I. M. Pei', 'D', 'general', 'pro'),
('Bob and Mike Bryan were well known brothers in which sport?', 'Baseball', 'Basketball', 'Football', 'Tennis', 'D', 'general', 'pro'),
('Which restaurant''s mascot is a clown?', 'Sonic', 'Whataburger', 'Burger King', 'McDonald''s', 'D', 'general', 'rookie'),
('When was WhatsApp founded?', '2010', '2007', '2012', '2009', 'D', 'general', 'pro'),
('Which iconic Disneyland attraction was closed in 2017 to be remodeled as a "Guardians of the Galaxy" themed ride?', 'Peter Pan''s Flight', 'The Haunted Mansion', 'Pirates of the Caribbean', 'Twilight Zone Tower of Terror', 'D', 'general', 'pro'),
('Of the following months, which has the most amount of days?', 'November', 'September', 'April', 'December', 'D', 'general', 'rookie'),
('The word "aprosexia" means which of the following?', 'The inability to stand up', 'The inability to make decisions', 'A feverish desire to rip one''s clothes off', 'The inability to concentrate on anything', 'D', 'general', 'legend'),
('Which country drives on the left side of the road?', 'China', 'Russia', 'Germany', 'Japan', 'D', 'general', 'pro'),
('Which of these companies does NOT manufacture automobiles?', 'GMC', 'Fiat', 'Nissan', 'Ducati', 'D', 'general', 'pro'),

-- BATCH 6 (50 questions)
('Which of the following chemicals are found in eggplant seeds?', 'Mescaline', 'Psilocybin', 'Cyanide', 'Nicotine', 'D', 'general', 'legend'),
('When was Nintendo founded?', 'March 4th, 1887', 'December 27th, 1894', 'October 19th, 1891', 'September 23rd, 1889', 'D', 'general', 'pro'),
('What name represents the letter "M" in the NATO phonetic alphabet?', 'Mark', 'Max', 'Matthew', 'Mike', 'D', 'general', 'pro'),
('Which of these is the name of a Japanese system of alternative medicine, literally meaning "finger pressure"?', 'Majime', 'Ikigai', 'Ukiyo', 'Shiatsu', 'D', 'general', 'pro'),
('What does the "G" mean in "G-Man"?', 'Geronimo', 'Ghost', 'Going', 'Government', 'D', 'general', 'pro'),
('Who invented the first ever chocolate bar, in 1847?', 'John Cadbury', 'Andrew Johnson', 'John Tyler', 'Joseph Fry', 'D', 'general', 'rookie'),
('In "Resident Evil 3", how many inventory slots does Jill have at the start of the game?', '12', '6', '10', '8', 'D', 'general', 'legend'),
('What is the airspeed velocity of an unladen swallow?', '200 MPH', '15 MPH', '20 MPH', '24 MPH', 'D', 'general', 'legend'),
('What is the weight of a Gold Bar in Fallout: New Vegas?', '32.50 Pounds', '40 Pounds', '30 Pounds', '35 Pounds', 'D', 'general', 'legend'),
('Before the 19th Century, the "Living Room" was originally called the...', 'Loft', 'Sitting Room', 'Open Room', 'Parlor', 'D', 'general', 'legend'),
('The "fairy" type made its debut in which generation of the Pokemon core series games?', '7th', '2nd', '4th', '6th', 'D', 'general', 'rookie'),
('What country has had prime ministers named Eden, Major, Peel, Law, Brown and Heath?', 'New Zealand', 'Canada', 'Australia', 'United Kingdom', 'D', 'general', 'rookie'),
('De Eemhof, Port Zelande and Het Heijderbos are holiday villas owned by what company?', 'Yelloh Village', 'Keycamp', 'Villa Plus', 'Center Parcs', 'D', 'general', 'legend'),
('Waluigi''s first appearance was in what game?', 'Super Smash Bros. Ultimate', 'Mario Party (N64)', 'Wario Land: Super Mario Land 3', 'Mario Tennis 64 (N64)', 'D', 'general', 'rookie'),
('Which of these American singers and songwriters won a Nobel Prize in Literature?', 'Johnny Cash', 'Alice Cooper', 'Buddy Holly', 'Bob Dylan', 'D', 'general', 'pro'),
('If someone said "you are olid", what would they mean?', 'You are out of shape/weak.', 'Your appearance is repulsive.', 'You are incomprehensible/an idiot.', 'You smell extremely unpleasant.', 'D', 'general', 'legend'),
('Foie gras is a French delicacy typically made from what part of a duck or goose?', 'Intestines', 'Stomach', 'Heart', 'Liver', 'D', 'general', 'rookie'),
('What is a "dakimakura"?', 'A yoga posture', 'A Chinese meal, essentially composed of fish', 'A word used to describe two people who truly love each other', 'A body pillow', 'D', 'general', 'pro'),
('What do sailors call the front of a boat?', 'Stern', 'Starboard', 'Port', 'Bow', 'D', 'general', 'rookie'),
('Which essential condiment is also known as Japanese horseradish?', 'Karashi', 'Ponzu', 'Mentsuyu', 'Wasabi', 'D', 'general', 'pro'),
('What airline was the owner of the plane that crashed off the coast of Nova Scotia in 1998?', 'Air France', 'TWA', 'British Airways', 'Swiss Air', 'D', 'general', 'rookie'),
('Scotch whisky and Drambuie make up which cocktail?', 'Screwdriver', 'Sex on the Beach', 'Manhattan', 'Rusty Nail', 'D', 'general', 'pro'),
('What is the name of the main Character from the Series: Dead Space?', 'Commander Shepard', 'Ellen Ripley', 'Captain Kirk', 'Isaac Clarke', 'D', 'general', 'rookie'),
('What is the name of the very first video uploaded to YouTube?', 'carrie rides a truck', 'Her new puppy from great grandpa vern.', 'tribute', 'Me at the zoo', 'D', 'general', 'pro'),
('What was the name of the Ethiopian wolf before it was called the Ethiopian wolf?', 'Canis Wolf', 'Amharic Fox', 'African Wolf', 'Simien Jackel', 'D', 'general', 'legend'),
('In the Harry Potter universe, who does Draco Malfoy end up marrying?', 'Hermione Granger', 'Millicent Bulstrode', 'Pansy Parkinson', 'Astoria Greengrass', 'D', 'general', 'pro'),
('What is the name of the Jewish New Year?', 'Hanukkah', 'Raksha Bandhan', 'Passover', 'Rosh Hashanah', 'D', 'general', 'rookie'),
('How much does a Granchieste Bar in Lindt''s "Hello" chocolate weigh?', '320g', '150g', '250g', '100g', 'D', 'general', 'legend'),
('What is the currency of Poland?', 'Ruble', 'Krone', 'Euro', 'Złoty', 'D', 'general', 'pro'),
('Who is considered the "Father of Modern Philosophy"?', 'Plato', 'Albert Einstein', 'Antoine Lavoiser', 'René Descartes', 'D', 'general', 'rookie'),
('When was the Declaration of Independence approved by the Second Continental Congress?', 'May 4, 1776', 'June 4, 1776', 'July 2, 1776', 'July 4, 1776', 'D', 'general', 'pro'),
('Which of the following nations was NOT a belligerent in World War I?', 'Portugal', 'Romania', 'Greece', 'Denmark', 'D', 'general', 'rookie'),
('What was the name of the WWF professional wrestling tag team made up of the wrestlers Ax and Smash?', 'The Dream Team', 'The Bushwhackers', 'The British Bulldogs', 'Demolition', 'D', 'general', 'rookie'),
('In the video-game franchise Kingdom Hearts, the main protagonist, carries a weapon with what shape?', 'Pen', 'Sword', 'Cellphone', 'Key', 'D', 'general', 'rookie'),
('Death Valley''s Badwater Basin is North America''s point of lowest elevation at how many feet below sea level?', '79 feet', '12,092 feet', '1,640 feet', '282 feet', 'D', 'general', 'pro'),
('What is Tasmania?', 'A Psychological Disorder', 'A flavor of Ben and Jerry''s ice-cream', 'The Name of a Warner Brothers Cartoon Character', 'An Australian State', 'D', 'general', 'rookie'),
('What geometric shape is generally used for stop signs?', 'Hexagon', 'Circle', 'Triangle', 'Octagon', 'D', 'general', 'rookie'),
('How many syllables make up a haiku?', '21', '15', '10', '17', 'D', 'general', 'rookie'),
('What was Bank of America originally established as?', 'Bank of Long Island', 'Bank of Charlotte', 'Bank of Pennsylvania', 'Bank of Italy', 'D', 'general', 'legend'),
('What does the ''S'' stand for in the abbreviation SIM, as in SIM card?', 'Secure', 'Solid', 'Single', 'Subscriber', 'D', 'general', 'rookie'),
('What character was once considered to be the 27th letter of the alphabet?', 'Pilcrow', 'Interrobang', 'Tilde', 'Ampersand', 'D', 'general', 'pro'),
('Which slogan did the fast food company, McDonald''s, use before their "I''m Lovin'' It" slogan?', 'Have It Your Way', 'Making People Happy Through Food', 'Why Pay More!?', 'We Love to See You Smile', 'D', 'general', 'pro'),
('What was the third country to have a McDonald''s restaurant?', 'France', 'Japan', 'Australia', 'Costa Rica', 'D', 'general', 'legend'),
('Named after the mallow flower, mauve is a shade of what?', 'Red', 'Pink', 'Brown', 'Purple', 'D', 'general', 'legend'),
('Which language is NOT Indo-European?', 'Latvian', 'Russian', 'Greek', 'Hungarian', 'D', 'general', 'pro'),
('What do sailors call the back of a boat?', 'Bow', 'Starboard', 'Port', 'Stern', 'D', 'general', 'rookie'),
('Which of the following landmarks is not located in New York City?', 'Central Park', 'Times Square', 'Empire State Building', 'Lincoln Memorial', 'D', 'general', 'rookie'),
('Who is a co-founder of music streaming service Spotify?', 'Michael Breidenbruecker', 'Sean Parker', 'Felix Miller', 'Daniel Ek', 'D', 'general', 'pro'),
('What was the first ever London Underground line to be built?', 'Victoria Line', 'Circle Line', 'Bakerloo Line', 'Metropolitan Line', 'D', 'general', 'rookie'),
('Where did the pineapple plant originate?', 'Hawaii', 'Asia', 'Europe', 'South America', 'D', 'general', 'pro'),

-- BATCH 7 (50 questions)
('In which country was the 1992 Summer Olympics Games held?', 'Korea', 'USA', 'Russia', 'Spain', 'D', 'general', 'pro'),
('Which of the following buildings is example of a structure primarily built in the Art Deco architectural style?', 'Taipei 101', 'One Detroit Center', 'Westendstrasse 1', 'Niagara Mohawk Building', 'D', 'general', 'pro'),
('In "Shrek", what comedic actor voices Donkey?', 'Chris Rock', 'Richard Pryor', 'Bernie Mac', 'Eddie Murphy', 'D', 'general', 'rookie'),
('Which musician has collaborated with American producer Porter Robinson and released the 2016 song "Shelter"?', 'deadmau5', 'Mat Zo', 'Zedd', 'Madeon', 'D', 'general', 'legend'),
('Electronic music producer Kygo''s popularity skyrocketed after a certain remix. Which song did he remix?', 'Marvin Gaye - Sexual Healing', 'Coldplay - Midnight', 'a-ha - Take On Me', 'Ed Sheeran - I See Fire', 'D', 'general', 'legend'),
('When did the website "Facebook" launch?', '2005', '2006', '2003', '2004', 'D', 'general', 'pro'),
('The buried remains of which English explorer of Australia were found in London in January 2019?', 'Abel Tasman', 'William Bourke', 'Dirk Hartog', 'Matthew Flinders', 'D', 'general', 'rookie'),
('Earth is located in which galaxy?', 'The Galaxy Note', 'The Mars Galaxy', 'The Black Hole', 'The Milky Way Galaxy', 'D', 'general', 'rookie'),
('After how many years would you celebrate your crystal anniversary?', '10', '25', '20', '15', 'D', 'general', 'pro'),
('What is the name of Poland in Polish?', 'Polszka', 'Pupcia', 'Póland', 'Polska', 'D', 'general', 'rookie'),
('What was the soft drink Pepsi originally introduced as?', 'Pepsin Pop', 'Carolina Cola', 'Pepsin Syrup', 'Brad''s Drink', 'D', 'general', 'pro'),
('Macintosh has named six of its operating systems after big cats. What big cat did Macintosh name their 2007 release after?', 'Tiger', 'Panther', 'Puma', 'Leopard', 'D', 'general', 'pro'),
('Who invented Pastafarianism?', 'Bill Nye', 'Eric Tignor', 'Zach Soldi', 'Bobby Henderson', 'D', 'general', 'pro'),
('What year was Queen Elizabeth II born?', '1923', '1930', '1929', '1926', 'D', 'general', 'legend'),
('What is the Italian word for "tomato"?', 'Peperoncino', 'Aglio', 'Cipolla', 'Pomodoro', 'D', 'general', 'pro'),
('What is the German word for "spoon"?', 'Messer', 'Essstäbchen', 'Gabel', 'Löffel', 'D', 'general', 'pro'),
('What is the French word for "fish"?', 'mer', 'escargot', 'fiche', 'poisson', 'D', 'general', 'rookie'),
('If you planted the seeds of Quercus robur, what would grow?', 'Flowers', 'Grains', 'Vegetables', 'Trees', 'D', 'general', 'legend'),
('How many calories are in a 355 ml can of Pepsi Cola?', '100', '200', '155', '150', 'D', 'general', 'legend'),
('What do sailors call the back of a boat?', 'Port', 'Starboard', 'Bow', 'Stern', 'D', 'general', 'rookie'),
('In the MMO RPG "Realm of the Mad God", what dungeon is widely considered to be the most difficult?', 'The Tomb of the Acient''s', 'Snake Pit', 'The Puppet Master''s Theater', 'The Shatter''s', 'D', 'general', 'legend'),
('The Swedish word "Grunka" means what in English?', 'People', 'Place', 'Pineapple', 'Thing', 'D', 'general', 'legend'),
('On a dartboard, what number is directly opposite No. 1?', '15', '20', '12', '19', 'D', 'general', 'rookie'),
('What is the Spanish word for "donkey"?', 'Perro', 'Toro', 'Caballo', 'Burro', 'D', 'general', 'rookie'),
('Which company did Valve cooperate with in the creation of the Vive?', 'Razer', 'Google', 'Oculus', 'HTC', 'D', 'general', 'rookie'),
('Which church''s interior in Vatican City was designed in 1503 by renaissance architects including Bramante, Michelangelo and Bernini?', 'The Duomo of Florence', 'St. Mark''s Basilica', 'Catania Cathedral', 'St. Peter''s Basilica', 'D', 'general', 'legend'),
('How much does a Granchieste Bar in Lindt''s "Hello" chocolate weigh?', '250g', '150g', '320g', '100g', 'D', 'general', 'legend'),
('What does the "G" mean in "G-Man"?', 'Going', 'Ghost', 'Geronimo', 'Government', 'D', 'general', 'pro'),
('What name represents the letter "M" in the NATO phonetic alphabet?', 'Matthew', 'Mark', 'Max', 'Mike', 'D', 'general', 'pro'),
('What is the name of the Jewish New Year?', 'Raksha Bandhan', 'Hanukkah', 'Passover', 'Rosh Hashanah', 'D', 'general', 'rookie'),
('In the Harry Potter universe, who does Draco Malfoy end up marrying?', 'Pansy Parkinson', 'Millicent Bulstrode', 'Hermione Granger', 'Astoria Greengrass', 'D', 'general', 'pro'),
('What was the name of the Ethiopian wolf before it was called the Ethiopian wolf?', 'African Wolf', 'Amharic Fox', 'Canis Wolf', 'Simien Jackel', 'D', 'general', 'legend'),
('In which fast food chain can you order a Jamocha Shake?', 'Wendy''s', 'Burger King', 'McDonald''s', 'Arby''s', 'D', 'general', 'rookie'),
('What is the unit of currency in Laos?', 'Dollar', 'Ruble', 'Konra', 'Kip', 'D', 'general', 'pro'),
('What is considered to be the first sport ever to have been played?', 'Javelin', 'Running', 'Boxing', 'Wrestling', 'D', 'general', 'legend'),
('What is "dabbing"?', 'A sport', 'A language', 'A medical procedure', 'A dance', 'D', 'general', 'rookie'),
('Which river flows through the Scottish city of Glasgow?', 'Tay', 'Dee', 'Tweed', 'Clyde', 'D', 'general', 'pro'),
('What did the Spanish autonomous community of Catalonia ban in 2010, that took effect in 2012?', 'Fiestas', 'Flamenco', 'Mariachi', 'Bullfighting', 'D', 'general', 'pro'),
('Who is considered the "Father of Modern Philosophy"?', 'Albert Einstein', 'Plato', 'Antoine Lavoiser', 'René Descartes', 'D', 'general', 'rookie'),
('What is the last letter of the Greek alphabet?', 'Mu', 'Epsilon', 'Kappa', 'Omega', 'D', 'general', 'pro'),
('What is the currency of Poland?', 'Krone', 'Euro', 'Ruble', 'Złoty', 'D', 'general', 'pro'),
('What was the name of the WWF professional wrestling tag team made up of the wrestlers Ax and Smash?', 'The British Bulldogs', 'The Bushwhackers', 'The Dream Team', 'Demolition', 'D', 'general', 'rookie'),
('Which of the following nations was NOT a belligerent in World War I?', 'Greece', 'Romania', 'Portugal', 'Denmark', 'D', 'general', 'rookie'),
('When was the Declaration of Independence approved by the Second Continental Congress?', 'July 2, 1776', 'June 4, 1776', 'May 4, 1776', 'July 4, 1776', 'D', 'general', 'pro'),
('What alcoholic drink is mainly made from juniper berries?', 'Vodka', 'Rum', 'Tequila', 'Gin', 'D', 'general', 'pro'),
('What is the nickname of the US state of California?', 'Sunshine State', 'Bay State', 'Treasure State', 'Golden State', 'D', 'general', 'rookie'),
('What step in cellular respiration forms ATP?', 'Glycolysis', 'Calvin Cycle', 'Pyruvate Oxidation', 'Oxidative Phosphorylation', 'D', 'general', 'rookie'),
('On a dartboard, what number is directly opposite No. 1?', '20', '15', '12', '19', 'D', 'general', 'rookie'),
('What is Tasmania?', 'A flavor of Ben and Jerry''s ice-cream', 'A Psychological Disorder', 'The Name of a Warner Brothers Cartoon Character', 'An Australian State', 'D', 'general', 'rookie'),
('Death Valley''s Badwater Basin is North America''s point of lowest elevation at how many feet below sea level?', '12,092 feet', '1,640 feet', '79 feet', '282 feet', 'D', 'general', 'pro');
