-- =====================================================
-- BATCHES 2-4: General Knowledge Questions (150 questions)
-- From Open Trivia Database - Batches 2, 3, 4
-- =====================================================

INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, category, difficulty) VALUES
-- BATCH 2 (50 questions)
('What does a funambulist walk on?', 'Balls', 'A Tight Rope', 'Broken Glass', 'The Moon', 'B', 'general', 'rookie'),
('Which sign of the zodiac is represented by the Crab?', 'Libra', 'Cancer', 'Virgo', 'Sagittarius', 'B', 'general', 'rookie'),
('What is the name of the very first video uploaded to YouTube?', 'tribute', 'Her new puppy from great grandpa vern.', 'Me at the zoo', 'carrie rides a truck', 'C', 'general', 'pro'),
('What year was Apple Inc. founded?', '1980', '1978', '1976', '1974', 'C', 'general', 'pro'),
('Which of these companies does NOT manufacture automobiles?', 'Fiat', 'Ducati', 'GMC', 'Nissan', 'B', 'general', 'pro'),
('The new One World Trade Center in Manhattan, New York City was designed by which architect?', 'Bjarke Ingels', 'Fumihiko Maki', 'Michael Arad', 'David Childs', 'D', 'general', 'pro'),
('What are Panama hats made out of?', 'Flax', 'Hemp', 'Straw', 'Silk', 'C', 'general', 'rookie'),
('What type of animal was Harambe, who was shot after a child fell into its enclosure at the Cincinnati Zoo?', 'Tiger', 'Crocodile', 'Gorilla', 'Panda', 'C', 'general', 'rookie'),
('What is a "dakimakura"?', 'A body pillow', 'A yoga posture', 'A word used to describe two people who truly love each other', 'A Chinese meal, essentially composed of fish', 'A', 'general', 'pro'),
('Who is depicted on the US hundred dollar bill?', 'Thomas Jefferson', 'Abraham Lincoln', 'Benjamin Franklin', 'George Washington', 'C', 'general', 'rookie'),
('What do sailors call the front of a boat?', 'Port', 'Bow', 'Stern', 'Starboard', 'B', 'general', 'rookie'),
('Which essential condiment is also known as Japanese horseradish?', 'Karashi', 'Wasabi', 'Ponzu', 'Mentsuyu', 'B', 'general', 'pro'),
('What airline was the owner of the plane that crashed off the coast of Nova Scotia in 1998?', 'Air France', 'TWA', 'British Airways', 'Swiss Air', 'D', 'general', 'rookie'),
('If you planted the seeds of Quercus robur, what would grow?', 'Vegetables', 'Trees', 'Grains', 'Flowers', 'B', 'general', 'legend'),
('The Hyundai Motor Company was founded in which country?', 'China', 'Russia', 'South Korea', 'Japan', 'C', 'general', 'rookie'),
('Scotch whisky and Drambuie make up which cocktail?', 'Screwdriver', 'Manhattan', 'Rusty Nail', 'Sex on the Beach', 'C', 'general', 'pro'),
('Where does water from Poland Spring water bottles come from?', 'Bavaria, Poland', 'Masovia, Poland', 'Hesse, Germany', 'Maine, United States', 'D', 'general', 'pro'),
('What is the name of the main Character from the Series: Dead Space?', 'Commander Shepard', 'Captain Kirk', 'Ellen Ripley', 'Isaac Clarke', 'D', 'general', 'rookie'),
('When someone is inexperienced they are said to be what color?', 'Blue', 'Red', 'Green', 'Yellow', 'C', 'general', 'rookie'),
('How many notes are there on a standard grand piano?', '98', '108', '88', '78', 'C', 'general', 'legend'),
('Which of these American singers and songwriters won a Nobel Prize in Literature?', 'Alice Cooper', 'Buddy Holly', 'Bob Dylan', 'Johnny Cash', 'C', 'general', 'pro'),
('Apple co-founder Steve Jobs died from complications of which form of cancer?', 'Stomach', 'Liver', 'Bone', 'Pancreatic', 'D', 'general', 'pro'),
('Waluigi''s first appearance was in what game?', 'Wario Land: Super Mario Land 3', 'Mario Party (N64)', 'Super Smash Bros. Ultimate', 'Mario Tennis 64 (N64)', 'D', 'general', 'rookie'),
('What is a dead mall?', 'A mall with no stores', 'A mall after business hours', 'A mall that has been condemed', 'A mall with high vacancy rates or low consumer foot traffic', 'D', 'general', 'pro'),
('Which river flows through the Scottish city of Glasgow?', 'Tweed', 'Dee', 'Tay', 'Clyde', 'D', 'general', 'pro'),
('Which musician has collaborated with American producer Porter Robinson and released the 2016 song "Shelter"?', 'Zedd', 'Mat Zo', 'Madeon', 'deadmau5', 'C', 'general', 'legend'),
('What is "dabbing"?', 'A sport', 'A language', 'A medical procedure', 'A dance', 'D', 'general', 'rookie'),
('What fast food chain has the most locations globally?', 'KFC', 'Starbucks', 'Subway', 'McDonalds', 'C', 'general', 'pro'),
('Which country drives on the left side of the road?', 'China', 'Germany', 'Russia', 'Japan', 'D', 'general', 'pro'),
('Which canal connects the Mediterranean Sea with the Red Sea?', 'Qaraqum Canal', 'Panama Canal', 'Suez Canal', 'Sinai Canal', 'C', 'general', 'rookie'),
('What zodiac sign is represented by a pair of scales?', 'Capricorn', 'Sagittarius', 'Libra', 'Aries', 'C', 'general', 'rookie'),
('Who invented the first ever chocolate bar, in 1847?', 'John Tyler', 'John Cadbury', 'Andrew Johnson', 'Joseph Fry', 'D', 'general', 'rookie'),
('What is the airspeed velocity of an unladen swallow?', '20 MPH', '200 MPH', '15 MPH', '24 MPH', 'D', 'general', 'legend'),
('In the MMO RPG "Realm of the Mad God", what dungeon is widely considered to be the most difficult?', 'Snake Pit', 'The Puppet Master''s Theater', 'The Tomb of the Acient''s', 'The Shatter''s', 'D', 'general', 'legend'),
('What is the profession of Elon Musk''s mom, Maye Musk?', 'Biologist', 'Professor', 'Model', 'Musician', 'C', 'general', 'rookie'),
('Which of these is the name of a Japanese system of alternative medicine, literally meaning "finger pressure"?', 'Ukiyo', 'Majime', 'Ikigai', 'Shiatsu', 'D', 'general', 'pro'),
('Which of these fast-food chains is NOT mainly known to sell pizza?', 'Papa John''s', 'Little Caesars', 'Wendy''s', 'Domino''s', 'C', 'general', 'rookie'),
('Which of the following chemicals are found in eggplant seeds?', 'Mescaline', 'Cyanide', 'Nicotine', 'Psilocybin', 'C', 'general', 'legend'),
('When was Nintendo founded?', 'March 4th, 1887', 'October 19th, 1891', 'December 27th, 1894', 'September 23rd, 1889', 'D', 'general', 'pro'),
('Originally another word for poppy, coquelicot is a shade of what?', 'Blue', 'Pink', 'Red', 'Green', 'C', 'general', 'legend'),
('The Fields Medal, one of the most sought after awards in mathematics, is awarded every how many years?', '5', '6', '3', '4', 'D', 'general', 'pro'),
('The American company "Campbell''s" is most well known for making what food product?', 'Sausages', 'Soft drinks', 'Chocolate', 'Canned soups', 'D', 'general', 'rookie'),
('The word "aprosexia" means which of the following?', 'The inability to stand up', 'A feverish desire to rip one''s clothes off', 'The inability to make decisions', 'The inability to concentrate on anything', 'D', 'general', 'legend'),
('Which restaurant''s mascot is a clown?', 'Burger King', 'Whataburger', 'McDonald''s', 'Sonic', 'C', 'general', 'rookie'),
('When was WhatsApp founded?', '2012', '2007', '2010', '2009', 'D', 'general', 'pro'),
('Which iconic Disneyland attraction was closed in 2017 to be remodeled as a "Guardians of the Galaxy" themed ride?', 'Pirates of the Caribbean', 'The Haunted Mansion', 'Peter Pan''s Flight', 'Twilight Zone Tower of Terror', 'D', 'general', 'pro'),
('Of the following months, which has the most amount of days?', 'September', 'November', 'April', 'December', 'D', 'general', 'rookie'),
('What type of dog is ''Handsome Dan'', the mascot of Yale University?', 'Yorkshire Terrier', 'Bulldog', 'Pug', 'Boxer', 'B', 'general', 'legend'),
('How many calories are in a 355 ml can of Pepsi Cola?', '100', '155', '200', '150', 'D', 'general', 'legend'),
('Bob and Mike Bryan were well known brothers in which sport?', 'Football', 'Baseball', 'Basketball', 'Tennis', 'D', 'general', 'pro'),

-- BATCH 3 (50 questions)
('What is the German word for "spoon"?', 'Gabel', 'Essstäbchen', 'Löffel', 'Messer', 'C', 'general', 'pro'),
('What is the Italian word for "tomato"?', 'Cipolla', 'Aglio', 'Peperoncino', 'Pomodoro', 'D', 'general', 'pro'),
('What year was Queen Elizabeth II born?', '1929', '1930', '1926', '1923', 'C', 'general', 'legend'),
('The Swedish word "Grunka" means what in English?', 'People', 'Pineapple', 'Place', 'Thing', 'D', 'general', 'legend'),
('Which of these is the name of a Japanese system of alternative medicine, literally meaning "finger pressure"?', 'Majime', 'Ikigai', 'Ukiyo', 'Shiatsu', 'D', 'general', 'pro'),
('Who invented Pastafarianism?', 'Zach Soldi', 'Eric Tignor', 'Bill Nye', 'Bobby Henderson', 'D', 'general', 'pro'),
('Macintosh has named six of its operating systems after big cats. What big cat did Macintosh name their 2007 release after?', 'Puma', 'Panther', 'Tiger', 'Leopard', 'D', 'general', 'pro'),
('What was the soft drink Pepsi originally introduced as?', 'Pepsin Syrup', 'Pepsin Pop', 'Carolina Cola', 'Brad''s Drink', 'D', 'general', 'pro'),
('What is the name of Poland in Polish?', 'Póland', 'Pupcia', 'Polska', 'Polszka', 'C', 'general', 'rookie'),
('After how many years would you celebrate your crystal anniversary?', '20', '25', '10', '15', 'D', 'general', 'pro'),
('What alcoholic drink is mainly made from juniper berries?', 'Tequila', 'Rum', 'Vodka', 'Gin', 'D', 'general', 'pro'),
('If you planted the seeds of Quercus robur, what would grow?', 'Flowers', 'Grains', 'Vegetables', 'Trees', 'D', 'general', 'legend'),
('Earth is located in which galaxy?', 'The Black Hole', 'The Mars Galaxy', 'The Galaxy Note', 'The Milky Way Galaxy', 'D', 'general', 'rookie'),
('The buried remains of which English explorer of Australia were found in London in January 2019?', 'Dirk Hartog', 'William Bourke', 'Abel Tasman', 'Matthew Flinders', 'D', 'general', 'rookie'),
('When did the website "Facebook" launch?', '2003', '2006', '2005', '2004', 'D', 'general', 'pro'),
('Electronic music producer Kygo''s popularity skyrocketed after a certain remix. Which song did he remix?', 'a-ha - Take On Me', 'Coldplay - Midnight', 'Marvin Gaye - Sexual Healing', 'Ed Sheeran - I See Fire', 'D', 'general', 'legend'),
('Which of the following landmarks is not located in New York City?', 'Empire State Building', 'Times Square', 'Central Park', 'Lincoln Memorial', 'D', 'general', 'rookie'),
('Which canal connects the Mediterranean Sea with the Red Sea?', 'Panama Canal', 'Qaraqum Canal', 'Sinai Canal', 'Suez Canal', 'D', 'general', 'rookie'),
('Who is a co-founder of music streaming service Spotify?', 'Felix Miller', 'Sean Parker', 'Michael Breidenbruecker', 'Daniel Ek', 'D', 'general', 'pro'),
('In the MMO RPG "Realm of the Mad God", what dungeon is widely considered to be the most difficult?', 'The Puppet Master''s Theater', 'Snake Pit', 'The Tomb of the Acient''s', 'The Shatter''s', 'D', 'general', 'legend'),
('How many calories are in a 355 ml can of Pepsi Cola?', '155', '200', '100', '150', 'D', 'general', 'legend'),
('What was the first ever London Underground line to be built?', 'Bakerloo Line', 'Circle Line', 'Victoria Line', 'Metropolitan Line', 'D', 'general', 'rookie'),
('When someone is cowardly, they are said to have what color belly?', 'Blue', 'Red', 'Green', 'Yellow', 'D', 'general', 'rookie'),
('Where did the pineapple plant originate?', 'Europe', 'Asia', 'Hawaii', 'South America', 'D', 'general', 'pro'),
('In which country was the 1992 Summer Olympics Games held?', 'Russia', 'USA', 'Korea', 'Spain', 'D', 'general', 'pro'),
('Which of these colours is NOT featured in the logo for Google?', 'Blue', 'Green', 'Yellow', 'Pink', 'D', 'general', 'rookie'),
('What does the Latin phrase "Veni, vidi, vici" translate into English?', 'Life, liberty, and happiness', 'Past, present, and future', 'See no evil, hear no evil, speak no evil', 'I came, I saw, I conquered', 'D', 'general', 'legend'),
('What does a funambulist walk on?', 'Broken Glass', 'The Moon', 'Balls', 'A Tight Rope', 'D', 'general', 'rookie'),
('When one is "envious", they are said to be what color?', 'Yellow', 'Red', 'Blue', 'Green', 'D', 'general', 'rookie'),
('What is the name of NASA''s most famous space telescope?', 'Millenium Falcon', 'Big Eye', 'Death Star', 'Hubble Space Telescope', 'D', 'general', 'rookie'),
('What is the French word for "fish"?', 'escargot', 'fiche', 'mer', 'poisson', 'D', 'general', 'rookie'),
('Which of the following buildings is example of a structure primarily built in the Art Deco architectural style?', 'Westendstrasse 1', 'One Detroit Center', 'Taipei 101', 'Niagara Mohawk Building', 'D', 'general', 'pro'),
('What is the first book of the Old Testament?', 'Numbers', 'Exodus', 'Leviticus', 'Genesis', 'D', 'general', 'rookie'),
('The Quadrangularis Reversum is best described as which of the following?', 'A geometric theorem', 'A chess move', 'A building in Oxford University', 'A percussion instrument', 'D', 'general', 'legend'),
('Which candy is NOT made by Mars?', 'M&M''s', 'Snickers', 'Twix', 'Almond Joy', 'D', 'general', 'rookie'),
('Before the 19th Century, the "Living Room" was originally called the...', 'Open Room', 'Loft', 'Sitting Room', 'Parlor', 'D', 'general', 'legend'),
('What is the weight of a Gold Bar in Fallout: New Vegas?', '30 Pounds', '32.50 Pounds', '40 Pounds', '35 Pounds', 'D', 'general', 'legend'),
('The "fairy" type made its debut in which generation of the Pokemon core series games?', '4th', '7th', '2nd', '6th', 'D', 'general', 'rookie'),
('What country has had prime ministers named Eden, Major, Peel, Law, Brown and Heath?', 'Australia', 'Canada', 'New Zealand', 'United Kingdom', 'D', 'general', 'rookie'),
('De Eemhof, Port Zelande and Het Heijderbos are holiday villas owned by what company?', 'Yelloh Village', 'Villa Plus', 'Keycamp', 'Center Parcs', 'D', 'general', 'legend'),
('Which of these cities does NOT have a United States Minting location?', 'Philidelphia, PA', 'San Fransisco, CA', 'West Point, NY', 'St. Louis, MO', 'D', 'general', 'legend'),
('What year was Apple Inc. founded?', '1974', '1978', '1980', '1976', 'D', 'general', 'pro'),
('What is the romanized Russian word for "winter"?', 'Vesna', 'Osen''', 'Leto', 'Zima', 'D', 'general', 'pro'),
('Which of the following is not the host of a program on NPR?', 'Peter Sagal', 'Ira Glass', 'Terry Gross', 'Ben Shapiro', 'D', 'general', 'rookie'),
('In "Shrek", what comedic actor voices Donkey?', 'Bernie Mac', 'Richard Pryor', 'Chris Rock', 'Eddie Murphy', 'D', 'general', 'rookie'),
('What is the profession of Elon Musk''s mom, Maye Musk?', 'Musician', 'Biologist', 'Professor', 'Model', 'D', 'general', 'rookie'),
('What zodiac sign is represented by a pair of scales?', 'Sagittarius', 'Capricorn', 'Aries', 'Libra', 'D', 'general', 'rookie'),
('Foie gras is a French delicacy typically made from what part of a duck or goose?', 'Heart', 'Intestines', 'Stomach', 'Liver', 'D', 'general', 'rookie'),
('If someone said "you are olid", what would they mean?', 'You are incomprehensible/an idiot.', 'Your appearance is repulsive.', 'You are out of shape/weak.', 'You smell extremely unpleasant.', 'D', 'general', 'legend'),
('What do sailors call the back of a boat?', 'Port', 'Starboard', 'Bow', 'Stern', 'D', 'general', 'rookie'),

-- BATCH 4 (50 questions)
('Which language is NOT Indo-European?', 'Greek', 'Latvian', 'Russian', 'Hungarian', 'D', 'general', 'pro'),
('Who is depicted on the US hundred dollar bill?', 'Abraham Lincoln', 'Thomas Jefferson', 'George Washington', 'Benjamin Franklin', 'D', 'general', 'rookie'),
('Named after the mallow flower, mauve is a shade of what?', 'Brown', 'Pink', 'Red', 'Purple', 'D', 'general', 'legend'),
('What was the third country to have a McDonald''s restaurant?', 'Australia', 'France', 'Japan', 'Costa Rica', 'D', 'general', 'legend'),
('Which slogan did the fast food company, McDonald''s, use before their "I''m Lovin'' It" slogan?', 'Why Pay More!?', 'Making People Happy Through Food', 'Have It Your Way', 'We Love to See You Smile', 'D', 'general', 'pro'),
('What type of dog is ''Handsome Dan'', the mascot of Yale University?', 'Boxer', 'Pug', 'Yorkshire Terrier', 'Bulldog', 'D', 'general', 'legend'),
('Which of these cities does NOT have a United States Minting location?', 'Philidelphia, PA', 'West Point, NY', 'San Fransisco, CA', 'St. Louis, MO', 'D', 'general', 'legend'),
('What character was once considered to be the 27th letter of the alphabet?', 'Tilde', 'Interrobang', 'Pilcrow', 'Ampersand', 'D', 'general', 'pro'),
('What is the name of NASA''s most famous space telescope?', 'Death Star', 'Millenium Falcon', 'Big Eye', 'Hubble Space Telescope', 'D', 'general', 'rookie'),
('The American company "Campbell''s" is most well known for making what food product?', 'Soft drinks', 'Chocolate', 'Sausages', 'Canned soups', 'D', 'general', 'rookie'),
('What does the ''S'' stand for in the abbreviation SIM, as in SIM card?', 'Single', 'Solid', 'Secure', 'Subscriber', 'D', 'general', 'rookie'),
('What is the shape of the toy invented by Hungarian professor Ernő Rubik?', 'Pyramid', 'Cylinder', 'Sphere', 'Cube', 'D', 'general', 'rookie'),
('What was Bank of America originally established as?', 'Bank of Pennsylvania', 'Bank of Charlotte', 'Bank of Long Island', 'Bank of Italy', 'D', 'general', 'legend'),
('Which of the following is not another name for the eggplant?', 'Melongene', 'Guinea Squash', 'Brinjal', 'Potimarron', 'D', 'general', 'legend'),
('How many syllables make up a haiku?', '10', '21', '15', '17', 'D', 'general', 'rookie'),
('What is the Swedish word for "window"?', 'Skärm', 'Ruta', 'Hål', 'Fönster', 'D', 'general', 'pro'),
('What geometric shape is generally used for stop signs?', 'Triangle', 'Circle', 'Hexagon', 'Octagon', 'D', 'general', 'rookie'),
('In the video-game franchise Kingdom Hearts, the main protagonist, carries a weapon with what shape?', 'Cellphone', 'Pen', 'Sword', 'Key', 'D', 'general', 'rookie'),
('The Swedish word "Grunka" means what in English?', 'Pineapple', 'Place', 'People', 'Thing', 'D', 'general', 'legend'),
('Death Valley''s Badwater Basin is North America''s point of lowest elevation at how many feet below sea level?', '1,640 feet', '12,092 feet', '79 feet', '282 feet', 'D', 'general', 'pro'),
('What is Tasmania?', 'The Name of a Warner Brothers Cartoon Character', 'A Psychological Disorder', 'A flavor of Ben and Jerry''s ice-cream', 'An Australian State', 'D', 'general', 'rookie'),
('On a dartboard, what number is directly opposite No. 1?', '12', '15', '20', '19', 'D', 'general', 'rookie'),
('What step in cellular respiration forms ATP?', 'Pyruvate Oxidation', 'Calvin Cycle', 'Glycolysis', 'Oxidative Phosphorylation', 'D', 'general', 'rookie'),
('What is the nickname of the US state of California?', 'Treasure State', 'Bay State', 'Sunshine State', 'Golden State', 'D', 'general', 'rookie'),
('What alcoholic drink is mainly made from juniper berries?', 'Tequila', 'Rum', 'Vodka', 'Gin', 'D', 'general', 'pro'),
('When was the Declaration of Independence approved by the Second Continental Congress?', 'July 2, 1776', 'June 4, 1776', 'May 4, 1776', 'July 4, 1776', 'D', 'general', 'pro'),
('Which of the following nations was NOT a belligerent in World War I?', 'Greece', 'Romania', 'Portugal', 'Denmark', 'D', 'general', 'rookie'),
('What was the name of the WWF professional wrestling tag team made up of the wrestlers Ax and Smash?', 'The British Bulldogs', 'The Bushwhackers', 'The Dream Team', 'Demolition', 'D', 'general', 'rookie'),
('What is the currency of Poland?', 'Euro', 'Krone', 'Ruble', 'Złoty', 'D', 'general', 'pro'),
('What is the last letter of the Greek alphabet?', 'Kappa', 'Epsilon', 'Mu', 'Omega', 'D', 'general', 'pro'),
('Who is considered the "Father of Modern Philosophy"?', 'Antoine Lavoiser', 'Albert Einstein', 'Plato', 'René Descartes', 'D', 'general', 'rookie'),
('What did the Spanish autonomous community of Catalonia ban in 2010, that took effect in 2012?', 'Mariachi', 'Flamenco', 'Fiestas', 'Bullfighting', 'D', 'general', 'pro'),
('Which river flows through the Scottish city of Glasgow?', 'Tweed', 'Dee', 'Tay', 'Clyde', 'D', 'general', 'pro'),
('According to Sherlock Holmes, "If you eliminate the impossible, whatever remains, however improbable, must be the..."', 'Source', 'Cause', 'Answer', 'Truth', 'D', 'general', 'rookie'),
('How many cards are there in a standard deck of playing cards?', '64', '40', '32', '52', 'D', 'general', 'rookie'),
('Which iconic Disneyland attraction was closed in 2017 to be remodeled as a "Guardians of the Galaxy" themed ride?', 'Peter Pan''s Flight', 'Pirates of the Caribbean', 'The Haunted Mansion', 'Twilight Zone Tower of Terror', 'D', 'general', 'pro'),
('How many notes are there on a standard grand piano?', '78', '108', '98', '88', 'D', 'general', 'legend'),
('Which famed architect, who died in 2019 aged 102, designed the glass pyramid at the Louvre museum in Paris?', 'Wang Shu', 'Frank Gehry', 'Pascale Guédot', 'I. M. Pei', 'D', 'general', 'pro'),
('What do sailors call the right side of a boat?', 'Bow', 'Stern', 'Port', 'Starboard', 'D', 'general', 'rookie'),
('The website "Shut Up & Sit Down" reviews which form of media?', 'Films', 'Video Games', 'Television Shows', 'Board Games', 'D', 'general', 'pro'),
('Which company did Valve cooperate with in the creation of the Vive?', 'Razer', 'Google', 'Oculus', 'HTC', 'D', 'general', 'rookie'),
('How many fingers does a single human hand have?', 'Eight', 'Ten', 'Five', 'Four', 'D', 'general', 'rookie'),
('What is the romanized Russian word for "winter"?', 'Osen''', 'Vesna', 'Leto', 'Zima', 'D', 'general', 'pro'),
('In aerodynamics, which force pushes an object upwards?', 'Thrust', 'Weight', 'Drag', 'Lift', 'D', 'general', 'rookie'),
('Amsterdam Centraal station is twinned with what station?', 'Brussels Midi', 'Paris Gare du Nord', 'Frankfurt (Main) Hauptbahnhof', 'London Liverpool Street', 'D', 'general', 'pro'),
('What is the French word for "fish"?', 'mer', 'escargot', 'fiche', 'poisson', 'D', 'general', 'rookie'),
('Which of these holidays is NOT usually celebrated in the month of December?', 'Hanukkah', 'Kwanzaa', 'Christmas', 'Thanksgiving', 'D', 'general', 'rookie'),
('The lesser-known continuation of the saying "Curiosity killed the cat..." is:', '"...but death by the truth is better than ignorance."', '"...which taught it not to do that."', '"...and the silent mouse remained thereat."', '"...but satisfaction brought it back."', 'D', 'general', 'pro'),
('In ancient Greece, if your job were a "hippeus" which of these would you own?', 'Boat', 'Guitar', 'Weave', 'Horse', 'D', 'general', 'pro'),
('When was the website reddit founded?', '2006', '2004', '2008', '2005', 'D', 'general', 'rookie');
