-- =====================================================
-- ENTERTAINMENT QUESTIONS PART 1 (150 questions)
-- Music, Board Games, Video Games
-- Category: entertainment
-- =====================================================

INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, category, difficulty) VALUES

-- MUSIC (50 questions)
('Which music publication is often abbreviated to NME?', 'New Metro Entertainment', 'Next Musical Enterprise', 'North Manchester Express', 'New Musical Express', 'D', 'entertainment', 'rookie'),
('Which rapper had an album that went double platinum with no features?', 'Kendrick Lamar', 'Drake', 'Big Sean', 'J. Cole', 'D', 'entertainment', 'pro'),
('What song by Tina Turner is the theme for Mad Max Beyond Thunderdome?', 'Let''s Stay Together', 'What''s Love Got To Do With It', 'I Don''t Wanna Lose You', 'We Don''t Need Another Hero', 'D', 'entertainment', 'pro'),
('Which American family band had a 1986 top 10 hit with the song ''Crush On You''?', 'DeBarge', 'The Jacksons', 'The Cover Girls', 'The Jets', 'D', 'entertainment', 'pro'),
('What is the name of Finnish DJ Darude''s hit single released in October 1999?', 'Dust Devil', 'Sirocco', 'Khamsin', 'Sandstorm', 'D', 'entertainment', 'rookie'),
('The co-creator of Gorillaz, Damon Albarn, is also the lead singer of what band?', 'Oasis', 'Radiohead', 'Queens of the Stone Age', 'Blur', 'D', 'entertainment', 'pro'),
('Who is the lead singer of Green Day?', 'Mike Dirnt', 'Sean Hughes', 'Tré Cool', 'Billie Joe Armstrong', 'D', 'entertainment', 'rookie'),
('Which Canadian reggae musician had a 1993 hit with the song ''Informer''?', 'Rain', 'Hail', 'Sleet', 'Snow', 'D', 'entertainment', 'rookie'),
('Which one of these songs did the group "Men At Work" NOT make?', 'Down Under', 'Who Can It Be Now?', 'It''s a Mistake', 'Safety Dance', 'D', 'entertainment', 'rookie'),
('Which of these Queen songs were sampled for the baseline in Vanilla "Ice''s Ice Ice Baby?"', 'Don''t Stop Me Now', 'Brighton Rock', 'Lazing On A Sunday Afternoon', 'Under Pressure', 'D', 'entertainment', 'pro'),
('Which term best describes the connection of two sections of a musical piece through a transitional passage?', 'Coda', 'Capo', 'Binary Form', 'Bridge', 'D', 'entertainment', 'rookie'),
('Who is the Pink Floyd song "Shine On You Crazy Diamond" written about?', 'John Lennon', 'David Gilmour', 'Floyd', 'Syd Barrett', 'D', 'entertainment', 'pro'),
('According to the American rapper Nelly, what should you do when its hot in here?', 'Take a cool shower', 'Drink some water', 'Go skinny dipping', 'Take off all your clothes', 'D', 'entertainment', 'rookie'),
('In what year was the smash hit song "Scatman''s World" released?', '1996', '1994', '1993', '1995', 'D', 'entertainment', 'pro'),
('What is rapper Drake''s real name?', 'Shaun Carter', 'Dwayne Carter', 'Andre Young', 'Aubrey Graham', 'D', 'entertainment', 'pro'),
('Which novelty band was best known for their UK chart hits "Combine Harvester" and "I Am a Cider Drinker" in 1976?', 'Goldie Lookin Chain', 'Bonzo Dog Doo-Dah Band', 'The Firm', 'The Wurzels', 'D', 'entertainment', 'pro'),
('What is the frontman''s name of the metal band Megadeth?', 'Rob Halford', 'Vince Neil', 'James Hetfield', 'Dave Mustaine', 'D', 'entertainment', 'rookie'),
('The key of sharps does the key of G# minor contain?', '3', '7', '0', '5', 'D', 'entertainment', 'legend'),
('Which song by Swedish electronic musician Avicii samples the song "Something''s Got A Hold On Me" by Etta James?', 'Fade Into Darkness', 'Silhouettes', 'Seek Bromance', 'Levels', 'D', 'entertainment', 'pro'),
('Who is the frontman of Muse?', 'Dominic Howard', 'Thom Yorke', 'Jonny Greenwood', 'Matt Bellamy', 'D', 'entertainment', 'pro'),
('The band Muse released their first album, Showbiz, in what year?', '1998', '2000', '2001', '1999', 'D', 'entertainment', 'rookie'),
('Who is the lead singer of Pearl Jam?', 'Ozzy Osbourne', 'Stone Gossard', 'Kurt Cobain', 'Eddie Vedder', 'D', 'entertainment', 'rookie'),
('Which English guitarist has the nickname "Slowhand"?', 'Mark Knopfler', 'Jeff Beck', 'Jimmy Page', 'Eric Clapton', 'D', 'entertainment', 'rookie'),
('What is the best selling album of all time from 1976 to 2018?', 'Back in Black', 'Abbey Road', 'The Dark Side of the Moon', 'Thriller', 'D', 'entertainment', 'rookie'),
('What song originally performed by The Bee Gees in 1978 had a cover version by Steps 20 years later?', 'Night Fever', 'Stayin'' Alive', 'You Should Be Dancing', 'Tragedy', 'D', 'entertainment', 'legend'),
('Which of these is the name of an American psychedelic rock band formed in 2002 by Benjamin Goldwasser and Andrew VanWyngarden?', 'MSTRKRFT', 'STRFKR', 'SBTRKT', 'MGMT', 'D', 'entertainment', 'pro'),
('Which song previously recorded by Elvis Presley was covered by UB40 with a reggae beat?', 'Jailhouse Rock', 'In the Ghetto', 'Wooden Heart', 'Can''t Help Falling in Love', 'D', 'entertainment', 'pro'),
('The tuba is a part of which musical family?', 'Percussion', 'Strings', 'Woodwind', 'Brass', 'D', 'entertainment', 'rookie'),
('Which artist collaborated with American DJ Dillon Francis to release the song 2016 "Need You"?', 'LOUDPVCK', 'KRNE', 'DVBBS', 'NGHTMRE', 'D', 'entertainment', 'pro'),
('Which band released the album "Sonic Highways" in 2014?', 'Coldplay', 'Nickelback', 'The Flaming Lips', 'Foo Fighters', 'D', 'entertainment', 'pro'),
('What is the stage name of New Zealand singer Phillipa "Pip" Brown?', 'Lorde', 'Kesha', 'Anika Moa', 'Ladyhawke', 'D', 'entertainment', 'legend'),
('What date is referenced in the 1971 song "September" by Earth, Wind & Fire?', '26th of September', '23rd of September', '24th of September', '21st of September', 'D', 'entertainment', 'pro'),
('Which Disney character sings the song "A Dream is a Wish Your Heart Makes"?', 'Belle', 'Snow White', 'Pocahontas', 'Cinderella', 'D', 'entertainment', 'rookie'),
('What is the stage name of English female rapper Mathangi Arulpragasam, who is known for the song "Paper Planes"?', 'K.I.A.', 'C.I.A.', 'A.I.A.', 'M.I.A.', 'D', 'entertainment', 'rookie'),
('Which member of the British pop group "The Spice Girls" was known as Ginger Spice?', 'Melanie Brown', 'Emma Bunton', 'Victoria Beckham', 'Geri Halliwell', 'D', 'entertainment', 'pro'),
('Which French duo had UK hits in 1998 with the songs ''Sexy Boy'', ''Kelly Watch The Stars'' & ''All I Need''?', 'Fire', 'Earth', 'Water', 'Air', 'D', 'entertainment', 'pro'),
('Which of these are NOT a Men at Work song?', 'Dr. Heckyll and Mr. Jive', 'Who Can It Be Now?', 'Be Good Johnny', 'Basket Case', 'D', 'entertainment', 'rookie'),
('Which year was the album "Floral Shoppe" by Macintosh Plus released?', '2014', '2013', '2012', '2011', 'D', 'entertainment', 'legend'),
('Which singer was featured in Swedish producer Avicii''s song "Wake Me Up"?', 'John Legend', 'CeeLo Green', 'Pharrell Williams', 'Aloe Blacc', 'D', 'entertainment', 'pro'),
('Which of the following songs was not originally released by Sir Elton John?', 'Crocodile Rock', 'Candle in the Wind', 'I Don''t Wanna Go On With You Like That', 'You''ll Be In My Heart', 'D', 'entertainment', 'rookie'),
('A Caixa Malacacheta is what kind of musical instrument which is commonly used in Latin American music?', 'Cow Bell', 'Bass Drum', 'Maraca', 'Snare Drum', 'D', 'entertainment', 'legend'),
('Björk''s "Unison" contains a sample of which Oval song?', 'Textuell', 'Panorama', 'Do While', 'Aero Deck', 'D', 'entertainment', 'legend'),
('What was The Velvet Underground''s first album called?', 'Loaded', 'The Velvet Underground', 'White Light / White Heat', 'The Velvet Underground & Nico', 'D', 'entertainment', 'pro'),
('What is the name of the main character from the music video of "Shelter" by Porter Robinson and A-1 Studios?', 'Rem', 'Ren', 'Ram', 'Rin', 'D', 'entertainment', 'pro'),
('How many studio albums have the heavy metal band, ''Metallica'' released in the period between 1983 and 2016?', '7', '9', '12', '10', 'D', 'entertainment', 'pro'),
('Who is a pioneer of "Minimal Music" in 1960s?', 'Wolfgang Amadeus Mozart', 'Brian Eno', 'Sigur Rós', 'Steve Reich', 'D', 'entertainment', 'legend'),
('Who performed "I Took A Pill In Ibiza"?', 'Avicii', 'Robbie Williams', 'Harry Styles', 'Mike Posner', 'D', 'entertainment', 'rookie'),
('Which one of these Rammstein songs has two official music videos?', 'Du Hast', 'Benzin', 'Mein Teil', 'Du Riechst So Gut', 'D', 'entertainment', 'pro'),
('What was the subject of the 2014 song "CoCo" by American rapper O. T. Genasis?', 'Conan O''Brien', 'Cobalt(II) carbonate', 'Coconut cream pie', 'Cocaine', 'D', 'entertainment', 'rookie'),
('Which of these songs from American Idiot: The Musical was a previously unreleased Green Day song?', 'Are We The Waiting', 'Before The Lobotomy', 'Favorite Son', 'When It''s Time', 'D', 'entertainment', 'pro'),

-- BOARD GAMES (50 questions)
('How many pieces are there on the board at the start of a game of chess?', '16', '20', '36', '32', 'D', 'entertainment', 'rookie'),
('The board game "Monopoly" is a variation of what board game?', 'Territorial Dispute', 'Property Feud', 'The Monopolist''s Game', 'The Landlord''s Game', 'D', 'entertainment', 'legend'),
('What do you declare in Rīchi Mahjong when you''ve drawn your winning tile?', 'Ron', 'Rīchi', 'Kan', 'Tsumo', 'D', 'entertainment', 'legend'),
('In Magic: The Gathering, which of the following was the first publicly released foil card?', 'Revenant', 'Beast of Burden', 'Dirtcowl Wurm', 'Lightning Dragon', 'D', 'entertainment', 'legend'),
('When Magic: The Gathering was first solicited, which of the following was it originally titled?', 'Magic', 'Magic Clash', 'Mana Duels', 'Mana Clash', 'D', 'entertainment', 'legend'),
('The board game "Ra" was designed by which designer?', 'Bruno Cathala', 'Uwe Rosenburg', 'Allison Kline', 'Reiner Knizia', 'D', 'entertainment', 'legend'),
('In Magic: The Gathering, what was a tribute card to Jamie Wakefield''s late wife Marilyn, who loved horses?', 'Loyal Pegasus', 'Vryn Wingmare', 'Sungrace Pegasus', 'Timbermare', 'D', 'entertainment', 'legend'),
('What happens when you roll 3 doubles in a row in Monopoly?', 'Get paid $200', 'Pay $200', 'Move to Free Parking', 'Go to jail', 'D', 'entertainment', 'pro'),
('Carcassonne is based on which French town?', 'Paris', 'Marseille', 'Clermont-Ferrand', 'Carcassonne', 'D', 'entertainment', 'rookie'),
('What letter is used to refer to blue mana in the card game Magic The Gathering?', 'B', 'L', 'E', 'U', 'D', 'entertainment', 'pro'),
('In Magic: The Gathering, what term for blocking was established in the Portal set?', 'Blocking', 'Resisting', 'Shielding', 'Intercepting', 'D', 'entertainment', 'legend'),
('Which of these cities is NOT featured in the Pandemic board game?', 'Ho Chi Minh City', 'Lagos', 'Karachi', 'Berlin', 'D', 'entertainment', 'legend'),
('In Magic: The Gathering, what card''s flavor text is "Catch!"?', 'Stone-Throwing Devils', 'Ember Shot', 'Throwing Knife', 'Lava Axe', 'D', 'entertainment', 'legend'),
('In which year was the pen and paper RPG "Deadlands" released?', '2003', '1999', '1993', '1996', 'D', 'entertainment', 'rookie'),
('Who was the first official world chess champion?', 'José Raúl Capablanca', 'Emanuel Lasker', 'Bobby Fischer', 'Wilhelm Steinitz', 'D', 'entertainment', 'pro'),
('The board game Monopoly takes its street names from which real American city?', 'Las Vegas, Nevada', 'Duluth, Minnesota', 'Charleston, South Carolina', 'Atlantic City, New Jersey', 'D', 'entertainment', 'rookie'),
('Which character class in Dungeons and Dragons 5th edition gains it''s powers from making a pact with a being of higher power?', 'Wizard', 'Sorceror', 'Cleric', 'Warlock', 'D', 'entertainment', 'legend'),
('What type is "Magic Drain" in Yugioh! Trading Card Game?', 'Normal Trap', 'Quick-Play Spell', 'Field Spell', 'Counter Trap', 'D', 'entertainment', 'pro'),
('How many dots are on a single die?', '24', '15', '18', '21', 'D', 'entertainment', 'rookie'),
('Which of the following tabletop games is the oldest?', 'Chess', 'Mahjong', 'Shogi', 'Go', 'D', 'entertainment', 'pro'),
('What was the development code name for the "Urza''s Destiny" expansion for "Magic: The Gathering", released in 1999?', 'Burrito', 'Taquito', 'Enchilada', 'Chimichanga', 'D', 'entertainment', 'legend'),
('In a standard game of Monopoly, what colour are the two cheapest properties?', 'Green', 'Yellow', 'Blue', 'Brown', 'D', 'entertainment', 'rookie'),
('The Dice Tower network of board game podcasts and videos is run by which individual?', 'Jason LeVine', 'Borth Sampson', 'Uncle Pennybags', 'Tom Vasel', 'D', 'entertainment', 'legend'),
('Europa Universalis is a strategy video game based on which French board game?', 'Europe and the Universe', 'Europa!', 'Power in Europe', 'Europa Universalis', 'D', 'entertainment', 'pro'),
('How many points is the Z tile worth in Scrabble?', '8', '5', '6', '10', 'D', 'entertainment', 'pro'),
('Who was world chess champion between 1894 and 1921', 'José Raúl Capablanca', 'Wilhelm Steinitz', 'Bobby Fischer', 'Emanuel Lasker', 'D', 'entertainment', 'pro'),
('Who is the main character in the VHS tape included in the board game Nightmare?', 'The Kryptkeeper', 'The Monster', 'The Nightmare', 'The Gatekeeper', 'D', 'entertainment', 'pro'),
('In standard Monopoly, what''s the rent if you land on Park Place with no houses?', '$30', '$50', '$45', '$35', 'D', 'entertainment', 'legend'),
('In board games, an additional or ammended rule that applies to a certain group or place is informally known as a "what" rule?', 'Custom', 'Extra', 'Change', 'House', 'D', 'entertainment', 'rookie'),
('Which of these cards from "Magic: The Gathering" has a flavor text that begins with "Oi oi oi"?', 'Lotleth Troll', 'Albino Troll', 'Harvester Troll', 'Uthden Troll', 'D', 'entertainment', 'legend'),
('In Dungeons and Dragons (5th edition), what stat do you normally add onto your initiative die roll?', 'Speed', 'Strength', 'Wisdom', 'Dexterity', 'D', 'entertainment', 'rookie'),
('The board game, Nightmare was released in what year?', '1992', '1989', '1995', '1991', 'D', 'entertainment', 'pro'),
('Which card is on the cover of the Beta rulebook of "Magic: The Gathering"?', 'Island', 'Rock Hydra', 'Elvish Archers', 'Bog Wraith', 'D', 'entertainment', 'legend'),
('At the start of a standard game of the Monopoly, if you throw a double six, which square would you land on?', 'Water Works', 'Chance', 'Community Chest', 'Electric Company', 'D', 'entertainment', 'pro'),
('Some of the "Fallen Empires" cards from "Magic: The Gathering" were misprinted on the backs of which other card game?', 'Pokemon', 'Dominion', 'Yu-Gi-Oh', 'Wyvern', 'D', 'entertainment', 'legend'),
('What special item did the creators of Cards Against Humanity ship for their Black Friday pack?', 'A Card Expansion', 'A Racist Toy', 'Cat Urine', 'Bull Feces', 'D', 'entertainment', 'pro'),
('Which of these games includes the phrase "Do not pass Go, do not collect $200"?', 'Pay Day', 'Cluedo', 'Coppit', 'Monopoly', 'D', 'entertainment', 'rookie'),
('In "Magic: The Gathering", what instant card has the highest converted mana cost?', 'Vitalizing Wind', ' Chant of Vitu-Ghazi', 'Assert Authority', 'Blinkmoth Infusion', 'D', 'entertainment', 'pro'),
('How many rooms are there, not including the hallways and the set of stairs, in the board game "Clue"?', '1', '6', '10', '9', 'D', 'entertainment', 'legend'),
('In Chess, the Queen has the combined movement of which two pieces?', 'Rook and King', 'Knight and Bishop', 'King and Knight', 'Bishop and Rook', 'D', 'entertainment', 'pro'),
('What is the world''s oldest board game?', 'Chess', 'Checkers', 'Go', 'Senet', 'D', 'entertainment', 'legend'),
('What is the maximum level you can have in a single class in Dungeons and Dragons (5e)?', '30', '15', '25', '20', 'D', 'entertainment', 'rookie'),
('About how many Slinkys were sold in their first 60 years (from 1945 to 2005)?', '100 Million', '450 Million', '1 Billion', '300 Million', 'D', 'entertainment', 'pro'),
('Which of the following is NOT a class in Dungeons and Dragons 5e?', 'Fighter ', 'Paladin ', 'Bard', 'Engineer ', 'D', 'entertainment', 'rookie'),
('Which ability from the "Magic: The Gathering" Scars of Mirrodin expansion involves having at least three artifacts in play?', 'Affinity', 'Imprint', 'Living Weapon', 'Metalcraft', 'D', 'entertainment', 'legend'),
('Which one of these is not a real game in the Dungeons & Dragons series?', 'Advanced Dungeons & Dragons', 'Dungeons & Dragons 3.5th edition', 'Advanced Dungeons & Dragons 2nd edition', 'Extreme Dungeons & Dragons', 'D', 'entertainment', 'rookie'),
('In what year was the card game Magic: the Gathering first introduced?', '1987', '1998', '2003', '1993', 'D', 'entertainment', 'pro'),
('What is the sum of all the tiles in a standard box of Scrabble?', '207', '197', '177', '187', 'D', 'entertainment', 'legend'),
('Which of the following characters is not in the board game Clue?', 'Colonel Mustard', 'Reverend Green', 'Miss Scarlet', 'Mister Indigo', 'D', 'entertainment', 'pro'),
('When was the board game Twister, released to the public?', 'September 1965', 'January 1969', 'February 1966', 'April 1966', 'D', 'entertainment', 'rookie'),

-- VIDEO GAMES (50 questions)
('In "Overwatch", what is the name of Mercy''s "ultimate ability"?', 'Earthshatter', 'Rocket Barrage', 'Molten Core', 'Valkyrie', 'D', 'entertainment', 'pro'),
('What is the name of the machine that fails and essentially dooms mankind in the beginning of the first Half-Life game?', 'Oscillation generator', 'Dark fusion reactor', 'Dark fusion resonator', 'Anti-mass spectrometer', 'D', 'entertainment', 'pro'),
('Which company developed and published Game Dev Tycoon?', 'Greenland Games', 'The Tycoonists', 'MomCorp', 'Greenheart Games', 'D', 'entertainment', 'pro'),
('In the video game "Team Fortress 2", which class is able to double jump?', 'Spy', 'Engineer', 'Pyro', 'Scout', 'D', 'entertainment', 'rookie'),
('From the Meme Culture, which Mario game immerged "Weegee"?', 'Mario is Missing! SNES Version', 'Mario is Missing! NES Version', 'Mario is Missing! MSX Version', 'Mario is Missing! MS-DOS Version ', 'D', 'entertainment', 'pro'),
('In what year was the game "Fallout" released?', '1998', '1999', '1996', '1997', 'D', 'entertainment', 'rookie'),
('In "Earthbound", how does one enter "Master Belch''s" factory?', 'Enter the password "Fly Honey"', 'Enter the password "Master Belch Rules"', 'Enter the password "Mr Saturn Drools"', 'Wait 3 Minutes', 'D', 'entertainment', 'legend'),
('In Splatoon 2''s Hero Mode, which agent does the player take the role of?', 'Agent 1', 'Agent 2', 'Agent 3', 'Agent 4', 'D', 'entertainment', 'pro'),
('Which game in the "Monster Hunter" series introduced the monster "Gobul"?', 'Monster Hunter Freedom Unite', 'Monster Hunter Frontier', 'Monster Hunter Generations', 'Monster Hunter Tri', 'D', 'entertainment', 'legend'),
('In the game Dark Souls, what is the name of the region you''re in for the majority of the game?', 'Drangleic', 'Oolacile', 'Catarina', 'Lordran', 'D', 'entertainment', 'rookie'),
('Which company developed the free battle royale game Fortnite?', 'Valve', 'Ubisoft', 'Square Enix', 'Epic Games', 'D', 'entertainment', 'rookie'),
('What was the nickname of the original model for Half-Life''s protagonist Gordon Freeman?', 'Gordon the Space Biker', 'Ivan the Alien Biker', 'Gordon the Alien Biker', 'Ivan the Space Biker', 'D', 'entertainment', 'legend'),
('Excluding their instructor, how many members of Class VII are there in the game "Legend of Heroes: Trails of Cold Steel"?', '6', '10', '3', '9', 'D', 'entertainment', 'pro'),
('Which of the following is not a prosecutor in the "Ace Attorney" video game series?', 'Godot', 'Miles Edgeworth', 'Jacques Portsman', 'Jake Marshall', 'D', 'entertainment', 'pro'),
('In Counter Strike: Global Offensive, what is the code implanted onto the C4 as the Terrorists plant the bomb?', '7890728', '7256380', '7726354', '7355608', 'D', 'entertainment', 'legend'),
('The protagonist in the game "Cave Story" is named', 'Kazuma', 'Curly', 'Arthur', 'Quote', 'D', 'entertainment', 'pro'),
('In the Nintendo Game Splatoon 2, what is Marina''s screen name?', 'MC.princess', 'Kidnotsquid123', 'I<30ffTh3H00k', 'DJ_Hyperfresh', 'D', 'entertainment', 'legend'),
('Given that all party members are maxed, who is the fastest party member in Super Mario RPG: Legend of The Seven Stars?', 'Mario', 'Bowser', 'Peach', 'Geno', 'D', 'entertainment', 'legend'),
('Which character is from "Splatoon"?', 'Cyrus', 'Palutena', 'Shulk', 'Marie', 'D', 'entertainment', 'pro'),
('In the "Ace Attorney" series, what is the relationship between Apollo Justice and Trucy Wright?', 'They''re co-workers', 'They''re friends', 'They''re both attorneys', 'They''re half-siblings', 'D', 'entertainment', 'pro'),
('In the video game "League of Legends" which character is known as "The Sinister Blade"?', 'Shaco', 'Akali', 'Zed', 'Katarina', 'D', 'entertainment', 'pro'),
('In the game "Overwatch," what are the names of the two Australian criminals from the Junkers faction?', 'Roadrat and Junkhog', 'Ana and Pharah', 'McCree and Deadeye', 'Junkrat and Roadhog', 'D', 'entertainment', 'rookie'),
('In which "Call of Duty" game are the "Apothicons" introduced in the Zombies mode?', 'Call Of Duty: Black Ops', 'Call Of Duty: World At War', 'Call Of Duty: Black Ops II', 'Call Of Duty: Black Ops III', 'D', 'entertainment', 'pro'),
('In "Mario & Sonic at the Olympic Games", characters are split into how many types?', '6', '5', '3', '4', 'D', 'entertainment', 'rookie'),
('The Khajiit are a race of cat-like creatures from which epic series of role-playing games, set across the land of Tamriel?', 'Lord of the Rings', 'The Witcher', 'Neverwinter Nights', 'The Elder Scrolls', 'D', 'entertainment', 'rookie'),
('In World of Warcraft lore,  how many siblings does Sylvanas Windrunner have?', '2', '4', '1', '3', 'D', 'entertainment', 'pro'),
('In which mall does "Dead Rising" take place?', 'Liberty Mall', 'Twin Pines Mall', 'Central Square Shopping Center', 'Willamette Parkview Mall', 'D', 'entertainment', 'rookie'),
('Who created the indie adventure game "Night in the Woods"?', 'Ron Gilbert', 'Tim Schafer', ' Tommy Refenes', 'Alec Holowka', 'D', 'entertainment', 'rookie'),
('In the video game DOTA 2, which of these is NOT a hero?', 'Dark Seer', 'Keeper of the Light', 'Mirana', 'Dragon Champion', 'D', 'entertainment', 'pro'),
('In Kingdom Hearts which of the following people can NOT wield a keyblade?', 'Xehanort', 'Lea', 'Mickey', 'Larxene', 'D', 'entertainment', 'pro'),
('Which Sonic the Hedgehog game introudced Knuckles the Echidna?', 'Sonic the Hedgehog 2', 'Sonic & Knuckles', 'Sonic Adventure', 'Sonic the Hedgehog 3', 'D', 'entertainment', 'pro'),
('Which of the Master levels in "Super Monkey Ball" is also used in the arcade version of the game, simply named "Monkey Ball"?', 'MASTER 3 - Stamina Master', 'MASTER 10 - Monkey Master', 'MASTER 6 - Roll Master', 'MASTER 9 - Bridge Master', 'D', 'entertainment', 'legend'),
('According to Overwatch''s lore, who was once a member of the Deadlock Gang?', 'Roadhog', 'Soldier 76', 'Junkrat', 'McCree', 'D', 'entertainment', 'pro'),
('Which of these is not the name of a city in the Grand Theft Auto series?', 'San Fierro', 'Las Venturas', 'Vice City', 'San Andreas', 'D', 'entertainment', 'pro'),
('In Terraria, what does the Wall of Flesh not drop upon defeat?', 'Pwnhammer', 'Breaker Blade', 'Laser Rifle', 'Picksaw', 'D', 'entertainment', 'pro'),
('Which of these weapons is NOT available to the Terrorist team in the game, "Counter-Strike: Global Offensive"?', 'SG 550', 'CZ-75', 'XM1014', 'SCAR-20', 'D', 'entertainment', 'pro'),
('When Halo 3: ODST was unveiled in 2008, it had a different title. What was the game formally called?', 'Halo 3: Helljumpers', 'Halo 3: Phantom', 'Halo 3: Guerilla', 'Halo 3: Recon', 'D', 'entertainment', 'pro'),
('When was the Valve Corporation founded?', 'December 26, 1994', 'March 22, 1997', 'March 13, 1997', 'August 24, 1996', 'D', 'entertainment', 'legend'),
('In the Portal series, Aperture Science was founded under what name in the early 1940s?', 'Aperture Lavatories', 'Aperture Science Innovators', 'Wheatley Laboratories', 'Aperture Fixtures', 'D', 'entertainment', 'pro'),
('What is the name of Joel''s daughter in the game, "The Last of Us"?', 'Ellie', 'Tess', 'Marlene', 'Sarah', 'D', 'entertainment', 'pro'),
('In the game "Brawlhalla", what species is the character Bödvar is?', 'A Human', 'Half Wolf / Half Bear', 'Half Tiger /  Half Human', 'Half Human / Half Bear', 'D', 'entertainment', 'pro'),
('The rights to the "Rayman" series are owned by which company?', 'Nintendo', 'EA', 'Sony', 'Ubisoft', 'D', 'entertainment', 'pro'),
('In the Super Mario Bros. series, what game is the  "Carrot" power-up from?', 'Super Mario World', 'Super Mario Land', 'Super Mario 3D Land', 'Super Mario Land 2: The 6 Golden Coins', 'D', 'entertainment', 'pro'),
('Which Dota 1 hero changed gender when ported to Dota 2?', 'Axe', 'Keeper of the Light', 'Templar Assassin', 'Legion Commander', 'D', 'entertainment', 'pro'),
('How many regular Sunken Sea Scrolls are there in "Splatoon"?', '32', '30', '5', '27', 'D', 'entertainment', 'pro'),
('How many total monsters appear in Monster Hunter Generations?', '100', '98', '73', '105', 'D', 'entertainment', 'legend'),
('In what year was "Antichamber" released?', '2012', '2014', '2011', '2013', 'D', 'entertainment', 'rookie'),
('In Need For Speed Most Wanted (2005), what do you drive at the beginning of the career mode?', 'Porsche 911 Turbo', 'Nissan 240SX', 'Ford Mustang', 'BMW M3 GTR', 'D', 'entertainment', 'pro'),
('How many classes are there in Team Fortress 2?', '10', '8', '7', '9', 'D', 'entertainment', 'pro'),
('In "Clash Royale" what is Arena 4 called?', 'Barbarian Bowl', 'P.E.K.K.A''s Playhouse', 'Royal Arena', 'Spell Valley', 'D', 'entertainment', 'pro');
