-- =====================================================
-- ENTERTAINMENT QUESTIONS PART 2 (150 questions)
-- Television, Books, Film
-- Category: entertainment
-- =====================================================

INSERT INTO trivia_questions (question, option_a, option_b, option_c, option_d, correct_answer, category, difficulty) VALUES

-- TELEVISION (50 questions)
('In the show ''Doctor Who'', what is the name of the time-capsule model stolen by ''the Doctor''?', 'TT Type 1, Mark 3 (TARDIS)', 'TT Type 40, Mark 5 (TARDIS)', 'TT Type 1, Mark 5 (TARDIS)', 'TT Type 40, Mark 3 (TARDIS)', 'D', 'entertainment', 'legend'),
('In the cartoon ''SpongeBob SquarePants'', what did the acronym E.V.I.L stand for?', 'Every Villain Is Lemonade', 'Every Villain Is Limes', 'Each Villain Is Lemonade', 'Every Villain Is Lemons', 'D', 'entertainment', 'rookie'),
('In which year did the British television series "The Bill" end?', '2001', '2007', '2012', '2010', 'D', 'entertainment', 'pro'),
('Which of the following won the first season of American Idol in 2002?', 'Justin Guarini', 'Ruben Studdard', 'Chris Daughtry', 'Kelly Clarkson', 'D', 'entertainment', 'rookie'),
('What actor portrays Hogan "Wash" Washburne in the TV Show Firefly?', 'Adam Baldwin', 'Nathan Fillion', 'Sean Maher', 'Alan Tudyk', 'D', 'entertainment', 'pro'),
('Which character was played by Dustin Diamond in the sitcom ''Saved by the Bell''?', 'Zack', 'Mr. Belding', 'A.C. Slater', 'Screech', 'D', 'entertainment', 'rookie'),
('What''s Dr. Doofenshmirtz first name?', 'Hans', 'Hank', 'Heidi', 'Heinz', 'D', 'entertainment', 'legend'),
('The 1985 Toyota Corolla "AE86" was the hero car for what anime?', 'Wangan Midnight', 'Ghost MF', 'Ex Driver', 'Initial D', 'D', 'entertainment', 'pro'),
('Which of these Bojack Horseman characters is a human?', 'Lennie Turtletaub', 'Princess Carolyn', 'Tom Jumbo-Grumbo', 'Todd Chavez', 'D', 'entertainment', 'rookie'),
('In "Star Trek: Voyager", which episode did Voyager establish real-time communication with Starfleet Headquarters?', 'Message In A Bottle', 'Someone To Watch Over Me', 'Counterpoint', 'Pathfinder', 'D', 'entertainment', 'rookie'),
('In which state of America was the Fresh Prince of Bel-Air born and raised in?', 'Florida', 'California', 'New Jersey', 'Pennsylvania', 'D', 'entertainment', 'rookie'),
('Which character does voice actress Tara Strong NOT voice?', 'Twilight Sparkle', 'Timmy Turner', 'Harley Quinn', 'Bubbles (2016)', 'D', 'entertainment', 'pro'),
('Which of the following Autobot names in Michael Bay''s movies was NOT a name for a Transformer in the original 1980''s cartoon?', 'Skids', 'Sideswipe', 'Ratchet', 'Mudflap', 'D', 'entertainment', 'pro'),
('At which university do "The Big Bang Theory" characters Mr. Wolowitz and Drs. Cooper, Hofstadter and Koothrappali work?', 'UCLA', 'MIT', 'UC Berkeley ', 'Caltech', 'D', 'entertainment', 'pro'),
('In the show Stranger Things, what is Eleven''s favorite breakfast food?', 'Toast', 'Captain Crunch', 'Bacon and Eggs', 'Eggo Waffles', 'D', 'entertainment', 'rookie'),
('Pat Cashman, the announcer for Super Smash Brothers: Brawl, also featured prominently in what famous TV show?', 'The Muppet Show', 'Scooby-Doo', 'Seinfeld', 'Bill Nye the Science Guy', 'D', 'entertainment', 'pro'),
('In Game of Thrones, what is Littlefinger''s real name?', 'Podrick Payne', 'Lancel Lannister', 'Torrhen Karstark', 'Petyr Baelish', 'D', 'entertainment', 'rookie'),
('Who played Agent Fox Mulder in the TV sci-fi drama "The X-Files"?', 'Gillian Anderson', 'Robert Patrick', 'Mitch Pileggi', 'David Duchovny', 'D', 'entertainment', 'rookie'),
('Which track by "Massive Attack" is used for the theme of "House"?', 'Protection', 'Angel', 'Black Milk', 'Teardrop', 'D', 'entertainment', 'pro'),
('Which of these in the Star Trek series is NOT Klingon food?', 'Racht', 'Gagh', 'Bloodwine', 'Hors d''oeuvre', 'D', 'entertainment', 'legend'),
('Which actor portrays "Walter White" in the series "Breaking Bad"?', 'Andrew Lincoln', 'Aaron Paul', 'RJ Mitte', ' Bryan Cranston', 'D', 'entertainment', 'rookie'),
('How many seasons did "Stargate SG-1" have?', '3', '7', '12', '10', 'D', 'entertainment', 'rookie'),
('What episode of "Mr. Bean" saw him trying to prevent people from seeing him naked?', 'Mr. Bean Goes to Town', 'The Trouble with Mr. Bean', 'Back to School Mr. Bean', 'Mr. Bean in Room 426', 'D', 'entertainment', 'pro'),
('What breed of dog is "Scooby Doo"?', 'Pit bull', 'Boxer', 'Doberman Pinscher', 'Great Dane', 'D', 'entertainment', 'pro'),
('In Star Trek, what is the name of Spock''s father?', 'Tuvok', 'T''Pal', 'Surak', 'Sarek', 'D', 'entertainment', 'legend'),
('In what year did "The Big Bang Theory" debut on CBS?', '2008', '2006', '2009', '2007', 'D', 'entertainment', 'pro'),
('What was the name of the the first episode of Doctor Who to air in 1963?', 'The Daleks', 'The Aztecs', 'The Edge of Destruction', 'An Unearthly Child', 'D', 'entertainment', 'rookie'),
('What Nickelodeon game show featured a house on the set that the contestants would ransack to find hidden objects?', 'Double Dare', 'Nickelodeon Guts', 'Nick Arcade', 'Finders Keepers', 'D', 'entertainment', 'rookie'),
('In "Star Trek", who was the founder of the Klingon Empire and its philosophy?', 'Lady Lukara of the Great Hall', 'Molor the Unforgiving', 'Dahar Master Kor', 'Kahless the Unforgettable', 'D', 'entertainment', 'legend'),
('Which company has exclusive rights to air episodes of the "The Grand Tour"?', 'Netflix', 'BBC', 'CCTV', 'Amazon', 'D', 'entertainment', 'rookie'),
('What was the name of Ross'' pet monkey on "Friends"?', 'Jojo', 'George', 'Champ', 'Marcel', 'D', 'entertainment', 'pro'),
('In AMC''s TV Series "The Walking Dead" what are "Zombies" referred to as?', 'Creepers', 'Maggots', 'Hell Pigs', 'Walkers', 'D', 'entertainment', 'rookie'),
('Which of the following was not an actor/actress on the American television show "Saturday Night Live" in Season 42?', 'Mikey Day', 'Kate McKinnon', 'Sasheer Zamata', 'Tina Fey', 'D', 'entertainment', 'pro'),
('In "Donkey Kong Country", why does Donkey Kong want to know the secret of the crystal coconut?', 'To find out where all the bananas are.', 'Because Diddy Kong forced him.', 'He wants to punish brutes.', 'He''s the big kahuna.', 'D', 'entertainment', 'legend'),
('In 2008, British celebrity chef Gordon Ramsay believes he almost died after suffering what accident in Iceland while filming?', 'Crash landing when arriving at Keflavík airport', 'A minor car accident in a snowstorm', 'Being served under-cooked chicken at his hotel', 'Slipping off a cliff, and nearly drowning in icy water', 'D', 'entertainment', 'legend'),
('"The A Team" first aired in the USA and in the UK in what year?', '1981', '1985', '1987', '1983', 'D', 'entertainment', 'pro'),
('This composer worked on the 2003 TV series Battlestar Galatica.', 'Ramin Djawadi', 'Jeremy Soule', 'Harry Gregson-Williams', 'Bear McCreary', 'D', 'entertainment', 'pro'),
('Who played the sun baby in the original run of Teletubbies?', 'Pui Fan Lee', 'Sue Monroe', 'Lisa Brockwell', 'Jessica Smith', 'D', 'entertainment', 'legend'),
('What country is Cory in the House set in?', 'Canada', 'Venezuala', 'England', 'The United States of America', 'D', 'entertainment', 'rookie'),
('What is the name of the race horse that Tony Soprano becomes attached to?', 'Man o'' war', 'Bada Bing', 'Honest Earnings', 'Pie-O-My', 'D', 'entertainment', 'pro'),
('In Game of Thrones, what continent lies across the Narrow Sea from Westeros?', 'Easteros', 'Westereast', 'Esuntos', 'Essos', 'D', 'entertainment', 'rookie'),
('What NBC sitcom once saw two of its characters try to pitch NBC on a sitcom about nothing?', 'Frasier', 'Becker', 'Friends', 'Seinfeld', 'D', 'entertainment', 'rookie'),
('What is the surname of the character Daryl in AMC''s show The Walking Dead?', 'Grimes', 'Dickinson', 'Dicketson', 'Dixon', 'D', 'entertainment', 'pro'),
('Guy''s Grocery Games is hosted by which presenter?', 'Guy Martin', 'Guy Ritchie', 'Ainsley Harriott', 'Guy Fieri', 'D', 'entertainment', 'rookie'),
('In Two and a Half Men, what is Alan Harper''s son''s name?', 'John', 'Jeremy', 'James', 'Jake', 'D', 'entertainment', 'rookie'),
('The fictional movie ''Rochelle, Rochelle'' features in which sitcom?', 'Frasier', 'Cheers', 'Friends', 'Seinfeld', 'D', 'entertainment', 'pro'),
('Which actor was not a major character in TV Show Freaks and Geeks?', 'Jason Segel', 'Seth Rogen', 'James Franco', 'Jonah Hill', 'D', 'entertainment', 'pro'),
('Dee from "It''s Always Sunny in Philadelphia" has dated all of the following guys EXCEPT', 'Colin the Thief', 'Ben the Soldier', 'Kevin Gallagher aka Lil'' Kevin', 'Matthew "Rickety Cricket" Mara', 'D', 'entertainment', 'pro'),
('In the Black Mirror episode "Bandersnatch", PAC-MAN stands for:', 'Postgraduate Aplications Centre Man', 'Political Action Committee Man', 'Physics & Astronomy Classification Man', 'Program And Control Man', 'D', 'entertainment', 'pro'),
('What is the real name of the famous spanish humorist, El Risitas?', 'Gabriel Garcia Marquez', 'Jesus Quintero', 'Ernesto Guevara', 'Juan Joya Borga', 'D', 'entertainment', 'rookie'),

-- BOOKS (50 questions)
('How many books are in the Chronicles of Narnia series?', '6', '8', '5', '7', 'D', 'entertainment', 'pro'),
('In Terry Pratchett''s Discworld novel ''Wyrd Sisters'', which of these are not one of the three main witches?', 'Granny Weatherwax', 'Nanny Ogg', 'Magrat Garlick', 'Winny Hathersham', 'D', 'entertainment', 'pro'),
('Which of the following is not a work authored by Fyodor Dostoevsky?', 'Notes from the Underground', 'Crime and Punishment', 'The Brothers Karamazov', 'Anna Karenina', 'D', 'entertainment', 'pro'),
('What was the first ever entry written for the SCP Foundation collaborative writing project?', 'SCP-001', 'SCP-999', 'SCP-1459', 'SCP-173', 'D', 'entertainment', 'rookie'),
('In "Little Women", which of the March sisters married Laurie?', 'Beth', 'Jo', 'Meg', 'Amy', 'D', 'entertainment', 'pro'),
('American illustrator and writer Maurice Sendak is most well-known for writing which children''s book?', 'The Neverending Story', 'Charlie and the Chocolate Factory', 'The Cat in the Hat', 'Where The Wild Things Are', 'D', 'entertainment', 'rookie'),
('Who wrote the 1967 horror novel "Rosemary''s Baby"?', 'Stephen King', 'Robert Bloch', 'Mary Shelley', 'Ira Levin', 'D', 'entertainment', 'pro'),
('Which is NOT a book in the Harry Potter Series?', 'The Chamber of Secrets', 'The Prisoner of Azkaban', 'The Deathly Hallows', 'The House Elf', 'D', 'entertainment', 'rookie'),
('Which of these does Charlie NOT read in The Perks of Being a Wallflower?', 'Hamlet', 'The Great Gatsby', 'Peter Pan', 'The Grapes of Wrath', 'D', 'entertainment', 'legend'),
('Which author co-wrote "The Communist Manifesto" alongside Karl Marx?', 'Robert Owen', 'Alexander Kerensky', 'Paul Lafargue', 'Friedrich Engels', 'D', 'entertainment', 'legend'),
('Which of the following is NOT a work done by Shakespeare?', 'Measure For Measure', 'Titus Andronicus', 'Cymbeline', 'Trial of Temperance', 'D', 'entertainment', 'legend'),
('Which of these books was NOT written by the Czech author Karel Čapek?', 'The War with the Newts', 'R.U.R. (Rossum''s Universal Robots)', 'Dashenka, or the Life of a Puppy', 'Journey to the Center of the Earth', 'D', 'entertainment', 'pro'),
('In the Lord of the Rings, who is the father of the dwarf Gimli?', 'Thorin Oakenshield', 'Bombur', 'Dwalin', 'Gloin', 'D', 'entertainment', 'pro'),
('In the novel "Lord of the Rings", how many rings of power were given to the race of man?', '5', '11', '13', '9', 'D', 'entertainment', 'pro'),
('Which famous spy novelist wrote the childrens'' story "Chitty-Chitty-Bang-Bang"?', 'Joseph Conrad', 'John Buchan', 'Graham Greene', 'Ian Fleming', 'D', 'entertainment', 'rookie'),
('Who wrote the children''s story "The Little Match Girl"?', 'Charles Dickens', 'Lewis Carroll', 'Oscar Wilde', 'Hans Christian Andersen', 'D', 'entertainment', 'pro'),
('What was the pen name of novelist, Mary Ann Evans?', 'George Orwell', 'George Bernard Shaw', 'George Saunders', 'George Eliot', 'D', 'entertainment', 'pro'),
('In the Magic: The Gathering universe, the Fallen Empires expansion takes place on which continent?', 'Otaria', 'Terisiare', 'Shiv', 'Sarpadia', 'D', 'entertainment', 'legend'),
('What is the name of the gang that Ponyboy is a part of in the book, The Outsiders?', 'The Outsiders', 'The Mafia', 'The Socs', 'The Greasers', 'D', 'entertainment', 'pro'),
('Where does Stephen King''s "IT" take place?', 'Rockford, Illinois', 'Innsmouth, Massachusetts', 'Kingsland, Texas', 'Derry, Maine', 'D', 'entertainment', 'pro'),
('J.K. Rowling completed "Harry Potter and the Deathly Hallows" in which hotel in Edinburgh, Scotland?', 'The Dunstane Hotel', 'Hotel Novotel', 'Sheraton Grand Hotel & Spa', 'The Balmoral', 'D', 'entertainment', 'pro'),
('What is Ron Weasley''s middle name?', 'Arthur', 'John', 'Dominic', 'Bilius', 'D', 'entertainment', 'legend'),
('According to The Hitchhiker''s Guide to the Galaxy book, the answer to life, the universe and everything else is...', 'Loving everyone around you', 'Chocolate', 'Death', '42', 'D', 'entertainment', 'pro'),
('The novel "Of Mice And Men" was written by what author?', 'George Orwell', 'Mark Twain ', 'Harper Lee', 'John Steinbeck ', 'D', 'entertainment', 'pro'),
('What book series published by Jim Butcher follows a wizard in modern day Chicago?', 'A Hat in Time', 'The Cinder Spires', 'My Life as a Teenage Wizard', 'The Dresden Files', 'D', 'entertainment', 'pro'),
('The book "The Little Prince" was written by...', 'Miguel de Cervantes Saavedra', 'Jane Austen', 'F. Scott Fitzgerald', 'Antoine de Saint-Exupéry', 'D', 'entertainment', 'pro'),
('Which Russian author wrote the epic novel War and Peace?', 'Fyodor Dostoyevsky', 'Alexander Pushkin', 'Vladimir Nabokov', 'Leo Tolstoy', 'D', 'entertainment', 'pro'),
('In the "The Hobbit", who kills Smaug?', 'Bilbo Baggins', 'Gandalf the Grey', 'Frodo', 'Bard', 'D', 'entertainment', 'pro'),
('Which classic book opens with the line "Call me Ishmael"?', 'A Tale of Two Cities', 'Kidnapped', 'Wuthering Heights', 'Moby Dick', 'D', 'entertainment', 'rookie'),
('What is the name of Eragon''s dragon in "Eragon"?', 'Glaedr', 'Thorn', 'Arya', 'Saphira', 'D', 'entertainment', 'pro'),
('Which American author was also a budding travel writer and wrote of his adventures with his dog Charley?', 'F. Scott Fitzgerald', 'Ernest Hemingway', 'William Faulkner', 'John Steinbeck', 'D', 'entertainment', 'pro'),
('What was the name of Captain Nemo''s submarine in "20,000 Leagues Under the Sea"?', 'The Neptune', 'The Poseidon  ', 'The Atlantis', 'The Nautilus', 'D', 'entertainment', 'rookie'),
('What is the name of the protagonist of J.D. Salinger''s novel Catcher in the Rye?', 'Fletcher Christian', 'Jay Gatsby', 'Randall Flagg', 'Holden Caulfield', 'D', 'entertainment', 'rookie'),
('What''s the second book in George R. R. Martin''s ''A Song of Ice and Fire'' series?', 'A Dance with Dragons', 'A Storm of Swords', 'A Feast for Crows', 'A Clash of Kings', 'D', 'entertainment', 'rookie'),
('In the "Harry Potter" series, what is Headmaster Dumbledore''s full name?', 'Albus Valum Jetta Mobius Dumbledore', 'Albus James Lunae Otto Dumbledore', 'Albus Valencium Horatio Kul Dumbledore', 'Albus Percival Wulfric Brian Dumbledore', 'D', 'entertainment', 'legend'),
('In the novel 1984, written by George Orwell, what is the name of the totalitarian regime that controls Oceania?', 'Neo-Bolshevism', 'Obliteration of the Self', 'Earth Alliance', 'INGSOC', 'D', 'entertainment', 'rookie'),
('In the children''s book series, where is Paddington Bear originally from?', 'India', 'Iceland', 'Canada', 'Peru', 'D', 'entertainment', 'pro'),
('In the Harry Potter universe, what is Cornelius Fudge''s middle name?', 'James', 'Harold', 'Christopher', 'Oswald', 'D', 'entertainment', 'legend'),
('Under what pseudonym did Stephen King publish five novels between 1977 and 1984?', 'J. D. Robb', 'Mark Twain', 'Lewis Carroll', 'Richard Bachman', 'D', 'entertainment', 'rookie'),
('Who is the author of the series "Malazan Book of the Fallen"?', 'Ian Cameron Esslemont', 'George R. R. Martin', 'J. R. R. Tolkien', 'Steven Erikson', 'D', 'entertainment', 'pro'),
('This play is generally considered to be the most adaptable of Shakespeare''s works, and follows two "star-crossed lovers".', 'Hamlet', 'The Tempest', 'King Lear', 'Romeo and Juliet', 'D', 'entertainment', 'rookie'),
('Who wrote "Harry Potter"?', 'J.R.R. Tolkien', 'Terry Pratchett', 'Daniel Radcliffe', 'J.K. Rowling', 'D', 'entertainment', 'rookie'),
('According to Bram Stoker''s novel, in which British coastal town did Dracula come ashore?', 'Scarborough', 'Brighton', 'Portsmouth', 'Whitby', 'D', 'entertainment', 'legend'),
('The title of Adolf Hitler''s autobiography "Mein Kampf" is what when translated to English?', 'My Hatred', 'My Sadness', 'My Desire', 'My Struggle', 'D', 'entertainment', 'pro'),
('"Green Eggs And Ham" is a book by which author?', 'Beatrix Potter', 'Roald Dahl', 'A.A. Milne', 'Dr. Seuss', 'D', 'entertainment', 'rookie'),
('In The Lies Of Locke Lamora, what does "Lamora" mean in Throne Therin?', 'Thievery', 'Justice', 'Chaos', 'Shadow', 'D', 'entertainment', 'legend'),
('In the Beatrix Potter books, what type of animal is Tommy Brock?', 'Fox', 'Frog', 'Rabbit', 'Badger', 'D', 'entertainment', 'legend'),
('How many Harry Potter books are there?', '8', '5', '6', '7', 'D', 'entertainment', 'rookie'),
('What is the title of the first Sherlock Holmes book by Arthur Conan Doyle?', 'The Sign of the Four', 'A Case of Identity', 'The Doings of Raffles Haw', 'A Study in Scarlet', 'D', 'entertainment', 'rookie'),
('What was the name of the Mysterious Island, in Jules Verne''s "The Mysterious Island"?', 'Vulcania Island', 'Prometheus Island', 'Neptune Island', 'Lincoln Island', 'D', 'entertainment', 'pro'),

-- FILM (50 questions)
('Who plays the character of Po in the Kung Fu Panda movies?', 'Mirana Jonnes', 'McConahey Ramses', 'Jim Petersson', 'Jack Black', 'D', 'entertainment', 'rookie'),
('In the 2010 Nightmare on Elm Street reboot, who played Freddy Kruger?', 'Tyler Mane', 'Derek Mears', 'Gunnar Hansen', 'Jackie Earle Haley', 'D', 'entertainment', 'pro'),
('What is the birth name of Michael Keaton?', 'Michael Fox', 'Michael Richards', 'Michael Kane', 'Michael Douglas', 'D', 'entertainment', 'pro'),
('According to the Star Wars lore, what is Han Solo''s home planet?', 'Tatooine', 'Naboo', 'Coruscant', 'Corellia', 'D', 'entertainment', 'pro'),
('Which of the following films was directed by Ivan Reitman, written by Gary Ross, featured Kevin Kline, and was released in 1993?', 'John', 'Will', 'Carl', 'Dave', 'D', 'entertainment', 'legend'),
('What was the first superhero film James Gunn was involved with?', 'Super', 'Guardians of the Galaxy', 'Brightburn', 'The Specials', 'D', 'entertainment', 'legend'),
('Darth Vader''s famous reveal to Luke is iconic. But which of these is the right one?', '"Luke, I am your father."', '"You''re wrong. I am your father."', '"The truth is that I am your father."', '"No. I am your father."', 'D', 'entertainment', 'pro'),
('Which one of these films are shot entirely in one-take?', 'Good Will Hunting', 'Birdman', 'Schindler''s List', 'Russian Ark', 'D', 'entertainment', 'pro'),
('Actress Susan Sarandon caught pneumonia during filming of which movie?', 'Thelma and Louise', 'Dead Man Walking', 'Enchanted', 'The Rocky Horror Picture Show', 'D', 'entertainment', 'pro'),
('What is the species of the "Predator" in the 1987 movie "Predator"?', 'Xenomorph', 'Praetorian', 'Phocrex', 'Yautja', 'D', 'entertainment', 'legend'),
('What superhero has been played in film by actors Michael Keaton, Val Kilmer, George Clooney and Christian Bale?', 'Superman', 'Iron Man', 'Spiderman', 'Batman', 'D', 'entertainment', 'rookie'),
('Which movie contains the quote, "Say hello to my little friend!"?', 'Reservoir Dogs', 'Heat', 'Goodfellas', 'Scarface', 'D', 'entertainment', 'rookie'),
('Which actor auditioned for the role of Luke Skywalker?', 'Christopher Lambert', 'Laurence Fishburne', 'James Remar', 'Kurt Russell', 'D', 'entertainment', 'pro'),
('In Finding Nemo, what was the name of Nemo''s mom?', 'Sandy', 'Pearl', 'Shelly', 'Coral', 'D', 'entertainment', 'pro'),
('In the Mad Max franchise, what type of car is the Pursuit Special driven by Max?', 'Holden Monaro', 'Chrysler Valiant Charger', 'Pontiac Firebird', 'Ford Falcon', 'D', 'entertainment', 'pro'),
('Who played Thanos in Avengers: Infinity War and Avengers: End Game?', 'Tom Hiddleston', 'Adam Sandler', 'Sean Gunn', 'Josh Brolin', 'D', 'entertainment', 'rookie'),
('Which was the first of Alfred Hitchcock''s movies to be filmed in colour?', 'Psycho', 'Vertigo', 'Rebecca', 'Rope', 'D', 'entertainment', 'legend'),
('Which boxer was famous for striking the gong in the introduction to J. Arthur Rank films?', 'Freddie Mills', 'Terry Spinks', 'Don Cockell', 'Bombardier Billy Wells', 'D', 'entertainment', 'legend'),
('When was the movie ''Con Air'' released?', '1985', '1999', '1990', '1997', 'D', 'entertainment', 'rookie'),
('What was the first movie to ever use a Wilhelm Scream?', 'Treasure of the Sierra Madre', 'The Charge at Feather River', 'Indiana Jones', 'Distant Drums', 'D', 'entertainment', 'legend'),
('What is Lilo''s last name from Lilo and Stitch?', 'Anoaʻi', 'Kealoha', 'Kuʻulei', 'Pelekai', 'D', 'entertainment', 'pro'),
('Which of these Disney classics was released in 1970?', 'One Hundred and One Dalmatians', 'The Fox and the Hound', 'The Little Mermaid', 'The Aristocats', 'D', 'entertainment', 'pro'),
('After India, which country produces the second most movies per year?', 'United States', 'China', 'France', 'Nigeria', 'D', 'entertainment', 'pro'),
('At the end of the 2001 film "Rat Race", whose concert do the contestants crash?', 'Bowling for Soup', 'Sum 41', 'Linkin Park', 'Smash Mouth', 'D', 'entertainment', 'rookie'),
('In the movie "Scream" who is Ghost Face?', 'Dewey Riley', 'Sidney Prescott', 'Archie Prescott and Philip Marv', 'Billy Loomis and Stu Macher', 'D', 'entertainment', 'legend'),
('Who plays "Bruce Wayne" in the 2008 movie "The Dark Knight"?', 'Michael Caine', 'Ron Dean', 'Heath Ledger', 'Christian Bale', 'D', 'entertainment', 'pro'),
('Which actor and martial artist starred as Colonel Guile in the 1994 action film adaptation of Street Fighter?', 'Chuck Norris', 'Steven Seagal', 'Scott Adkins', 'Jean-Claude Van Damme', 'D', 'entertainment', 'pro'),
('What is the birth name of Michael Caine?', 'Morris Coleman', 'Carl Myers', 'Martin Michaels', 'Maurice Micklewhite', 'D', 'entertainment', 'pro'),
('Which movie of film director Stanley Kubrick is known to be an adaptation of a Stephen King novel?', '2001: A Space Odyssey', ' Dr. Strangelove ', 'Eyes Wide Shut', 'The Shining', 'D', 'entertainment', 'pro'),
('Which singer is portrayed by Bruce Campbell in the 2002 film ''Bubba Ho-Tep''?', 'Johnny Cash', 'Hank Williams, Sr.', 'Buddy Holly', 'Elvis Presley', 'D', 'entertainment', 'legend'),
('What was Humphrey Bogart''s middle name?', 'DeWinter', 'Steven', 'Bryce', 'DeForest', 'D', 'entertainment', 'legend'),
('In Youtuber Jerma985''s 2014 film "Rat Movie: Mystery of the Mayan Treasure," who is the man who tries to steal the Mayan Treasure?', 'Gabe "The Glue Man" Degrossi', 'Bootleg Duck Dynasty Byeah Batman', 'Demon Lord Zeraxos', 'Dick Dastardly Richards', 'D', 'entertainment', 'legend'),
('Which actor plays Obi-Wan Kenobi in Star Wars Episodes I-III?', 'Alec Guinness', 'Hayden Christensen', 'Liam Neeson', 'Ewan McGregor', 'D', 'entertainment', 'rookie'),
('Who directed the 1973 film "American Graffiti"?', 'Ron Howard', 'Francis Ford Coppola', 'Steven Spielberg', 'George Lucas', 'D', 'entertainment', 'pro'),
('Which famous singer was portrayed by actor Kevin Spacey in the 2004 biographical film "Beyond the Sea"?', 'Louis Armstrong', 'Frank Sinatra', 'Dean Martin', 'Bobby Darin', 'D', 'entertainment', 'pro'),
('Which actor plays the character "Tommy Jarvis" in "Friday the 13th: The Final Chapter" (1984)?', 'Macaulay Culkin', 'Mel Gibson', 'Mark Hamill', 'Corey Feldman', 'D', 'entertainment', 'pro'),
('This movie contains the quote, "What we''ve got here is a failure to communicate."', 'Bonnie and Clyde', 'The Graduate', 'In the Heat of the Night', 'Cool Hand Luke', 'D', 'entertainment', 'pro'),
('What year did the movie "Napoleon Dynamite" come out?', '2002', '2003', '2005', '2004', 'D', 'entertainment', 'pro'),
('About how much money did it cost for Tommy Wiseau to make his masterpiece "The Room" (2003)?', '$20,000', '$1 Million', '$10 Million', '$6 Million', 'D', 'entertainment', 'pro'),
('What mutated animals act as monsters in the movie ''Night of the Lepus''?', 'Dogs', 'Rats', 'Bats', 'Rabbits', 'D', 'entertainment', 'pro'),
('Which actress portrayed Dr. Grace Augustine in the James Cameron movie "Avatar"?', 'Jessica Chastain', 'Melissa Beckett', 'Alyssa Monroe ', 'Sigourney Weaver', 'D', 'entertainment', 'legend'),
('Which DC superhero was NOT included in the 2017 movie "Justice League"?', 'Batman', 'Cyborg', 'Wonder Woman', 'Green Arrow', 'D', 'entertainment', 'pro'),
('What was the first James Bond film?', 'Goldfinger', 'From Russia With Love', 'Thunderball', 'Dr. No', 'D', 'entertainment', 'rookie'),
('What year did the James Cameron film "Titanic" come out in theaters?', '1996', '1998', '1999', '1997', 'D', 'entertainment', 'pro'),
('Which of the following movies was not based on a book?', 'The Godfather', 'Forrest Gump', 'Jurassic Park', 'Citizen Kane', 'D', 'entertainment', 'pro'),
('Which movie released in 2016 features Superman and Batman fighting?', 'Batman v Superman: Superapocalypse', 'Batman v Superman: Black of Knight', 'Batman v Superman: Knightfall', 'Batman v Superman: Dawn of Justice', 'D', 'entertainment', 'rookie'),
('In the 1979 British film "Quadrophenia" what is the name of the seaside city the mods are visiting?', 'Eastbourne', 'Mousehole', 'Bridlington', 'Brighton', 'D', 'entertainment', 'pro'),
('When does "Rogue One: A Star Wars Story" take place chronologically in the series?', 'After Episode 6', 'Before Episode 1', 'Between Episode 4 and 5', 'Between Episode 3 and 4', 'D', 'entertainment', 'rookie'),
('What was Marilyn Monroe`s character''s first name in the film "Some Like It Hot"?', 'Honey', 'Caramel', 'Candy', 'Sugar', 'D', 'entertainment', 'pro'),
('In Big Hero 6, what fictional city is the Big Hero 6 from?', 'San Tokyo', 'Tokysisco', 'Sankyo', 'San Fransokyo', 'D', 'entertainment', 'rookie');
