-- IQ Arena - Science & Tech Questions (Fixed for actual schema)
-- 50 questions with easy/hard difficulty

INSERT INTO trivia_questions (category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, is_free_play) VALUES

-- Easy Questions (25)
('science_tech', 'easy', 'What does CPU stand for?', 'Central Processing Unit', 'Computer Personal Unit', 'Central Program Unit', 'Core Processing Unit', 'A', false),
('science_tech', 'easy', 'What is H2O commonly known as?', 'Water', 'Hydrogen', 'Oxygen', 'Peroxide', 'A', false),
('science_tech', 'easy', 'How many planets are in our solar system?', 'Seven', 'Eight', 'Nine', 'Ten', 'B', false),
('science_tech', 'easy', 'What is the symbol for potassium?', 'P', 'K', 'Po', 'Pt', 'B', false),
('science_tech', 'easy', 'Which gas do plants absorb from the atmosphere?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen', 'B', false),
('science_tech', 'easy', 'What is the largest planet in our solar system?', 'Saturn', 'Jupiter', 'Neptune', 'Earth', 'B', false),
('science_tech', 'easy', 'What does DNA stand for?', 'Deoxyribonucleic Acid', 'Dual Nuclear Acid', 'Dynamic Nuclear Acid', 'Digital Nuclear Acid', 'A', false),
('science_tech', 'easy', 'Which planet is known as the Red Planet?', 'Venus', 'Mars', 'Mercury', 'Jupiter', 'B', false),
('science_tech', 'easy', 'What is the speed of light?', '150,000 km/s', '299,792 km/s', '500,000 km/s', '1,000,000 km/s', 'B', false),
('science_tech', 'easy', 'What does USB stand for?', 'Universal Serial Bus', 'United System Bus', 'Universal System Board', 'United Serial Board', 'A', false),
('science_tech', 'easy', 'Which element is the most abundant in the universe?', 'Oxygen', 'Hydrogen', 'Carbon', 'Helium', 'B', false),
('science_tech', 'easy', 'What is the boiling point of water in Fahrenheit?', '100°F', '212°F', '180°F', '200°F', 'B', false),
('science_tech', 'easy', 'What is the name of Earth''s natural satellite?', 'Luna', 'Moon', 'Satellite', 'Titan', 'B', false),
('science_tech', 'easy', 'Which scientist is famous for E=mc²?', 'Isaac Newton', 'Albert Einstein', 'Galileo', 'Tesla', 'B', false),
('science_tech', 'easy', 'What type of animal is a dolphin?', 'Fish', 'Mammal', 'Reptile', 'Amphibian', 'B', false),
('science_tech', 'easy', 'How many bones are in the human body?', '198', '206', '214', '250', 'B', false),
('science_tech', 'easy', 'What is the chemical formula for table salt?', 'NaCl', 'HCl', 'KCl', 'H2O', 'A', false),
('science_tech', 'easy', 'Which organ pumps blood through the body?', 'Liver', 'Heart', 'Lungs', 'Kidney', 'B', false),
('science_tech', 'easy', 'What does WWW stand for?', 'World Wide Web', 'Wide World Web', 'Web Wide World', 'World Web Wide', 'A', false),
('science_tech', 'easy', 'Which planet has rings around it?', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'B', false),
('science_tech', 'easy', 'What is the powerhouse of the cell?', 'Nucleus', 'Mitochondria', 'Ribosome', 'Chloroplast', 'B', false),
('science_tech', 'easy', 'What is the most abundant element in Earth''s crust?', 'Silicon', 'Oxygen', 'Iron', 'Aluminum', 'B', false),
('science_tech', 'easy', 'Who invented the first practical telephone?', 'Thomas Edison', 'Alexander Graham Bell', 'Nikola Tesla', 'Guglielmo Marconi', 'B', false),
('science_tech', 'easy', 'What is the study of fungi called?', 'Biology', 'Mycology', 'Botany', 'Zoology', 'B', false),
('science_tech', 'easy', 'What is the pH of pure water?', '5', '7', '9', '10', 'B', false),

-- Hard Questions (25)
('science_tech', 'hard', 'Which programming language is known as the "mother of all languages"?', 'FORTRAN', 'C', 'Assembly', 'COBOL', 'B', false),
('science_tech', 'hard', 'What is the name of the largest moon of Saturn?', 'Europa', 'Titan', 'Io', 'Ganymede', 'B', false),
('science_tech', 'hard', 'How many chromosomes do humans have?', '23', '46', '48', '44', 'B', false),
('science_tech', 'hard', 'What is the SI unit of force?', 'Joule', 'Newton', 'Watt', 'Pascal', 'B', false),
('science_tech', 'hard', 'Which cloud computing company created AWS?', 'Microsoft', 'Amazon', 'Google', 'IBM', 'B', false),
('science_tech', 'hard', 'What is the atomic number of carbon?', '4', '6', '8', '12', 'B', false),
('science_tech', 'hard', 'What does GUI stand for in computing?', 'General User Interface', 'Graphical User Interface', 'Global User Interface', 'Generic User Input', 'B', false),
('science_tech', 'hard', 'Which particle has no electric charge?', 'Electron', 'Neutron', 'Proton', 'Positron', 'B', false),
('science_tech', 'hard', 'What is the study of earthquakes called?', 'Geology', 'Seismology', 'Meteorology', 'Volcanology', 'B', false),
('science_tech', 'hard', 'Which planet rotates on its side?', 'Venus', 'Uranus', 'Neptune', 'Mars', 'B', false),
('science_tech', 'hard', 'What is the name of the first artificial satellite?', 'Explorer 1', 'Sputnik 1', 'Vanguard 1', 'Apollo 1', 'B', false),
('science_tech', 'hard', 'How many teeth does an adult human have?', '28', '32', '30', '34', 'B', false),
('science_tech', 'hard', 'What is the chemical symbol for silver?', 'Si', 'Ag', 'Au', 'S', 'B', false),
('science_tech', 'hard', 'Which gas makes up most of Earth''s atmosphere?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Argon', 'B', false),
('science_tech', 'hard', 'What is the smallest unit of life?', 'Atom', 'Cell', 'Molecule', 'Organ', 'B', false),
('science_tech', 'hard', 'What is Planck''s constant approximately?', '3.14×10⁻³⁴ J·s', '6.626×10⁻³⁴ J·s', '9.81×10⁻³⁴ J·s', '1.602×10⁻³⁴ J·s', 'B', false),
('science_tech', 'hard', 'What is the name of the theorem that relates energy and time uncertainty?', 'Schrödinger Equation', 'Heisenberg Uncertainty Principle', 'Pauli Exclusion', 'Fermat''s Theorem', 'B', false),
('science_tech', 'hard', 'Which element has the highest electronegativity?', 'Oxygen', 'Fluorine', 'Chlorine', 'Nitrogen', 'B', false),
('science_tech', 'hard', 'What is the Schwarzschild radius of a black hole with 1 solar mass?', '~1 km', '~3 km', '~10 km', '~100 km', 'B', false),
('science_tech', 'hard', 'What is the fine structure constant approximately?', '1/100', '1/137', '1/200', '1/50', 'B', false),
('science_tech', 'hard', 'Which programming paradigm uses lambda calculus?', 'Object-Oriented', 'Functional Programming', 'Procedural', 'Declarative', 'B', false),
('science_tech', 'hard', 'What is the half-life of Uranium-235 in years?', '100 million', '704 million', '1 billion', '5 billion', 'B', false),
('science_tech', 'hard', 'What is the name of the first quantum computer?', 'IBM Q', 'D-Wave One', 'Sycamore', 'Quantum Alpha', 'B', false),
('science_tech', 'hard', 'What is the Chandrasekhar limit in solar masses?', '1.0', '1.4', '2.0', '0.8', 'B', false),
('science_tech', 'hard', 'Which mathematician proved Fermat''s Last Theorem?', 'Pierre de Fermat', 'Andrew Wiles', 'Leonhard Euler', 'Carl Gauss', 'B', false);
