-- IQ Arena - General Knowledge Questions (Fixed for actual schema)
-- 50 questions with easy/hard difficulty matching the trivia_questions table structure

INSERT INTO trivia_questions (category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, is_free_play) VALUES

-- Easy Questions (25)
('general_knowledge', 'easy', 'What is the largest ocean on Earth?', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'A', false),
('general_knowledge', 'easy', 'How many sides does a hexagon have?', 'Five', 'Six', 'Seven', 'Eight', 'B', false),
('general_knowledge', 'easy', 'What is the capital of Australia?', 'Sydney', 'Melbourne', 'Canberra', 'Brisbane', 'C', false),
('general_knowledge', 'easy', 'Which planet is closest to the Sun?', 'Venus', 'Mercury', 'Mars', 'Earth', 'B', false),
('general_knowledge', 'easy', 'What color is a sapphire?', 'Red', 'Green', 'Blue', 'Yellow', 'C', false),
('general_knowledge', 'easy', 'How many hours are in a day?', '12', '24', '36', '48', 'B', false),
('general_knowledge', 'easy', 'What is the largest continent by land area?', 'Africa', 'Asia', 'North America', 'Europe', 'B', false),
('general_knowledge', 'easy', 'What is the freezing point of water in Celsius?', '0', '32', '100', '-32', 'A', false),
('general_knowledge', 'easy', 'Which animal is known as the King of the Jungle?', 'Tiger', 'Lion', 'Elephant', 'Bear', 'B', false),
('general_knowledge', 'easy', 'What is the smallest prime number?', '1', '2', '3', '5', 'B', false),
('general_knowledge', 'easy', 'How many legs does a spider have?', 'Six', 'Eight', 'Ten', 'Four', 'B', false),
('general_knowledge', 'easy', 'What is the main ingredient in guacamole?', 'Tomato', 'Avocado', 'Pepper', 'Onion', 'B', false),
('general_knowledge', 'easy', 'Which ocean is the Bermuda Triangle located in?', 'Pacific', 'Atlantic', 'Indian', 'Arctic', 'B', false),
('general_knowledge', 'easy', 'What is the tallest mammal on Earth?', 'Elephant', 'Giraffe', 'Whale', 'Camel', 'B', false),
('general_knowledge', 'easy', 'How many strings does a standard guitar have?', 'Four', 'Five', 'Six', 'Seven', 'C', false),
('general_knowledge', 'easy', 'What is the chemical symbol for gold?', 'Ag', 'Au', 'Fe', 'Go', 'B', false),
('general_knowledge', 'easy', 'Which fruit is dried to make raisins?', 'Plums', 'Grapes', 'Apricots', 'Figs', 'B', false),
('general_knowledge', 'easy', 'What is the largest island in the world?', 'Iceland', 'Greenland', 'Madagascar', 'Borneo', 'B', false),
('general_knowledge', 'easy', 'How many teeth does an adult human typically have?', '28', '30', '32', '34', 'C', false),
('general_knowledge', 'easy', 'What is the smallest country in the world?', 'Monaco', 'Vatican City', 'San Marino', 'Liechtenstein', 'B', false),
('general_knowledge', 'easy', 'What is the most abundant gas in Earth''s atmosphere?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Argon', 'B', false),
('general_knowledge', 'easy', 'Which phobia is the fear of heights?', 'Claustrophobia', 'Acrophobia', 'Arachnophobia', 'Agoraphobia', 'B', false),
('general_knowledge', 'easy', 'What is the currency of Japan?', 'Yuan', 'Yen', 'Won', 'Rupee', 'B', false),
('general_knowledge', 'easy', 'Which planet has the most moons?', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'B', false),
('general_knowledge', 'easy', 'What is the hardest natural substance on Earth?', 'Gold', 'Diamond', 'Platinum', 'Titanium', 'B', false),

-- Hard Questions (25)
('general_knowledge', 'hard', 'In which year did World War II end?', '1943', '1944', '1945', '1946', 'C', false),
('general_knowledge', 'hard', 'What is the speed of light in km/s?', '150,000', '300,000', '500,000', '1,000,000', 'B', false),
('general_knowledge', 'hard', 'Which country has the longest coastline?', 'Russia', 'Canada', 'Australia', 'Indonesia', 'B', false),
('general_knowledge', 'hard', 'What is the smallest bone in the human body?', 'Tibia', 'Stapes', 'Femur', 'Radius', 'B', false),
('general_knowledge', 'hard', 'Which element has the atomic number 1?', 'Helium', 'Hydrogen', 'Oxygen', 'Carbon', 'B', false),
('general_knowledge', 'hard', 'What is the largest desert in the world?', 'Sahara', 'Antarctica', 'Gobi', 'Arabian', 'B', false),
('general_knowledge', 'hard', 'How many time zones does Russia have?', '7', '9', '11', '13', 'C', false),
('general_knowledge', 'hard', 'What is the most spoken native language in the world?', 'English', 'Spanish', 'Mandarin Chinese', 'Hindi', 'C', false),
('general_knowledge', 'hard', 'Which blood type is known as the universal donor?', 'AB Positive', 'O Negative', 'A Positive', 'B Negative', 'B', false),
('general_knowledge', 'hard', 'What is the SI unit of electric current?', 'Volt', 'Watt', 'Ampere', 'Ohm', 'C', false),
('general_knowledge', 'hard', 'Which country invented paper?', 'Egypt', 'India', 'China', 'Greece', 'C', false),
('general_knowledge', 'hard', 'What percentage of Earth''s surface is covered by water?', '60%', '71%', '80%', '50%', 'B', false),
('general_knowledge', 'hard', 'Which organ in the human body produces insulin?', 'Liver', 'Kidney', 'Pancreas', 'Spleen', 'C', false),
('general_knowledge', 'hard', 'What is the rarest blood type?', 'O Negative', 'B Negative', 'AB Negative', 'A Negative', 'C', false),
('general_knowledge', 'hard', 'How many bones are in the adult human body?', '198', '206', '214', '220', 'B', false),
('general_knowledge', 'hard', 'What is the half-life of Carbon-14 in years?', '3,500', '5,730', '10,000', '15,000', 'B', false),
('general_knowledge', 'hard', 'Which country has won the most Nobel Prizes?', 'United Kingdom', 'Germany', 'United States', 'France', 'C', false),
('general_knowledge', 'hard', 'What is the Mohs hardness of talc?', '1', '2', '3', '5', 'A', false),
('general_knowledge', 'hard', 'What is the most densely populated country in the world?', 'Singapore', 'Monaco', 'Vatican City', 'Malta', 'B', false),
('general_knowledge', 'hard', 'Which amino acid is represented by the single letter K?', 'Leucine', 'Lysine', 'Valine', 'Arginine', 'B', false),
('general_knowledge', 'hard', 'What is the Avogadro constant approximately?', '3.14×10²³', '6.022×10²³', '9.81×10²³', '1.602×10²³', 'B', false),
('general_knowledge', 'hard', 'Which country has the highest GDP per capita?', 'Switzerland', 'Luxembourg', 'Qatar', 'Singapore', 'B', false),
('general_knowledge', 'hard', 'What is the largest known prime number as of 2024 (digits)?', '10 million', '25 million', '41 million', '100 million', 'C', false),
('general_knowledge', 'hard', 'Which element has the highest melting point?', 'Carbon', 'Tungsten', 'Titanium', 'Iron', 'B', false),
('general_knowledge', 'hard', 'What is the speed of sound in air at sea level (m/s)?', '300', '343', '400', '500', 'B', false);
