-- IQ Arena - History & Geography Questions (Fixed for actual schema)
-- 50 questions with easy/hard difficulty

INSERT INTO trivia_questions (category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, is_free_play) VALUES

-- Easy Questions (25)
('history_geography', 'easy', 'What is the capital of Italy?', 'Milan', 'Rome', 'Venice', 'Florence', 'B', false),
('history_geography', 'easy', 'Which ocean is the largest?', 'Atlantic', 'Pacific', 'Indian', 'Arctic', 'B', false),
('history_geography', 'easy', 'Who was the first President of the United States?', 'Thomas Jefferson', 'George Washington', 'John Adams', 'Benjamin Franklin', 'B', false),
('history_geography', 'easy', 'What is the longest river in the world?', 'Amazon', 'Nile', 'Mississippi', 'Yangtze', 'B', false),
('history_geography', 'easy', 'Which country is known as the Land of the Rising Sun?', 'China', 'Japan', 'Korea', 'Thailand', 'B', false),
('history_geography', 'easy', 'What year did World War I begin?', '1912', '1914', '1916', '1918', 'B', false),
('history_geography', 'easy', 'Which continent is the Sahara Desert located on?', 'Asia', 'Africa', 'Australia', 'South America', 'B', false),
('history_geography', 'easy', 'What is the capital of Spain?', 'Barcelona', 'Madrid', 'Seville', 'Valencia', 'B', false),
('history_geography', 'easy', 'Who built the pyramids?', 'Romans', 'Ancient Egyptians', 'Greeks', 'Babylonians', 'B', false),
('history_geography', 'easy', 'Which country has the most population?', 'India', 'China', 'USA', 'Indonesia', 'B', false),
('history_geography', 'easy', 'What is the smallest country in the world?', 'Monaco', 'Vatican City', 'San Marino', 'Liechtenstein', 'B', false),
('history_geography', 'easy', 'Which city is the Eiffel Tower located in?', 'London', 'Paris', 'Rome', 'Berlin', 'B', false),
('history_geography', 'easy', 'What year did the Titanic sink?', '1910', '1912', '1914', '1916', 'B', false),
('history_geography', 'easy', 'Which country is the Great Wall located in?', 'Japan', 'China', 'Korea', 'Mongolia', 'B', false),
('history_geography', 'easy', 'What is the capital of Canada?', 'Toronto', 'Montreal', 'Ottawa', 'Vancouver', 'C', false),
('history_geography', 'easy', 'Which empire was ruled by Julius Caesar?', 'Greek Empire', 'Roman Empire', 'Persian Empire', 'Ottoman Empire', 'B', false),
('history_geography', 'easy', 'What is the largest desert in the world?', 'Sahara', 'Antarctica', 'Gobi', 'Arabian', 'B', false),
('history_geography', 'easy', 'Which river flows through Egypt?', 'Tigris', 'Nile', 'Euphrates', 'Jordan', 'B', false),
('history_geography', 'easy', 'What year did the Berlin Wall fall?', '1985', '1989', '1991', '1987', 'B', false),
('history_geography', 'easy', 'Which country gifted the Statue of Liberty to the USA?', 'England', 'France', 'Spain', 'Italy', 'B', false),
('history_geography', 'easy', 'Who was the first emperor of Rome?', 'Julius Caesar', 'Augustus', 'Nero', 'Caligula', 'B', false),
('history_geography', 'easy', 'What is the capital of Kazakhstan?', 'Almaty', 'Astana', 'Bishkek', 'Tashkent', 'B', false),
('history_geography', 'easy', 'In which year did Christopher Columbus first reach the Americas?', '1490', '1492', '1494', '1500', 'B', false),
('history_geography', 'easy', 'Which battle is considered the turning point of WWII in Europe?', 'D-Day', 'Stalingrad', 'Battle of Britain', 'El Alamein', 'B', false),
('history_geography', 'easy', 'What is the deepest ocean trench?', 'Puerto Rico Trench', 'Mariana Trench', 'Java Trench', 'Philippine Trench', 'B', false),

-- Hard Questions (25)
('history_geography', 'hard', 'Which empire was Genghis Khan the founder of?', 'Ottoman Empire', 'Mongol Empire', 'Persian Empire', 'Chinese Empire', 'B', false),
('history_geography', 'hard', 'What is the longest mountain range in the world?', 'Himalayas', 'Andes', 'Rockies', 'Alps', 'B', false),
('history_geography', 'hard', 'Which country has the most UNESCO World Heritage Sites?', 'China', 'Italy', 'Spain', 'France', 'B', false),
('history_geography', 'hard', 'What year did the Russian Revolution occur?', '1914', '1917', '1920', '1922', 'B', false),
('history_geography', 'hard', 'Which city was formerly known as Constantinople?', 'Athens', 'Istanbul', 'Alexandria', 'Cairo', 'B', false),
('history_geography', 'hard', 'What is the highest mountain in Africa?', 'Kenya', 'Kilimanjaro', 'Atlas', 'Rwenzori', 'B', false),
('history_geography', 'hard', 'Which treaty ended World War I?', 'Treaty of Paris', 'Treaty of Versailles', 'Treaty of Ghent', 'Treaty of Westphalia', 'B', false),
('history_geography', 'hard', 'What is the capital of Mongolia?', 'Astana', 'Ulaanbaatar', 'Bishkek', 'Dushanbe', 'B', false),
('history_geography', 'hard', 'Which civilization built Machu Picchu?', 'Maya', 'Inca', 'Aztec', 'Olmec', 'B', false),
('history_geography', 'hard', 'What is the largest lake in the world by surface area?', 'Superior', 'Caspian Sea', 'Victoria', 'Huron', 'B', false),
('history_geography', 'hard', 'Who was the longest-reigning British monarch?', 'Victoria', 'Elizabeth II', 'George III', 'Henry VIII', 'B', false),
('history_geography', 'hard', 'Which city is built on seven hills?', 'Athens', 'Rome', 'Jerusalem', 'Lisbon', 'B', false),
('history_geography', 'hard', 'What year did India gain independence from Britain?', '1945', '1947', '1950', '1952', 'B', false),
('history_geography', 'hard', 'Which country has the most active volcanoes?', 'Japan', 'Indonesia', 'Philippines', 'USA', 'B', false),
('history_geography', 'hard', 'What is the oldest continuously inhabited city?', 'Jericho', 'Damascus', 'Athens', 'Rome', 'B', false),
('history_geography', 'hard', 'What year was the Battle of Hastings?', '1056', '1066', '1076', '1086', 'B', false),
('history_geography', 'hard', 'Which empire had the largest contiguous land area?', 'Roman Empire', 'Mongol Empire', 'British Empire', 'Russian Empire', 'B', false),
('history_geography', 'hard', 'What is the exact latitude of the Equator?', '0 degrees', '1 degree', '5 degrees', '10 degrees', 'A', false),
('history_geography', 'hard', 'Which treaty divided the New World between Spain and Portugal?', 'Treaty of Madrid', 'Treaty of Tordesillas', 'Treaty of Zaragoza', 'Treaty of Utrecht', 'B', false),
('history_geography', 'hard', 'What is the antipode of Madrid, Spain?', 'Australia', 'Near New Zealand', 'Argentina', 'Pacific Ocean', 'B', false),
('history_geography', 'hard', 'Which pharaoh built the Great Pyramid of Giza?', 'Ramses II', 'Khufu', 'Tutankhamun', 'Cleopatra', 'B', false),
('history_geography', 'hard', 'What year did the Byzantine Empire fall?', '1400', '1453', '1500', '1350', 'B', false),
('history_geography', 'hard', 'Which country has the most time zones?', 'Russia', 'France', 'USA', 'UK', 'B', false),
('history_geography', 'hard', 'What is the smallest independent state by area?', 'Monaco', 'Vatican City', 'San Marino', 'Nauru', 'B', false),
('history_geography', 'hard', 'Which city was the capital of the Inca Empire?', 'Lima', 'Cusco', 'Quito', 'Machu Picchu', 'B', false);
