-- Arts & Literature Questions - 50 questions

INSERT INTO trivia_questions (category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer) VALUES
-- Rookie Questions (20)
('arts', 'rookie', 'Who painted the Mona Lisa?', 'Picasso', 'Van Gogh', 'Da Vinci', 'Monet', 'C'),
('arts', 'rookie', 'Who wrote Romeo and Juliet?', 'Dickens', 'Shakespeare', 'Austen', 'Hemingway', 'B'),
('arts', 'rookie', 'What color do you get mixing blue and yellow?', 'Orange', 'Green', 'Purple', 'Brown', 'B'),
('arts', 'rookie', 'Who wrote Harry Potter?', 'Tolkien', 'Lewis', 'Rowling', 'Martin', 'C'),
('arts', 'rookie', 'What are the three primary colors?', 'RGB', 'RYB', 'CMY', 'RGY', 'B'),
('arts', 'rookie', 'Who painted Starry Night?', 'Picasso', 'Van Gogh', 'Monet', 'Renoir', 'B'),
('arts', 'rookie', 'Who wrote The Odyssey?', 'Virgil', 'Homer', 'Ovid', 'Sophocles', 'B'),
('arts', 'rookie', 'What is a haiku?', 'Novel', 'Song', 'Poem', 'Play', 'C'),
('arts', 'rookie', 'Who painted The Scream?', 'Van Gogh', 'Picasso', 'Munch', 'Dali', 'C'),
('arts', 'rookie', 'Who wrote The Great Gatsby?', 'Hemingway', 'Fitzgerald', 'Steinbeck', 'Faulkner', 'B'),
('arts', 'rookie', 'What instrument has 88 keys?', 'Organ', 'Piano', 'Keyboard', 'Harpsichord', 'B'),
('arts', 'rookie', 'Who wrote 1984?', 'Huxley', 'Orwell', 'Bradbury', 'Asimov', 'B'),
('arts', 'rookie', 'What color do you get mixing red and blue?', 'Orange', 'Green', 'Purple', 'Brown', 'C'),
('arts', 'rookie', 'Who painted the ceiling of the Sistine Chapel?', 'Da Vinci', 'Raphael', 'Michelangelo', 'Botticelli', 'C'),
('arts', 'rookie', 'Who wrote Pride and Prejudice?', 'Bronte', 'Austen', 'Eliot', 'Shelley', 'B'),
('arts', 'rookie', 'What is the lowest male singing voice?', 'Tenor', 'Baritone', 'Bass', 'Alto', 'C'),
('arts', 'rookie', 'Who painted Girl with a Pearl Earring?', 'Rembrandt', 'Vermeer', 'Rubens', 'Hals', 'B'),
('arts', 'rookie', 'Who wrote To Kill a Mockingbird?', 'Steinbeck', 'Lee', 'Morrison', 'Walker', 'B'),
('arts', 'rookie', 'What is a sonnet?', 'Novel', 'Poem', 'Play', 'Song', 'B'),
('arts', 'rookie', 'Who painted The Last Supper?', 'Michelangelo', 'Raphael', 'Da Vinci', 'Botticelli', 'C'),

-- Pro Questions (20)
('arts', 'pro', 'Who wrote One Hundred Years of Solitude?', 'Borges', 'Garcia Marquez', 'Neruda', 'Fuentes', 'B'),
('arts', 'pro', 'What art movement was Picasso associated with?', 'Impressionism', 'Surrealism', 'Cubism', 'Expressionism', 'C'),
('arts', 'pro', 'Who composed The Four Seasons?', 'Bach', 'Mozart', 'Vivaldi', 'Handel', 'C'),
('arts', 'pro', 'Who wrote War and Peace?', 'Dostoevsky', 'Tolstoy', 'Chekhov', 'Pushkin', 'B'),
('arts', 'pro', 'What is the Sistine Madonnas other name?', 'Madonna of the Rocks', 'Madonna of the Chair', 'Madonna of San Sisto', 'Madonna del Prato', 'C'),
('arts', 'pro', 'Who painted The Birth of Venus?', 'Da Vinci', 'Michelangelo', 'Botticelli', 'Raphael', 'C'),
('arts', 'pro', 'Who wrote The Divine Comedy?', 'Petrarch', 'Boccaccio', 'Dante', 'Virgil', 'C'),
('arts', 'pro', 'What is the highest female singing voice?', 'Alto', 'Mezzo-soprano', 'Soprano', 'Contralto', 'C'),
('arts', 'pro', 'Who painted Guernica?', 'Dali', 'Miro', 'Picasso', 'Gris', 'C'),
('arts', 'pro', 'Who wrote Ulysses?', 'Yeats', 'Joyce', 'Wilde', 'Shaw', 'B'),
('arts', 'pro', 'How many symphonies did Beethoven compose?', '7', '8', '9', '10', 'C'),
('arts', 'pro', 'Who painted The Garden of Earthly Delights?', 'Van Eyck', 'Bosch', 'Bruegel', 'Memling', 'B'),
('arts', 'pro', 'Who wrote Crime and Punishment?', 'Tolstoy', 'Dostoevsky', 'Turgenev', 'Gogol', 'B'),
('arts', 'pro', 'What is the art of Japanese paper folding?', 'Ikebana', 'Origami', 'Bonsai', 'Sumi-e', 'B'),
('arts', 'pro', 'Who composed The Magic Flute?', 'Bach', 'Mozart', 'Beethoven', 'Haydn', 'B'),
('arts', 'pro', 'Who painted American Gothic?', 'Hopper', 'Wood', 'Wyeth', 'Rockwell', 'B'),
('arts', 'pro', 'Who wrote The Brothers Karamazov?', 'Tolstoy', 'Dostoevsky', 'Chekhov', 'Turgenev', 'B'),
('arts', 'pro', 'What period followed the Renaissance?', 'Gothic', 'Baroque', 'Rococo', 'Medieval', 'B'),
('arts', 'pro', 'Who painted The Night Watch?', 'Vermeer', 'Hals', 'Rembrandt', 'Rubens', 'C'),
('arts', 'pro', 'Who wrote The Metamorphosis?', 'Mann', 'Kafka', 'Hesse', 'Rilke', 'B'),

-- Legend Questions (10)
('arts', 'legend', 'Who painted The Arnolfini Portrait?', 'Van der Weyden', 'Van Eyck', 'Memling', 'Bosch', 'B'),
('arts', 'legend', 'Who wrote The Sound and the Fury?', 'Hemingway', 'Fitzgerald', 'Faulkner', 'Steinbeck', 'C'),
('arts', 'legend', 'What is the Goldberg Variations composer?', 'Handel', 'Bach', 'Vivaldi', 'Telemann', 'B'),
('arts', 'legend', 'Who painted Las Meninas?', 'El Greco', 'Goya', 'Velazquez', 'Murillo', 'C'),
('arts', 'legend', 'Who wrote In Search of Lost Time?', 'Gide', 'Proust', 'Camus', 'Sartre', 'B'),
('arts', 'legend', 'What year was the Rite of Spring premiered?', '1911', '1912', '1913', '1914', 'C'),
('arts', 'legend', 'Who painted The Sleeping Venus?', 'Titian', 'Giorgione', 'Tintoretto', 'Veronese', 'B'),
('arts', 'legend', 'Who wrote The Canterbury Tales?', 'Langland', 'Chaucer', 'Gower', 'Malory', 'B'),
('arts', 'legend', 'What is BWV in Bach catalog?', 'Bach Werk Verzeichnis', 'Baroque Work Volume', 'Bach Work Version', 'Baroque Werk Volume', 'A'),
('arts', 'legend', 'Who painted The Ambassadors?', 'Hilliard', 'Holbein', 'Hollar', 'Hogarth', 'B');
