-- Entertainment Questions - 50 questions

INSERT INTO trivia_questions (category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer) VALUES
-- Rookie Questions (20)
('entertainment', 'rookie', 'Who played Iron Man in the Marvel movies?', 'Chris Evans', 'Robert Downey Jr', 'Chris Hemsworth', 'Mark Ruffalo', 'B'),
('entertainment', 'rookie', 'What is the name of Harry Potters owl?', 'Errol', 'Hedwig', 'Pigwidgeon', 'Scabbers', 'B'),
('entertainment', 'rookie', 'What is the highest-grossing film of all time?', 'Titanic', 'Avatar', 'Endgame', 'Star Wars', 'B'),
('entertainment', 'rookie', 'Who is the lead singer of Queen?', 'Roger Taylor', 'Brian May', 'Freddie Mercury', 'John Deacon', 'C'),
('entertainment', 'rookie', 'What is Batmans real name?', 'Bruce Banner', 'Bruce Wayne', 'Clark Kent', 'Peter Parker', 'B'),
('entertainment', 'rookie', 'Who directed Titanic?', 'Spielberg', 'Cameron', 'Lucas', 'Scott', 'B'),
('entertainment', 'rookie', 'What is the name of the wizarding school in Harry Potter?', 'Beauxbatons', 'Durmstrang', 'Hogwarts', 'Ilvermorny', 'C'),
('entertainment', 'rookie', 'Who played Jack in Titanic?', 'Brad Pitt', 'Tom Cruise', 'Leonardo DiCaprio', 'Johnny Depp', 'C'),
('entertainment', 'rookie', 'What is the name of the lion in The Lion King?', 'Mufasa', 'Scar', 'Simba', 'Nala', 'C'),
('entertainment', 'rookie', 'Who sang "Thriller"?', 'Prince', 'Michael Jackson', 'Stevie Wonder', 'James Brown', 'B'),
('entertainment', 'rookie', 'What is Supermans weakness?', 'Silver', 'Iron', 'Kryptonite', 'Gold', 'C'),
('entertainment', 'rookie', 'Who directed Jurassic Park?', 'Lucas', 'Cameron', 'Spielberg', 'Scott', 'C'),
('entertainment', 'rookie', 'What is the name of the toy cowboy in Toy Story?', 'Buzz', 'Rex', 'Woody', 'Slinky', 'C'),
('entertainment', 'rookie', 'Who played Captain Jack Sparrow?', 'Orlando Bloom', 'Johnny Depp', 'Geoffrey Rush', 'Bill Nighy', 'B'),
('entertainment', 'rookie', 'What is the name of the wizarding bank in Harry Potter?', 'Gringotts', 'Flourish', 'Ollivanders', 'Weasleys', 'A'),
('entertainment', 'rookie', 'Who sang "Like a Virgin"?', 'Cher', 'Madonna', 'Cyndi Lauper', 'Whitney Houston', 'B'),
('entertainment', 'rookie', 'What is the name of Shreks donkey?', 'Eddie', 'Danny', 'Donkey', 'Jeffrey', 'C'),
('entertainment', 'rookie', 'Who directed Star Wars?', 'Spielberg', 'Lucas', 'Cameron', 'Kubrick', 'B'),
('entertainment', 'rookie', 'What is the name of the café in Friends?', 'Java Joe', 'Coffee House', 'Central Perk', 'The Grind', 'C'),
('entertainment', 'rookie', 'Who sang "Billie Jean"?', 'Prince', 'Michael Jackson', 'Lionel Richie', 'Stevie Wonder', 'B'),

-- Pro Questions (20)
('entertainment', 'pro', 'What year was the first Star Wars released?', '1975', '1976', '1977', '1978', 'C'),
('entertainment', 'pro', 'Who directed The Shawshank Redemption?', 'Fincher', 'Darabont', 'Reiner', 'Zemeckis', 'B'),
('entertainment', 'pro', 'What is the longest-running Broadway show?', 'Cats', 'Les Mis', 'Phantom', 'Chicago', 'C'),
('entertainment', 'pro', 'Who won the first season of American Idol?', 'Clay Aiken', 'Kelly Clarkson', 'Ruben Studdard', 'Carrie Underwood', 'B'),
('entertainment', 'pro', 'What year did The Beatles break up?', '1968', '1969', '1970', '1971', 'C'),
('entertainment', 'pro', 'Who directed Inception?', 'Cameron', 'Nolan', 'Fincher', 'Tarantino', 'B'),
('entertainment', 'pro', 'What is the highest-rated show on IMDB?', 'The Wire', 'Breaking Bad', 'Sopranos', 'Game of Thrones', 'B'),
('entertainment', 'pro', 'Who composed the score for Star Wars?', 'Zimmer', 'Williams', 'Horner', 'Morricone', 'B'),
('entertainment', 'pro', 'What year did Friends premiere?', '1992', '1993', '1994', '1995', 'C'),
('entertainment', 'pro', 'Who directed Pulp Fiction?', 'Scorsese', 'Tarantino', 'Coen Brothers', 'Fincher', 'B'),
('entertainment', 'pro', 'What is the best-selling album of all time?', 'Back in Black', 'Thriller', 'Dark Side', 'Rumours', 'B'),
('entertainment', 'pro', 'Who won the first Oscar for Best Actress?', 'Janet Gaynor', 'Mary Pickford', 'Norma Shearer', 'Marie Dressler', 'A'),
('entertainment', 'pro', 'What year was Netflix founded?', '1995', '1996', '1997', '1998', 'C'),
('entertainment', 'pro', 'Who directed The Godfather?', 'Scorsese', 'Coppola', 'De Palma', 'Friedkin', 'B'),
('entertainment', 'pro', 'What is the longest-running TV show?', 'Simpsons', 'Law & Order', 'Gunsmoke', 'Meet the Press', 'D'),
('entertainment', 'pro', 'Who sang "Bohemian Rhapsody"?', 'Led Zeppelin', 'Queen', 'Pink Floyd', 'The Who', 'B'),
('entertainment', 'pro', 'What year did MTV launch?', '1979', '1980', '1981', '1982', 'C'),
('entertainment', 'pro', 'Who directed Schindlers List?', 'Cameron', 'Spielberg', 'Scorsese', 'Zemeckis', 'B'),
('entertainment', 'pro', 'What is the highest-grossing R-rated film?', 'Joker', 'Deadpool', 'Matrix', 'Passion', 'A'),
('entertainment', 'pro', 'Who sang "Imagine"?', 'McCartney', 'Lennon', 'Harrison', 'Starr', 'B'),

-- Legend Questions (10)
('entertainment', 'legend', 'What year was Citizen Kane released?', '1939', '1940', '1941', '1942', 'C'),
('entertainment', 'legend', 'Who directed 2001: A Space Odyssey?', 'Hitchcock', 'Kubrick', 'Scott', 'Lucas', 'B'),
('entertainment', 'legend', 'What is the first feature-length animated film?', 'Fantasia', 'Pinocchio', 'Snow White', 'Bambi', 'C'),
('entertainment', 'legend', 'Who composed The Rite of Spring?', 'Debussy', 'Ravel', 'Stravinsky', 'Prokofiev', 'C'),
('entertainment', 'legend', 'What year was the first Academy Awards?', '1927', '1928', '1929', '1930', 'C'),
('entertainment', 'legend', 'Who directed The Seventh Seal?', 'Fellini', 'Bergman', 'Kurosawa', 'Antonioni', 'B'),
('entertainment', 'legend', 'What is the best-selling single of all time?', 'White Christmas', 'Candle in the Wind', 'Rock Around the Clock', 'I Want to Hold Your Hand', 'A'),
('entertainment', 'legend', 'Who won the most competitive Oscars?', 'Hepburn', 'Streep', 'Davis', 'Bergman', 'A'),
('entertainment', 'legend', 'What year was the first sound film?', '1925', '1926', '1927', '1928', 'C'),
('entertainment', 'legend', 'Who directed The 400 Blows?', 'Godard', 'Truffaut', 'Resnais', 'Chabrol', 'B');
