-- IQ Arena - Entertainment Questions (Fixed for actual schema)
-- 50 questions with easy/hard difficulty

INSERT INTO trivia_questions (category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, is_free_play) VALUES

-- Easy Questions (25)
('entertainment', 'easy', 'Who played Iron Man in the Marvel Cinematic Universe?', 'Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo', 'B', false),
('entertainment', 'easy', 'Which movie features the song "Let It Go"?', 'Moana', 'Frozen', 'Tangled', 'Brave', 'B', false),
('entertainment', 'easy', 'Who is known as the King of Pop?', 'Elvis Presley', 'Michael Jackson', 'Prince', 'Freddie Mercury', 'B', false),
('entertainment', 'easy', 'What is the name of Harry Potter''s owl?', 'Errol', 'Hedwig', 'Pigwidgeon', 'Scabbers', 'B', false),
('entertainment', 'easy', 'Which streaming service created "Stranger Things"?', 'Hulu', 'Netflix', 'Disney+', 'Prime Video', 'B', false),
('entertainment', 'easy', 'Who painted the Mona Lisa?', 'Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello', 'B', false),
('entertainment', 'easy', 'What is the highest-grossing film of all time?', 'Titanic', 'Avatar', 'Avengers: Endgame', 'Star Wars', 'B', false),
('entertainment', 'easy', 'Which band sang "Bohemian Rhapsody"?', 'The Beatles', 'Queen', 'Led Zeppelin', 'Pink Floyd', 'B', false),
('entertainment', 'easy', 'What is the name of the coffee shop in Friends?', 'Starbucks', 'Central Perk', 'Java Junction', 'Coffee Bean', 'B', false),
('entertainment', 'easy', 'Who directed "Jurassic Park"?', 'James Cameron', 'Steven Spielberg', 'George Lucas', 'Peter Jackson', 'B', false),
('entertainment', 'easy', 'Which Disney princess has a pet tiger?', 'Belle', 'Jasmine', 'Ariel', 'Pocahontas', 'B', false),
('entertainment', 'easy', 'What instrument did Louis Armstrong play?', 'Saxophone', 'Trumpet', 'Piano', 'Guitar', 'B', false),
('entertainment', 'easy', 'Which TV show features a character named Walter White?', 'The Wire', 'Breaking Bad', 'Narcos', 'Ozark', 'B', false),
('entertainment', 'easy', 'Who wrote "Romeo and Juliet"?', 'Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain', 'B', false),
('entertainment', 'easy', 'What is Superman''s weakness?', 'Silver', 'Kryptonite', 'Gold', 'Iron', 'B', false),
('entertainment', 'easy', 'Which animated movie features a character named Simba?', 'Jungle Book', 'The Lion King', 'Madagascar', 'Tarzan', 'B', false),
('entertainment', 'easy', 'Who sang "Thriller"?', 'Prince', 'Michael Jackson', 'Whitney Houston', 'Madonna', 'B', false),
('entertainment', 'easy', 'What is the name of the school in Harry Potter?', 'Durmstrang', 'Hogwarts', 'Beauxbatons', 'Ilvermorny', 'B', false),
('entertainment', 'easy', 'Which actor played Jack in Titanic?', 'Brad Pitt', 'Leonardo DiCaprio', 'Tom Cruise', 'Johnny Depp', 'B', false),
('entertainment', 'easy', 'What is the name of the toy cowboy in Toy Story?', 'Buzz', 'Woody', 'Rex', 'Slinky', 'B', false),
('entertainment', 'easy', 'Which superhero is known as the Dark Knight?', 'Superman', 'Batman', 'Spider-Man', 'Iron Man', 'B', false),
('entertainment', 'easy', 'Who sang "Like a Virgin"?', 'Cyndi Lauper', 'Madonna', 'Cher', 'Whitney Houston', 'B', false),
('entertainment', 'easy', 'What is the name of the kingdom in Frozen?', 'Corona', 'Arendelle', 'DunBroch', 'Atlantica', 'B', false),
('entertainment', 'easy', 'Which TV show is set in Westeros?', 'The Witcher', 'Game of Thrones', 'Vikings', 'The Last Kingdom', 'B', false),
('entertainment', 'easy', 'Who directed "The Godfather"?', 'Martin Scorsese', 'Francis Ford Coppola', 'Quentin Tarantino', 'Steven Spielberg', 'B', false),

-- Hard Questions (25)
('entertainment', 'hard', 'What year was the first Star Wars film released?', '1975', '1977', '1979', '1980', 'B', false),
('entertainment', 'hard', 'Which composer wrote "The Four Seasons"?', 'Bach', 'Vivaldi', 'Mozart', 'Beethoven', 'B', false),
('entertainment', 'hard', 'What is the longest-running Broadway show?', 'Cats', 'The Phantom of the Opera', 'Les Misérables', 'Chicago', 'B', false),
('entertainment', 'hard', 'Which actor has won the most Oscars?', 'Meryl Streep', 'Katharine Hepburn', 'Jack Nicholson', 'Daniel Day-Lewis', 'B', false),
('entertainment', 'hard', 'Who created "The Simpsons"?', 'Seth MacFarlane', 'Matt Groening', 'Trey Parker', 'Mike Judge', 'B', false),
('entertainment', 'hard', 'What is the best-selling album of all time?', 'Back in Black', 'Thriller', 'The Dark Side of the Moon', 'Abbey Road', 'B', false),
('entertainment', 'hard', 'Which film won the first Academy Award for Best Picture?', 'Metropolis', 'Wings', 'The Jazz Singer', 'Sunrise', 'B', false),
('entertainment', 'hard', 'Who wrote the novel "1984"?', 'Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'Arthur C. Clarke', 'B', false),
('entertainment', 'hard', 'What is the highest-rated TV show on IMDb?', 'The Wire', 'Breaking Bad', 'Game of Thrones', 'The Sopranos', 'B', false),
('entertainment', 'hard', 'Which artist painted "The Starry Night"?', 'Claude Monet', 'Vincent van Gogh', 'Pablo Picasso', 'Salvador Dali', 'B', false),
('entertainment', 'hard', 'What is the real name of rapper Eminem?', 'Marshall Mathers', 'Curtis Jackson', 'Calvin Broadus', 'Shawn Carter', 'A', false),
('entertainment', 'hard', 'Which director has won the most Oscars?', 'Steven Spielberg', 'John Ford', 'Alfred Hitchcock', 'Martin Scorsese', 'B', false),
('entertainment', 'hard', 'What is the name of the first Pokémon ever created?', 'Pikachu', 'Rhydon', 'Mew', 'Bulbasaur', 'B', false),
('entertainment', 'hard', 'Who composed the opera "The Magic Flute"?', 'Verdi', 'Mozart', 'Wagner', 'Puccini', 'B', false),
('entertainment', 'hard', 'Which band performed at Woodstock in 1969?', 'The Beatles', 'Jimi Hendrix Experience', 'The Rolling Stones', 'The Doors', 'B', false),
('entertainment', 'hard', 'What is the best-selling video game of all time?', 'Grand Theft Auto V', 'Minecraft', 'Tetris', 'Wii Sports', 'B', false),
('entertainment', 'hard', 'Who wrote "The Great Gatsby"?', 'Ernest Hemingway', 'F. Scott Fitzgerald', 'John Steinbeck', 'William Faulkner', 'B', false),
('entertainment', 'hard', 'Which film features the quote "Here''s looking at you, kid"?', 'Gone with the Wind', 'Casablanca', 'Citizen Kane', 'The Maltese Falcon', 'B', false),
('entertainment', 'hard', 'What is the longest film ever made?', 'Gone with the Wind', 'The Cure for Insomnia', 'Shoah', 'War and Peace', 'B', false),
('entertainment', 'hard', 'Which musician has sold the most records?', 'Elvis Presley', 'The Beatles', 'Michael Jackson', 'Madonna', 'B', false),
('entertainment', 'hard', 'Who painted "The Last Supper"?', 'Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Caravaggio', 'B', false),
('entertainment', 'hard', 'What is the first Disney animated feature film?', 'Fantasia', 'Snow White and the Seven Dwarfs', 'Pinocchio', 'Bambi', 'B', false),
('entertainment', 'hard', 'Which composer became deaf later in life?', 'Mozart', 'Beethoven', 'Bach', 'Chopin', 'B', false),
('entertainment', 'hard', 'What is the best-selling book of all time (excluding religious texts)?', 'Lord of the Rings', 'Don Quixote', 'Harry Potter', 'A Tale of Two Cities', 'B', false),
('entertainment', 'hard', 'Which TV show had the most-watched finale?', 'Seinfeld', 'M*A*S*H', 'Friends', 'Cheers', 'B', false);
