-- History & Geography Questions - 50 questions

INSERT INTO trivia_questions (category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer) VALUES
-- Rookie Questions (20)
('history', 'rookie', 'Who was the first president of the United States?', 'Jefferson', 'Washington', 'Adams', 'Lincoln', 'B'),
('history', 'rookie', 'What year did World War II end?', '1943', '1944', '1945', '1946', 'C'),
('history', 'rookie', 'What is the capital of France?', 'Lyon', 'Paris', 'Nice', 'Marseille', 'B'),
('history', 'rookie', 'How many continents are there?', '5', '6', '7', '8', 'C'),
('history', 'rookie', 'What is the largest country by area?', 'Canada', 'China', 'USA', 'Russia', 'D'),
('history', 'rookie', 'What year did Christopher Columbus reach America?', '1482', '1492', '1502', '1512', 'B'),
('history', 'rookie', 'What is the capital of Italy?', 'Milan', 'Rome', 'Naples', 'Venice', 'B'),
('history', 'rookie', 'What ocean is between America and Europe?', 'Pacific', 'Atlantic', 'Indian', 'Arctic', 'B'),
('history', 'rookie', 'Who built the pyramids?', 'Romans', 'Greeks', 'Egyptians', 'Mayans', 'C'),
('history', 'rookie', 'What is the smallest continent?', 'Europe', 'Antarctica', 'Australia', 'South America', 'C'),
('history', 'rookie', 'What year did the Titanic sink?', '1910', '1911', '1912', '1913', 'C'),
('history', 'rookie', 'What is the capital of Japan?', 'Osaka', 'Kyoto', 'Tokyo', 'Nagoya', 'C'),
('history', 'rookie', 'How many states are in the USA?', '48', '49', '50', '51', 'C'),
('history', 'rookie', 'What is the longest river in the world?', 'Amazon', 'Nile', 'Yangtze', 'Mississippi', 'B'),
('history', 'rookie', 'What country is the Eiffel Tower in?', 'Italy', 'Spain', 'France', 'Germany', 'C'),
('history', 'rookie', 'Who was the first man on the moon?', 'Buzz Aldrin', 'Neil Armstrong', 'John Glenn', 'Alan Shepard', 'B'),
('history', 'rookie', 'What is the capital of England?', 'Manchester', 'Birmingham', 'London', 'Liverpool', 'C'),
('history', 'rookie', 'What continent is Egypt in?', 'Asia', 'Africa', 'Europe', 'Middle East', 'B'),
('history', 'rookie', 'What year did World War I start?', '1912', '1913', '1914', '1915', 'C'),
('history', 'rookie', 'What is the capital of China?', 'Shanghai', 'Hong Kong', 'Beijing', 'Guangzhou', 'C'),

-- Pro Questions (20)
('history', 'pro', 'What year did the Berlin Wall fall?', '1987', '1988', '1989', '1990', 'C'),
('history', 'pro', 'Who was the longest reigning British monarch?', 'Victoria', 'Elizabeth I', 'Elizabeth II', 'George III', 'C'),
('history', 'pro', 'What year did India gain independence?', '1945', '1946', '1947', '1948', 'C'),
('history', 'pro', 'What is the capital of Australia?', 'Sydney', 'Melbourne', 'Canberra', 'Perth', 'C'),
('history', 'pro', 'Who invented the telephone?', 'Edison', 'Bell', 'Tesla', 'Marconi', 'B'),
('history', 'pro', 'What year did the Roman Empire fall?', '376 AD', '476 AD', '576 AD', '676 AD', 'B'),
('history', 'pro', 'What is the deepest ocean trench?', 'Puerto Rico', 'Java', 'Mariana', 'Tonga', 'C'),
('history', 'pro', 'Who wrote the Declaration of Independence?', 'Washington', 'Franklin', 'Jefferson', 'Adams', 'C'),
('history', 'pro', 'What year was the United Nations founded?', '1943', '1944', '1945', '1946', 'C'),
('history', 'pro', 'What is the second largest country by area?', 'USA', 'Canada', 'China', 'Brazil', 'B'),
('history', 'pro', 'Who was the first female Prime Minister of UK?', 'May', 'Thatcher', 'Truss', 'Sturgeon', 'B'),
('history', 'pro', 'What year did the American Civil War end?', '1863', '1864', '1865', '1866', 'C'),
('history', 'pro', 'What is the highest mountain in Africa?', 'Kilimanjaro', 'Kenya', 'Meru', 'Stanley', 'A'),
('history', 'pro', 'Who discovered penicillin?', 'Pasteur', 'Fleming', 'Jenner', 'Koch', 'B'),
('history', 'pro', 'What year was the Magna Carta signed?', '1115', '1215', '1315', '1415', 'B'),
('history', 'pro', 'What is the largest island in the world?', 'New Guinea', 'Borneo', 'Greenland', 'Madagascar', 'C'),
('history', 'pro', 'Who was the first emperor of Rome?', 'Caesar', 'Augustus', 'Nero', 'Caligula', 'B'),
('history', 'pro', 'What year did the French Revolution start?', '1787', '1788', '1789', '1790', 'C'),
('history', 'pro', 'What is the capital of Brazil?', 'Rio', 'Sao Paulo', 'Brasilia', 'Salvador', 'C'),
('history', 'pro', 'Who painted the Sistine Chapel ceiling?', 'Da Vinci', 'Raphael', 'Michelangelo', 'Donatello', 'C'),

-- Legend Questions (10)
('history', 'legend', 'What year was the Battle of Hastings?', '1066', '1166', '1266', '1366', 'A'),
('history', 'legend', 'Who was the last Byzantine Emperor?', 'Constantine X', 'Constantine XI', 'Constantine XII', 'Constantine XIII', 'B'),
('history', 'legend', 'What year was the Treaty of Westphalia signed?', '1548', '1598', '1648', '1698', 'C'),
('history', 'legend', 'What is the population of Vatican City?', '~600', '~800', '~1000', '~1200', 'B'),
('history', 'legend', 'Who was the first Pharaoh of Egypt?', 'Khufu', 'Narmer', 'Djoser', 'Sneferu', 'B'),
('history', 'legend', 'What year did Constantinople fall?', '1353', '1403', '1453', '1503', 'C'),
('history', 'legend', 'What is the oldest continuously inhabited city?', 'Jericho', 'Damascus', 'Aleppo', 'Athens', 'B'),
('history', 'legend', 'Who was the first Holy Roman Emperor?', 'Otto I', 'Charlemagne', 'Frederick I', 'Henry II', 'B'),
('history', 'legend', 'What year was the Hundred Years War concluded?', '1353', '1403', '1453', '1503', 'C'),
('history', 'legend', 'What is the area of Russia in million sq km?', '15.1', '16.1', '17.1', '18.1', 'C');
