-- IQ Arena - Arts & Literature Questions (Fixed for actual schema)
-- 50 questions with easy/hard difficulty

INSERT INTO trivia_questions (category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, is_free_play) VALUES

-- Easy Questions (25)
('arts_literature', 'easy', 'Who wrote "Harry Potter"?', 'Suzanne Collins', 'J.K. Rowling', 'Stephenie Meyer', 'Veronica Roth', 'B', false),
('arts_literature', 'easy', 'What color do you get when you mix red and white?', 'Orange', 'Pink', 'Purple', 'Maroon', 'B', false),
('arts_literature', 'easy', 'Who painted the Sistine Chapel ceiling?', 'Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Donatello', 'B', false),
('arts_literature', 'easy', 'What is the opposite of a protagonist?', 'Hero', 'Antagonist', 'Narrator', 'Villain', 'B', false),
('arts_literature', 'easy', 'Which author created Sherlock Holmes?', 'Agatha Christie', 'Arthur Conan Doyle', 'Edgar Allan Poe', 'H.G. Wells', 'B', false),
('arts_literature', 'easy', 'What type of art uses clay?', 'Painting', 'Pottery', 'Sculpture', 'Drawing', 'B', false),
('arts_literature', 'easy', 'Who wrote "The Cat in the Hat"?', 'Roald Dahl', 'Dr. Seuss', 'Maurice Sendak', 'Eric Carle', 'B', false),
('arts_literature', 'easy', 'What are the three primary colors?', 'Red, Yellow, Green', 'Red, Yellow, Blue', 'Red, Green, Blue', 'Orange, Purple, Green', 'B', false),
('arts_literature', 'easy', 'Which fairy tale features a glass slipper?', 'Snow White', 'Cinderella', 'Sleeping Beauty', 'Rapunzel', 'B', false),
('arts_literature', 'easy', 'Who wrote "The Odyssey"?', 'Virgil', 'Homer', 'Sophocles', 'Euripides', 'B', false),
('arts_literature', 'easy', 'What is a haiku?', 'A long poem', 'A short Japanese poem', 'A type of novel', 'A play', 'B', false),
('arts_literature', 'easy', 'Which artist is famous for cutting off his ear?', 'Picasso', 'Van Gogh', 'Monet', 'Dali', 'B', false),
('arts_literature', 'easy', 'What is the first book of the Bible?', 'Exodus', 'Genesis', 'Leviticus', 'Numbers', 'B', false),
('arts_literature', 'easy', 'Who wrote "Pride and Prejudice"?', 'Charlotte Brontë', 'Jane Austen', 'Emily Brontë', 'Mary Shelley', 'B', false),
('arts_literature', 'easy', 'What is the art of beautiful handwriting called?', 'Typography', 'Calligraphy', 'Orthography', 'Lithography', 'B', false),
('arts_literature', 'easy', 'Which poet wrote "The Raven"?', 'Robert Frost', 'Edgar Allan Poe', 'Walt Whitman', 'Emily Dickinson', 'B', false),
('arts_literature', 'easy', 'What is the study of ancient texts called?', 'Archaeology', 'Philology', 'Anthropology', 'Etymology', 'B', false),
('arts_literature', 'easy', 'Who painted "The Scream"?', 'Van Gogh', 'Edvard Munch', 'Picasso', 'Dali', 'B', false),
('arts_literature', 'easy', 'What is the longest word in Shakespeare''s works?', 'Antidisestablishmentarianism', 'Honorificabilitudinitatibus', 'Incomprehensibilities', 'Disproportionableness', 'B', false),
('arts_literature', 'easy', 'Who wrote "1984"?', 'Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'Kurt Vonnegut', 'B', false),
('arts_literature', 'easy', 'What is a sonnet?', 'A 12-line poem', 'A 14-line poem', 'A 16-line poem', 'A 10-line poem', 'B', false),
('arts_literature', 'easy', 'Which artist painted "The Persistence of Memory"?', 'Picasso', 'Salvador Dali', 'Van Gogh', 'Monet', 'B', false),
('arts_literature', 'easy', 'Who wrote "To Kill a Mockingbird"?', 'Truman Capote', 'Harper Lee', 'John Steinbeck', 'Ernest Hemingway', 'B', false),
('arts_literature', 'easy', 'What is the art movement characterized by geometric shapes?', 'Impressionism', 'Cubism', 'Surrealism', 'Expressionism', 'B', false),
('arts_literature', 'easy', 'Who wrote "The Divine Comedy"?', 'Petrarch', 'Dante', 'Boccaccio', 'Chaucer', 'B', false),

-- Hard Questions (25)
('arts_literature', 'hard', 'What is the pen name of Samuel Clemens?', 'O. Henry', 'Mark Twain', 'Lewis Carroll', 'George Eliot', 'B', false),
('arts_literature', 'hard', 'Which art movement did Claude Monet co-found?', 'Cubism', 'Impressionism', 'Surrealism', 'Expressionism', 'B', false),
('arts_literature', 'hard', 'Who wrote "One Hundred Years of Solitude"?', 'Jorge Luis Borges', 'Gabriel García Márquez', 'Pablo Neruda', 'Octavio Paz', 'B', false),
('arts_literature', 'hard', 'What is the technique of scratching through one layer to reveal another?', 'Impasto', 'Sgraffito', 'Sfumato', 'Chiaroscuro', 'B', false),
('arts_literature', 'hard', 'Which novel begins with "Call me Ishmael"?', 'The Old Man and the Sea', 'Moby-Dick', 'Typee', 'White Jacket', 'B', false),
('arts_literature', 'hard', 'Who painted "Guernica"?', 'Salvador Dali', 'Pablo Picasso', 'Joan Miró', 'Diego Rivera', 'B', false),
('arts_literature', 'hard', 'What is the Japanese art of paper folding?', 'Ikebana', 'Origami', 'Kirigami', 'Kusudama', 'B', false),
('arts_literature', 'hard', 'Who wrote "The Brothers Karamazov"?', 'Leo Tolstoy', 'Fyodor Dostoevsky', 'Anton Chekhov', 'Ivan Turgenev', 'B', false),
('arts_literature', 'hard', 'What is the art technique using light and shadow?', 'Tenebrism', 'Chiaroscuro', 'Sfumato', 'Impasto', 'B', false),
('arts_literature', 'hard', 'Which poet wrote "The Waste Land"?', 'Ezra Pound', 'T.S. Eliot', 'W.H. Auden', 'Robert Frost', 'B', false),
('arts_literature', 'hard', 'Who sculpted "The Thinker"?', 'Michelangelo', 'Auguste Rodin', 'Donatello', 'Bernini', 'B', false),
('arts_literature', 'hard', 'What is the literary device of giving human qualities to non-human things?', 'Metaphor', 'Personification', 'Simile', 'Alliteration', 'B', false),
('arts_literature', 'hard', 'Who wrote "The Picture of Dorian Gray"?', 'Oscar Wilde', 'Charles Dickens', 'Bram Stoker', 'Robert Louis Stevenson', 'A', false),
('arts_literature', 'hard', 'What is the Renaissance technique of subtle blending?', 'Impasto', 'Sfumato', 'Glazing', 'Scumbling', 'B', false),
('arts_literature', 'hard', 'Which author wrote under the pseudonym George Eliot?', 'Mary Ann Evans', 'Charlotte Brontë', 'Elizabeth Gaskell', 'George Sand', 'A', false),
('arts_literature', 'hard', 'Who painted "The Birth of Venus"?', 'Leonardo da Vinci', 'Sandro Botticelli', 'Raphael', 'Titian', 'B', false),
('arts_literature', 'hard', 'What is a metrical foot with one stressed and one unstressed syllable?', 'Iamb', 'Trochee', 'Dactyl', 'Anapest', 'B', false),
('arts_literature', 'hard', 'Who wrote "In Search of Lost Time"?', 'James Joyce', 'Marcel Proust', 'Virginia Woolf', 'Thomas Mann', 'B', false),
('arts_literature', 'hard', 'What is the Japanese art of flower arrangement?', 'Origami', 'Ikebana', 'Bonsai', 'Kintsugi', 'B', false),
('arts_literature', 'hard', 'Which playwright wrote "Waiting for Godot"?', 'Harold Pinter', 'Samuel Beckett', 'Tom Stoppard', 'Eugene Ionesco', 'B', false),
('arts_literature', 'hard', 'Who painted "The Night Watch"?', 'Vermeer', 'Rembrandt', 'Frans Hals', 'Jan Steen', 'B', false),
('arts_literature', 'hard', 'What is the term for a word that sounds like what it describes?', 'Alliteration', 'Onomatopoeia', 'Assonance', 'Consonance', 'B', false),
('arts_literature', 'hard', 'Who wrote "The Metamorphosis"?', 'Hermann Hesse', 'Franz Kafka', 'Thomas Mann', 'Robert Musil', 'B', false),
('arts_literature', 'hard', 'What art style features optical illusions?', 'Abstract', 'Op Art', 'Pop Art', 'Minimalism', 'B', false),
('arts_literature', 'hard', 'Which epic poem features the hero Aeneas?', 'Iliad', 'Aeneid', 'Odyssey', 'Metamorphoses', 'B', false);
