-- Sports Questions - 50 questions (rookie, pro, legend mix)

INSERT INTO trivia_questions (category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer) VALUES
-- Rookie Questions (20)
('sports', 'rookie', 'How many points is a touchdown worth in American football?', '3', '6', '7', '8', 'B'),
('sports', 'rookie', 'What sport uses a puck?', 'Soccer', 'Basketball', 'Hockey', 'Tennis', 'C'),
('sports', 'rookie', 'How many players are on a basketball team?', '4', '5', '6', '7', 'B'),
('sports', 'rookie', 'What color is a tennis ball?', 'White', 'Yellow', 'Green', 'Orange', 'B'),
('sports', 'rookie', 'How many bases are in baseball?', '3', '4', '5', '6', 'B'),
('sports', 'rookie', 'What sport uses a net and a shuttlecock?', 'Tennis', 'Badminton', 'Volleyball', 'Pickleball', 'B'),
('sports', 'rookie', 'How many holes are played in a standard round of golf?', '9', '12', '18', '24', 'C'),
('sports', 'rookie', 'What is a perfect score in bowling?', '100', '200', '300', '400', 'C'),
('sports', 'rookie', 'How many periods are in a hockey game?', '2', '3', '4', '5', 'B'),
('sports', 'rookie', 'What sport is Wimbledon associated with?', 'Golf', 'Tennis', 'Cricket', 'Rugby', 'B'),
('sports', 'rookie', 'How many innings are in a baseball game?', '7', '8', '9', '10', 'C'),
('sports', 'rookie', 'What color card means ejection in soccer?', 'Yellow', 'Orange', 'Red', 'Black', 'C'),
('sports', 'rookie', 'How many players are on a volleyball team?', '4', '5', '6', '7', 'C'),
('sports', 'rookie', 'What is the home of golf?', 'England', 'Ireland', 'Scotland', 'Wales', 'C'),
('sports', 'rookie', 'How many points is a field goal worth in basketball?', '1', '2', '3', 'Depends', 'D'),
('sports', 'rookie', 'What sport uses wickets?', 'Baseball', 'Cricket', 'Polo', 'Rugby', 'B'),
('sports', 'rookie', 'How many yards is a football field?', '90', '100', '110', '120', 'B'),
('sports', 'rookie', 'What is the first event in a decathlon?', '100m dash', 'Long jump', 'Shot put', 'High jump', 'A'),
('sports', 'rookie', 'How many Grand Slam tournaments are in tennis?', '3', '4', '5', '6', 'B'),
('sports', 'rookie', 'What color are the goal posts in football?', 'White', 'Yellow', 'Orange', 'Red', 'B'),

-- Pro Questions (20)
('sports', 'pro', 'Who has won the most Olympic gold medals?', 'Usain Bolt', 'Michael Phelps', 'Carl Lewis', 'Mark Spitz', 'B'),
('sports', 'pro', 'What is the diameter of a basketball hoop in inches?', '16', '17', '18', '19', 'C'),
('sports', 'pro', 'How many Formula 1 World Championships did Michael Schumacher win?', '5', '6', '7', '8', 'C'),
('sports', 'pro', 'What is the maximum break in snooker?', '145', '147', '149', '151', 'B'),
('sports', 'pro', 'How many players are on a rugby union team?', '13', '15', '17', '19', 'B'),
('sports', 'pro', 'What is the regulation height of a basketball hoop in feet?', '9', '10', '11', '12', 'B'),
('sports', 'pro', 'How many majors has Tiger Woods won?', '13', '14', '15', '16', 'C'),
('sports', 'pro', 'What is the distance of an Olympic marathon in kilometers?', '40.195', '41.195', '42.195', '43.195', 'C'),
('sports', 'pro', 'How many stitches are on a baseball?', '106', '108', '110', '112', 'B'),
('sports', 'pro', 'What is par at Augusta National Golf Club?', '70', '71', '72', '73', 'C'),
('sports', 'pro', 'How many minutes are in a professional soccer match?', '80', '85', '90', '95', 'C'),
('sports', 'pro', 'What is the record for most points in an NBA game?', '81', '90', '100', '105', 'C'),
('sports', 'pro', 'How many Super Bowls did Tom Brady win?', '5', '6', '7', '8', 'C'),
('sports', 'pro', 'What is the height of an Olympic high jump bar record?', '2.35m', '2.40m', '2.45m', '2.50m', 'C'),
('sports', 'pro', 'How many players start on a cricket team?', '9', '10', '11', '12', 'C'),
('sports', 'pro', 'What is the weight of a shot put for men in kg?', '6.26', '7.26', '8.26', '9.26', 'B'),
('sports', 'pro', 'How many laps is the Indianapolis 500?', '150', '175', '200', '225', 'C'),
('sports', 'pro', 'What is the length of an Olympic swimming pool in meters?', '25', '50', '75', '100', 'B'),
('sports', 'pro', 'How many minutes are in an NBA quarter?', '10', '12', '15', '20', 'B'),
('sports', 'pro', 'What is the maximum score in Olympic gymnastics?', '9.0', '10.0', '11.0', '12.0', 'B'),

-- Legend Questions (10)
('sports', 'legend', 'Who holds the record for most career home runs?', 'Hank Aaron', 'Babe Ruth', 'Barry Bonds', 'Alex Rodriguez', 'C'),
('sports', 'legend', 'What year were the first modern Olympics held?', '1892', '1894', '1896', '1898', 'C'),
('sports', 'legend', 'How many times did Brazil win the FIFA World Cup?', '3', '4', '5', '6', 'C'),
('sports', 'legend', 'What is the record for fastest 100m sprint?', '9.58s', '9.63s', '9.69s', '9.72s', 'A'),
('sports', 'legend', 'How many Grand Slam singles titles did Roger Federer win?', '18', '19', '20', '21', 'C'),
('sports', 'legend', 'What is the highest score in NBA history?', '184', '186', '188', '190', 'B'),
('sports', 'legend', 'How many Olympic medals did swimmer Mark Spitz win in 1972?', '5', '6', '7', '8', 'C'),
('sports', 'legend', 'What is the record for most consecutive games with a hit in MLB?', '44', '50', '56', '62', 'C'),
('sports', 'legend', 'How many times did Muhammad Ali win the heavyweight title?', '2', '3', '4', '5', 'B'),
('sports', 'legend', 'What is the world record for longest long jump?', '8.75m', '8.85m', '8.95m', '9.05m', 'C');
