-- General Knowledge Questions - 50 questions (rookie, pro, legend mix)

INSERT INTO trivia_questions (category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer) VALUES
-- Rookie Questions (20)
('general', 'rookie', 'What is the largest planet in our solar system?', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'C'),
('general', 'rookie', 'How many days are in a leap year?', '364', '365', '366', '367', 'C'),
('general', 'rookie', 'What is the freezing point of water in Celsius?', '-1', '0', '1', '32', 'B'),
('general', 'rookie', 'How many minutes are in one hour?', '50', '60', '70', '100', 'B'),
('general', 'rookie', 'What color do you get when you mix red and white?', 'Orange', 'Pink', 'Purple', 'Brown', 'B'),
('general', 'rookie', 'How many wheels does a bicycle have?', '1', '2', '3', '4', 'B'),
('general', 'rookie', 'What is the opposite of hot?', 'Warm', 'Cool', 'Cold', 'Freezing', 'C'),
('general', 'rookie', 'How many letters are in the English alphabet?', '24', '25', '26', '27', 'C'),
('general', 'rookie', 'What shape is a stop sign?', 'Circle', 'Square', 'Triangle', 'Octagon', 'D'),
('general', 'rookie', 'How many months have 31 days?', '5', '6', '7', '8', 'C'),
('general', 'rookie', 'What is the first day of the week?', 'Monday', 'Sunday', 'Saturday', 'Tuesday', 'B'),
('general', 'rookie', 'How many seasons are there in a year?', '2', '3', '4', '5', 'C'),
('general', 'rookie', 'What animal says "meow"?', 'Dog', 'Cat', 'Bird', 'Cow', 'B'),
('general', 'rookie', 'What color is grass?', 'Blue', 'Green', 'Red', 'Yellow', 'B'),
('general', 'rookie', 'How many zeros are in one hundred?', '1', '2', '3', '4', 'B'),
('general', 'rookie', 'What do bees make?', 'Milk', 'Honey', 'Butter', 'Cheese', 'B'),
('general', 'rookie', 'What is the largest continent?', 'Africa', 'Europe', 'Asia', 'America', 'C'),
('general', 'rookie', 'How many colors are in a rainbow?', '5', '6', '7', '8', 'C'),
('general', 'rookie', 'What is the capital of the United States?', 'New York', 'Los Angeles', 'Washington DC', 'Chicago', 'C'),
('general', 'rookie', 'How many legs does a spider have?', '6', '8', '10', '12', 'B'),

-- Pro Questions (20)
('general', 'pro', 'What is the smallest country in the world?', 'Monaco', 'Vatican City', 'San Marino', 'Liechtenstein', 'B'),
('general', 'pro', 'How many bones are in the human body?', '196', '206', '216', '226', 'B'),
('general', 'pro', 'What is the currency of Japan?', 'Yuan', 'Won', 'Yen', 'Ringgit', 'C'),
('general', 'pro', 'How many Great Lakes are there?', '4', '5', '6', '7', 'B'),
('general', 'pro', 'What is the largest desert in the world?', 'Sahara', 'Arabian', 'Gobi', 'Antarctic', 'D'),
('general', 'pro', 'How many strings does a standard guitar have?', '4', '5', '6', '7', 'C'),
('general', 'pro', 'What is the hardest natural substance?', 'Gold', 'Iron', 'Diamond', 'Platinum', 'C'),
('general', 'pro', 'How many sides does a hexagon have?', '5', '6', '7', '8', 'B'),
('general', 'pro', 'What is the tallest mountain in the world?', 'K2', 'Everest', 'Kilimanjaro', 'Denali', 'B'),
('general', 'pro', 'How many time zones does Russia span?', '8', '9', '10', '11', 'D'),
('general', 'pro', 'What is the main ingredient in hummus?', 'Lentils', 'Chickpeas', 'Peas', 'Beans', 'B'),
('general', 'pro', 'How many players are on a soccer team?', '9', '10', '11', '12', 'C'),
('general', 'pro', 'What is the largest organ in the human body?', 'Heart', 'Liver', 'Skin', 'Brain', 'C'),
('general', 'pro', 'How many rings are on the Olympic flag?', '4', '5', '6', '7', 'B'),
('general', 'pro', 'What is the fastest land animal?', 'Lion', 'Cheetah', 'Gazelle', 'Leopard', 'B'),
('general', 'pro', 'How many keys are on a standard piano?', '76', '82', '88', '92', 'C'),
('general', 'pro', 'What is the smallest ocean?', 'Indian', 'Atlantic', 'Arctic', 'Southern', 'C'),
('general', 'pro', 'How many chambers does the human heart have?', '2', '3', '4', '5', 'C'),
('general', 'pro', 'What is the longest bone in the human body?', 'Tibia', 'Femur', 'Humerus', 'Fibula', 'B'),
('general', 'pro', 'How many permanent teeth does an adult have?', '28', '30', '32', '34', 'C'),

-- Legend Questions (10)
('general', 'legend', 'What is the rarest blood type?', 'O negative', 'AB negative', 'A negative', 'B negative', 'B'),
('general', 'legend', 'How many elements are in the periodic table?', '108', '112', '116', '118', 'D'),
('general', 'legend', 'What is the deepest point in the ocean?', 'Puerto Rico Trench', 'Java Trench', 'Mariana Trench', 'Tonga Trench', 'C'),
('general', 'legend', 'How many countries are in the United Nations?', '191', '193', '195', '197', 'B'),
('general', 'legend', 'What is the most spoken language by native speakers?', 'English', 'Spanish', 'Mandarin', 'Hindi', 'C'),
('general', 'legend', 'How many cards are in a standard tarot deck?', '72', '76', '78', '80', 'C'),
('general', 'legend', 'What is the smallest unit of life?', 'Atom', 'Cell', 'Molecule', 'Organ', 'B'),
('general', 'legend', 'How many miles are in a marathon?', '24.2', '25.2', '26.2', '27.2', 'C'),
('general', 'legend', 'What is the most abundant gas in Earths atmosphere?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen', 'C'),
('general', 'legend', 'How many stripes are on the American flag?', '11', '12', '13', '14', 'C');
