-- Science & Technology Questions - 50 questions

INSERT INTO trivia_questions (category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer) VALUES
-- Rookie Questions (20)
('science', 'rookie', 'What planet is known as the Red Planet?', 'Venus', 'Mars', 'Jupiter', 'Saturn', 'B'),
('science', 'rookie', 'How many planets are in our solar system?', '7', '8', '9', '10', 'B'),
('science', 'rookie', 'What gas do plants absorb from the air?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen', 'C'),
('science', 'rookie', 'What is H2O commonly known as?', 'Salt', 'Water', 'Sugar', 'Air', 'B'),
('science', 'rookie', 'What force pulls objects toward Earth?', 'Magnetism', 'Electricity', 'Gravity', 'Friction', 'C'),
('science', 'rookie', 'What is the center of an atom called?', 'Electron', 'Proton', 'Nucleus', 'Neutron', 'C'),
('science', 'rookie', 'What animal class do frogs belong to?', 'Mammals', 'Reptiles', 'Amphibians', 'Fish', 'C'),
('science', 'rookie', 'How many legs does an insect have?', '4', '6', '8', '10', 'B'),
('science', 'rookie', 'What is the largest star in our solar system?', 'Moon', 'Sun', 'Jupiter', 'Sirius', 'B'),
('science', 'rookie', 'What do you call a baby frog?', 'Tadpole', 'Froglet', 'Puppy', 'Kitten', 'A'),
('science', 'rookie', 'What is the boiling point of water in Celsius?', '90', '95', '100', '105', 'C'),
('science', 'rookie', 'What is the study of living things called?', 'Geology', 'Biology', 'Chemistry', 'Physics', 'B'),
('science', 'rookie', 'How many colors are in a spectrum?', '5', '6', '7', '8', 'C'),
('science', 'rookie', 'What is the closest planet to the sun?', 'Venus', 'Earth', 'Mercury', 'Mars', 'C'),
('science', 'rookie', 'What part of the plant conducts photosynthesis?', 'Root', 'Stem', 'Leaf', 'Flower', 'C'),
('science', 'rookie', 'What is the hardest rock?', 'Marble', 'Granite', 'Diamond', 'Quartz', 'C'),
('science', 'rookie', 'How many wings does a bee have?', '2', '4', '6', '8', 'B'),
('science', 'rookie', 'What is the largest mammal?', 'Elephant', 'Blue Whale', 'Giraffe', 'Polar Bear', 'B'),
('science', 'rookie', 'What do bees collect from flowers?', 'Seeds', 'Nectar', 'Pollen', 'Both B and C', 'D'),
('science', 'rookie', 'What is the closest star to Earth?', 'Sirius', 'Alpha Centauri', 'Sun', 'Polaris', 'C'),

-- Pro Questions (20)
('science', 'pro', 'What is the atomic number of carbon?', '4', '6', '8', '12', 'B'),
('science', 'pro', 'What is the speed of sound in air at sea level?', '299 m/s', '343 m/s', '400 m/s', '500 m/s', 'B'),
('science', 'pro', 'What is the most abundant element in the universe?', 'Oxygen', 'Carbon', 'Hydrogen', 'Helium', 'C'),
('science', 'pro', 'How many chromosomes do humans have?', '23', '42', '44', '46', 'D'),
('science', 'pro', 'What is the pH of pure water?', '5', '6', '7', '8', 'C'),
('science', 'pro', 'What is the powerhouse of the cell?', 'Nucleus', 'Ribosome', 'Mitochondria', 'Chloroplast', 'C'),
('science', 'pro', 'What is the main gas in the Earths atmosphere?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon', 'C'),
('science', 'pro', 'How many bones are in an adult human body?', '196', '206', '216', '226', 'B'),
('science', 'pro', 'What is the chemical formula for salt?', 'NaCl', 'KCl', 'CaCl2', 'MgCl2', 'A'),
('science', 'pro', 'What is the largest organ in the human body?', 'Liver', 'Brain', 'Skin', 'Heart', 'C'),
('science', 'pro', 'What is the smallest bone in the human body?', 'Stapes', 'Incus', 'Malleus', 'Femur', 'A'),
('science', 'pro', 'How many teeth does an adult human have?', '28', '30', '32', '34', 'C'),
('science', 'pro', 'What is the study of weather called?', 'Geology', 'Meteorology', 'Astronomy', 'Ecology', 'B'),
('science', 'pro', 'What is the symbol for potassium?', 'P', 'Po', 'K', 'Pt', 'C'),
('science', 'pro', 'How many chambers does the human heart have?', '2', '3', '4', '5', 'C'),
('science', 'pro', 'What is the most common blood type?', 'A', 'B', 'AB', 'O', 'D'),
('science', 'pro', 'What is the largest planet in our solar system?', 'Saturn', 'Jupiter', 'Neptune', 'Uranus', 'B'),
('science', 'pro', 'How many moons does Mars have?', '0', '1', '2', '3', 'C'),
('science', 'pro', 'What is the chemical symbol for iron?', 'Ir', 'Fe', 'In', 'I', 'B'),
('science', 'pro', 'What is the normal human body temperature in Celsius?', '35', '36', '37', '38', 'C'),

-- Legend Questions (10)
('science', 'legend', 'What is the half-life of Carbon-14?', '5,370 years', '5,730 years', '6,370 years', '6,730 years', 'B'),
('science', 'legend', 'What is the Planck constant value?', '6.626 x 10^-34 J·s', '6.626 x 10^-33 J·s', '7.626 x 10^-34 J·s', '8.626 x 10^-34 J·s', 'A'),
('science', 'legend', 'What is the atomic mass of uranium-235?', '233.04', '234.04', '235.04', '236.04', 'C'),
('science', 'legend', 'What is the Avogadro number?', '6.022 x 10^22', '6.022 x 10^23', '6.022 x 10^24', '6.022 x 10^25', 'B'),
('science', 'legend', 'What is the electron configuration of oxygen?', '1s² 2s² 2p²', '1s² 2s² 2p⁴', '1s² 2s² 2p⁶', '1s² 2s² 2p³', 'B'),
('science', 'legend', 'What is the gravitational constant G?', '6.67 x 10^-11 N·m²/kg²', '6.67 x 10^-10 N·m²/kg²', '6.67 x 10^-12 N·m²/kg²', '7.67 x 10^-11 N·m²/kg²', 'A'),
('science', 'legend', 'What is the charge of an electron?', '-1.6 x 10^-18 C', '-1.6 x 10^-19 C', '-1.6 x 10^-20 C', '-1.8 x 10^-19 C', 'B'),
('science', 'legend', 'What is the speed of light in a vacuum?', '2.998 x 10^8 m/s', '3.000 x 10^8 m/s', '3.100 x 10^8 m/s', '2.900 x 10^8 m/s', 'A'),
('science', 'legend', 'What is the mass of a proton?', '1.672 x 10^-27 kg', '1.673 x 10^-27 kg', '1.674 x 10^-27 kg', '1.675 x 10^-27 kg', 'B'),
('science', 'legend', 'What is the Boltzmann constant?', '1.38 x 10^-23 J/K', '1.38 x 10^-22 J/K', '1.38 x 10^-24 J/K', '1.48 x 10^-23 J/K', 'A');
