-- IQ Arena - Sports Questions (Fixed for actual schema)
-- 50 questions with easy/hard difficulty

INSERT INTO trivia_questions (category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, is_free_play) VALUES

-- Easy Questions (25)
('sports', 'easy', 'How many players are on a basketball team on the court?', 'Five', 'Six', 'Seven', 'Four', 'A', false),
('sports', 'easy', 'What sport is associated with Wimbledon?', 'Tennis', 'Golf', 'Cricket', 'Football', 'A', false),
('sports', 'easy', 'In which sport would you perform a slam dunk?', 'Volleyball', 'Basketball', 'Handball', 'Tennis', 'B', false),
('sports', 'easy', 'How many holes are on a standard golf course?', '9', '18', '27', '36', 'B', false),
('sports', 'easy', 'What color is the center of an archery target?', 'Red', 'Gold/Yellow', 'Blue', 'White', 'B', false),
('sports', 'easy', 'How many points is a touchdown worth in American football?', 'Three', 'Six', 'Seven', 'Four', 'B', false),
('sports', 'easy', 'Which country hosted the 2016 Summer Olympics?', 'China', 'Brazil', 'Russia', 'UK', 'B', false),
('sports', 'easy', 'What is the diameter of a basketball hoop in inches?', '15', '18', '20', '24', 'B', false),
('sports', 'easy', 'In baseball, how many strikes result in an out?', 'Two', 'Three', 'Four', 'Five', 'B', false),
('sports', 'easy', 'Which sport uses a puck?', 'Field Hockey', 'Ice Hockey', 'Lacrosse', 'Polo', 'B', false),
('sports', 'easy', 'How many yards is a football field (without end zones)?', '80', '100', '120', '90', 'B', false),
('sports', 'easy', 'What is the maximum score in a single frame of bowling?', '20', '30', '40', '50', 'B', false),
('sports', 'easy', 'Which country won the first FIFA World Cup in 1930?', 'Brazil', 'Uruguay', 'Argentina', 'Italy', 'B', false),
('sports', 'easy', 'In tennis, what is a score of zero called?', 'Zero', 'Love', 'Nil', 'Deuce', 'B', false),
('sports', 'easy', 'How many Olympic rings are there?', 'Four', 'Five', 'Six', 'Seven', 'B', false),
('sports', 'easy', 'What sport is known as "the beautiful game"?', 'Basketball', 'Soccer/Football', 'Rugby', 'Cricket', 'B', false),
('sports', 'easy', 'How long is a marathon in miles?', '20', '26.2', '30', '25', 'B', false),
('sports', 'easy', 'Which sport uses a shuttlecock?', 'Tennis', 'Badminton', 'Squash', 'Volleyball', 'B', false),
('sports', 'easy', 'In which sport do players slide stones on ice?', 'Shuffleboard', 'Curling', 'Bowling', 'Ice Hockey', 'B', false),
('sports', 'easy', 'How many bases are on a baseball field?', 'Three', 'Four', 'Five', 'Six', 'B', false),
('sports', 'easy', 'Who holds the record for most Olympic gold medals?', 'Usain Bolt', 'Michael Phelps', 'Carl Lewis', 'Mark Spitz', 'B', false),
('sports', 'easy', 'In which year was the first Super Bowl played?', '1960', '1967', '1970', '1965', 'B', false),
('sports', 'easy', 'Which tennis player has won the most Grand Slam titles (male)?', 'Roger Federer', 'Rafael Nadal', 'Novak Djokovic', 'Pete Sampras', 'C', false),
('sports', 'easy', 'What is the national sport of Canada?', 'Ice Hockey', 'Lacrosse', 'Basketball', 'Curling', 'B', false),
('sports', 'easy', 'Which boxer was known as "The Greatest"?', 'Mike Tyson', 'Muhammad Ali', 'Sugar Ray Leonard', 'Floyd Mayweather', 'B', false),

-- Hard Questions (25)
('sports', 'hard', 'How many times has Brazil won the FIFA World Cup?', 'Four', 'Five', 'Six', 'Three', 'B', false),
('sports', 'hard', 'In which sport is the Ryder Cup contested?', 'Tennis', 'Golf', 'Cricket', 'Sailing', 'B', false),
('sports', 'hard', 'What is the height of an NBA basketball hoop in feet?', '9', '10', '11', '12', 'B', false),
('sports', 'hard', 'Which country has won the most Cricket World Cups?', 'India', 'Australia', 'West Indies', 'England', 'B', false),
('sports', 'hard', 'Who is the fastest man in the world (100m record)?', 'Usain Bolt', 'Carl Lewis', 'Justin Gatlin', 'Tyson Gay', 'A', false),
('sports', 'hard', 'How many majors has Tiger Woods won?', '12', '15', '18', '20', 'B', false),
('sports', 'hard', 'In which sport would you find a pommel horse?', 'Wrestling', 'Gymnastics', 'Polo', 'Equestrian', 'B', false),
('sports', 'hard', 'Which NBA team has won the most championships?', 'Los Angeles Lakers', 'Boston Celtics', 'Chicago Bulls', 'Golden State Warriors', 'B', false),
('sports', 'hard', 'What is the maximum break in snooker?', '100', '147', '180', '200', 'B', false),
('sports', 'hard', 'Which Formula 1 driver has won the most championships?', 'Ayrton Senna', 'Lewis Hamilton/Michael Schumacher', 'Sebastian Vettel', 'Alain Prost', 'B', false),
('sports', 'hard', 'How many players are on a rugby union team?', '11', '13', '15', '17', 'C', false),
('sports', 'hard', 'Which cyclist has won the most Tour de France titles?', 'Eddy Merckx', 'Lance Armstrong (stripped)', 'Miguel Indurain', 'Chris Froome', 'B', false),
('sports', 'hard', 'What is the diameter of a soccer ball in inches?', '7.5', '8.65', '9.5', '10', 'B', false),
('sports', 'hard', 'In which year were women first allowed to compete in the Olympics?', '1896', '1900', '1920', '1950', 'B', false),
('sports', 'hard', 'Which country won the first Rugby World Cup?', 'Australia', 'New Zealand', 'South Africa', 'England', 'B', false),
('sports', 'hard', 'What is the record for most goals in a single FIFA World Cup?', '10', '13 (Just Fontaine)', '15', '11', 'B', false),
('sports', 'hard', 'Who was the first gymnast to score a perfect 10?', 'Olga Korbut', 'Nadia Comăneci', 'Mary Lou Retton', 'Simone Biles', 'B', false),
('sports', 'hard', 'What is the fastest serve ever recorded in tennis (mph)?', '150.5', '163.7', '175.2', '155.3', 'B', false),
('sports', 'hard', 'Which jockey has won the most Kentucky Derby races?', 'Bill Shoemaker', 'Eddie Arcaro', 'Willie Shoemaker', 'Johnny Longden', 'B', false),
('sports', 'hard', 'What is the maximum weight of an Olympic shot put (men)?', '5 kg', '7.26 kg', '10 kg', '8 kg', 'B', false),
('sports', 'hard', 'In which year was the three-point line introduced to the NBA?', '1975', '1979', '1983', '1985', 'B', false),
('sports', 'hard', 'What is the record for most consecutive wins in boxing?', '70', '87 (Julio César Chávez)', '100', '50', 'B', false),
('sports', 'hard', 'Which athlete has won the most Olympic medals overall?', 'Larisa Latynina', 'Michael Phelps', 'Paavo Nurmi', 'Carl Lewis', 'B', false),
('sports', 'hard', 'What is the world record for javelin throw (men) in meters?', '85.5', '90.2', '98.48', '105.3', 'C', false),
('sports', 'hard', 'Which team has won the most Stanley Cups?', 'Toronto Maple Leafs', 'Montreal Canadiens', 'Detroit Red Wings', 'Boston Bruins', 'B', false);
